.gitignore

The ignore is from https://github.com/github/gitignore.

ignore: Add macOS, Windows and Go ignore files

---

README.md

README: Add code quality badge

---

db/db_init.go
db/interface.go
manager/Dockerfile
manager/main.go
manager/visualise/tensorboard/tensorboardIF.go
manager/worker_interface/dlk/dlk.go
manager/worker_interface/kubernetes/kubernetes.go
manager/worker_interface/nvdocker/nvidia-docker.go
manager/worker_interface/worker_interface.go
suggestion/hyperband_service.go

Store all metrics of logs in DB.
/assign @gaocegege 

New db log schema

---

OWNERS

Ref https://github.com/kubeflow/hp-tuning/issues/40

reviewers: Add @ddysher @jose5918 @mitake

---

test/workflows/environments/releasing/params.libsonnet

Related to https://github.com/kubeflow/kubeflow/issues/534
/cc YujiOshima
/cc gaocegege

Replace kubeflow-images-staging with kubeflow-images-public

---

test/workflows/components/workflows.libsonnet

Ref https://github.com/kubeflow/tf-operator/issues/567

workflows.libsonnet: Fix the image name

---

OWNERS

Ref https://github.com/kubeflow/katib/issues/82
@libbyandhelen 
Jeremy sent you an invitation to Kubeflow org and please accept it then we could add you as an reviewer.
Thanks for your contribution :tada: 
/cc @ddutta 

OWNERS: Add @libbyandhelen

---

modeldb/frontend/public/js/models.js

fix ui bug

---

pkg/db/interface.go

Fix bug mentioned [here](https://github.com/kubeflow/katib/issues/72#issuecomment-391544816)

fix get service-param-list bug

---

CHANGELOG.md

changelog: Add

---

pkg/controller/studyjobcontroller/studyjob_controller.go

Make `error` to the last postion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/185)

Update `checkStatus` return value orders

---

examples/MinikubeDemo/deploy.sh
manifests/pv/pv.yaml
manifests/pv/pvc.yaml
manifests/vizier/db/deployment.yaml
scripts/deploy.sh
test/scripts/run-tests.sh

For persistent data, add pv example for katib.
Related to #137 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/178)

Add pv example to katibDB

---

Gopkg.lock
Gopkg.toml
pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
pkg/controller/studyjobcontroller/studyjob_controller.go

We can set a `Retain` flag to `WorkerSpec` and `MetricsCollectorSpec`.
When the flag set to `False`, a worker or metrics_collector will be deleted after completed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/176)

Add Retain flag

---

examples/MinikubeDemo.md

Fix document bug.
Fix #168 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/171)

fix-MinikubeDemodox

---

examples/random-example.yaml

Fix #179 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/181)

fix random-example

---

test/scripts/build-studyjobctr.sh

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/190)

add building metrics-collector to CI

---

examples/random-example.yaml
pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
pkg/controller/studyjobcontroller/studyjob_controller.go

@YujiOshima #184 support request count: request count * request num = max suggestion num
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/193)

support request count

---

pkg/controller/studyjobcontroller/studyjob_controller.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/201)

Fix deadlock condition in ReconcileStudyJobController#Reconcile

---

examples/MinikubeDemo.md

It was somewhat difficult for me to run this GPU demo.
This patch should clarify.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/202)

Point to the example version of ConfigMap from MinikubeDemo.md

---

examples/random-example.yaml
examples/workerConfigMap.yaml
manifests/studyjobcontroller/metricsControllerConfigMap.yaml
manifests/studyjobcontroller/workerConfigMap.yaml
pkg/controller/studyjobcontroller/studyjob_controller.go

Fix manifests along with #204 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/213)

fix manifest examples

---

pkg/controller/studyjobcontroller/studyjob_controller.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/219)

Check errors in order to avoid SEGV

---

scripts/build.sh

Signed-off-by: IWAMOTO Toshihiro <iwamoto@valinux.co.jp>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/231)

Fix the build script after #208

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/239)

Add richardsliu to OWNERS/reviewer

---

OWNERS

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/247)

Add texasmichelle as reviewer

---

OWNERS

Add @richardsliu to OWNERS/owner .
/cc @gaocegege @jlewi @richardsliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/274)

add Richard Liu to OWNERS

---

cmd/ui/Dockerfile
cmd/ui/main.go
cmd/ui/template/layout.html
cmd/ui/template/study.html
cmd/ui/template/worker.html
pkg/ui/ui.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/277)

Fix katib ui resource paths

---

test/e2e/test-client.go

add e2eTest of random, grid, and hyperband suggestion algorithm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/265)

add e2eTest of each suggestion algorithm

---

pkg/controller/studyjob/manifest_parser.go

Get metrics collector template from API, not from file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/292)

get metricscollector by API

---

pkg/manager/metricscollector/meticscollector.go

For distributed TFJob/PyTorchJob, logs are collected only from the pod that acts as the master of the job.
Fixes: #294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/300)

Adding master pod check for default metric collector

---

OWNERS

Adding to owners file
/assign @jlewi @richardsliu @YujiOshima 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/304)

Adding to OWNERS file

---

pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/330)

Fix typo in json API

---

examples/pytorchjob-example.yaml

@johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/329)

Update pytorch example with latest image

---

pkg/controller/studyjob/katib_api_util.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/342)

only try to delete study info in db when in need

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/333)

Clarify the example UI is generated by random-example.

---

pkg/controller/studyjob/manifest_parser.go

Fixes: #358
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/368)

fix invalid memory address

---

examples/README.md
examples/gpu-example.yaml
examples/grid-example.yaml
examples/hypb-example.yaml

some examples use wrong worker template path format
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/378)

fix wrong example

---

test/scripts/build-earlystopping-median.sh
test/scripts/build-manager-rest.sh
test/scripts/build-manager.sh
test/scripts/build-studyjobctr.sh
test/scripts/build-suggestion-bo.sh
test/scripts/build-suggestion-grid.sh
test/scripts/build-suggestion-hyperband.sh
test/scripts/build-suggestion-nasrl.sh
test/scripts/build-suggestion-random.sh
test/scripts/build-ui.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/409)

add latest tag for katib images

---

OWNERS

I updated reviewers in OWNERS.
/assign @YujiOshima
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/419)

Add NAS team as reviewers

---

examples/pytorchjob-example.yaml

Fixes:  #347
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/446)

Updating the pytorch example image

---

manifests/v1alpha1/studyjobcontroller/mcrbac.yaml
manifests/v1alpha1/studyjobcontroller/rbac.yaml
manifests/v1alpha1/vizier/ui/rbac.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/451)

ClusterRoleBinding doesn't need namespace field

---

py/study_job_client.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/453)

fix py client import error

---

cmd/manager-rest/v1alpha2/proxy.go
manifests/v1alpha2/katib/db/deployment.yaml
manifests/v1alpha2/katib/db/secret.yaml
manifests/v1alpha2/katib/db/service.yaml
manifests/v1alpha2/katib/manager/deployment.yaml
manifests/v1alpha2/katib/manager/service.yaml
manifests/v1alpha2/katib/pv/pv.yaml
manifests/v1alpha2/katib/pv/pvc.yaml
pkg/db/v1alpha2/interface.go
scripts/v1alpha2/build.sh
scripts/v1alpha2/deploy.sh
test/e2e/v1alpha2/test-katib-manager.py
test/e2e/v1alpha2/test_requirements.txt
test/scripts/v1alpha2/build-manager-rest.sh
test/scripts/v1alpha2/build-manager.sh
test/scripts/v1alpha2/run-tests.sh

enable test for katib-manager and fix RegisterTrial error
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/478)

enable test for katib-manager

---

OWNERS

Removing inactive users from OWNERS file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/490)

Prune katib OWNERS file

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

/cc  @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/505)

Added PR and Issue template.

---

prow_config.yaml

Fixes #472 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/516)

feat(CI): Run different flow according to version

---

pkg/api/operators/apis/experiment/v1alpha2/util.go
pkg/common/v1alpha2/katib_manager_util.go
pkg/controller/v1alpha2/experiment/experiment_controller.go
pkg/controller/v1alpha2/experiment/experiment_util.go
pkg/controller/v1alpha2/experiment/util/api_util.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/519)

Delete experiment in DB if in need

---

pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
pkg/controller/v1alpha2/experiment/util/status_util.go

Fix #499 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/501)

feat(api): Add total number of trials

---

pkg/common/v1alpha2/katib_manager_util.go
pkg/controller/v1alpha2/experiment/experiment_controller.go
pkg/controller/v1alpha2/experiment/experiment_util.go
pkg/controller/v1alpha2/experiment/util/api_util.go
pkg/controller/v1alpha2/experiment/util/manifest_util.go
pkg/controller/v1alpha2/experiment/util/status_util.go
pkg/db/v1alpha2/interface.go

Part of #510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/534)

Update experiment status DB operation

---

prow_config.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/536)

Include vendor dir instead of Gopkg in prow config

---

pkg/common/v1alpha2/common.go
pkg/util/v1alpha2/metricscollector/metricscollector.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/539)

[v1alpha2] Add labels for TFjob and PytorchJob in Metrics Collector

---

prow_config.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/541)

Include suggestion manager based on version in prow

---

pkg/controller/v1alpha2/experiment/experiment_controller.go
pkg/controller/v1alpha2/experiment/experiment_status.go

We will add test for experiment-controller. Then we need to check if the status is expected. Defining status update function as a handler makes it easy. We can use a custom func to catch the request and check if the instance is expected.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/518)

fix(status): Define status handler

---

test/scripts/v1alpha2/build-suggestion-random.sh
test/scripts/v1alpha2/run-tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/543)

Enable suggestion-random image build and push in CI

---

pkg/ui/v1alpha2/types.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/545)

fix: Fix the conflicts in UI backend

---

pkg/common/v1alpha2/common.go
pkg/controller/v1alpha2/experiment/experiment_util.go
pkg/controller/v1alpha2/experiment/util/status_util.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/547)

Fix nil pointer error when create trial

---

pkg/controller/v1alpha2/experiment/experiment_controller.go
pkg/controller/v1alpha2/experiment/suggestion/suggestion.go

PR tracks the comments that were not addressed in PR #546
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/548)

Adding minor styles changes

---

test/e2e/v1alpha2/test-katib-manager.py

Added a test for getting random algorithm suggestion
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/552)

Adding test for random suggestion algorithm

---

pkg/controller/v1alpha2/experiment/suggestion/suggestion.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/553)

Fix trial requestNumber error

---

manifests/v1alpha2/katib-controller/crds.yaml

```
NAME                  STATUS      AGE
random-experiment     Succeeded   2d
random-experiment-2   Running     8m
```
```
NAME                           STATUS      AGE
random-experiment-2-6jgbqngp   Running     11s
random-experiment-2-m8rts8ft   Running     11s
random-experiment-2-rlrfgwv8   Running     11s
random-experiment-b4tc6vcw     Succeeded   2d
random-experiment-fdgzzjds     Succeeded   2d
random-experiment-kjtwzb9c     Succeeded   2d
random-experiment-r7pb6cnr     Succeeded   2d
random-experiment-whq6vc84     Succeeded   2d
random-experiment-zhmrpzlv     Succeeded   2d
random-experiment-zpr2c6xz     Succeeded   2d
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/ka …

Add status for experiment and trial in additionalPrinterColumns

---

pkg/controller/v1alpha2/experiment/manifest/generator.go
pkg/controller/v1alpha2/experiment/validation_webhook.go
pkg/controller/v1alpha2/experiment/validator/validator.go
pkg/mock/v1alpha2/experiment/manifest/producer.go
pkg/mock/v1alpha2/util/katibclient/katibclient.go
pkg/util/v1alpha2/katibclient/katib_client.go

This PR injected the client to the generator to make sure that the client is useful in validator
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/561)

feat(experiment-validator): Inject client

---

pkg/common/v1alpha2/katib_manager_util.go
pkg/controller/v1alpha2/trial/trial_controller_test.go
pkg/controller/v1alpha2/trial/util/status_util.go

Fixes: #551 
With this PR , e2e experiment run is completed with metric collection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/564)

Implement trial observation metrics

---

pkg/api/operators/apis/experiment/v1alpha2/util.go

#567 make logic opposite
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/571)

Fix finalizer cannot work

---

pkg/controller/v1alpha2/trial/trial_controller.go
pkg/controller/v1alpha2/trial/trial_controller_suite_test.go
pkg/controller/v1alpha2/trial/trial_controller_test.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/570)

feat(trial): Add more failure test cases

---

scripts/v1alpha1/undeploy.sh
scripts/v1alpha2/undeploy.sh

Fixes https://github.com/kubeflow/katib/issues/578
```release-note
NONE
```
/cc @hougangliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/579)

Added undeploy for katib.

---

cmd/ui/v1alpha2/main.go

This PR allows us run UI locally:
```
go run ./cmd/ui/v1alpha2/main.go -build-dir ./pkg/ui/v1alpha2/frontend/build --port 9999
```
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/590)

feat: Support flags in UI

---

pkg/controller/v1alpha2/experiment/managerclient/managerclient.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/594)

Mini fix for getExperimentConf

---

pkg/suggestion/v1alpha1/hyperband_service.go
pkg/suggestion/v1alpha1/hyperband_service_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/592)

Reverse logic of Less in hyperband v1alpha1

---

README.md
scripts/update-readme-toc.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/593)

doc: Update readme

---

manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml

Adding v1alpha2 to metric collector image name. 
Related: #591 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/601)

Minor changes to metric collector manifest

---

test/scripts/v1alpha1/build-earlystopping-median.sh
test/scripts/v1alpha1/build-manager-rest.sh
test/scripts/v1alpha1/build-manager.sh
test/scripts/v1alpha1/build-studyjobctr.sh
test/scripts/v1alpha1/build-suggestion-bo.sh
test/scripts/v1alpha1/build-suggestion-grid.sh
test/scripts/v1alpha1/build-suggestion-hyperband.sh
test/scripts/v1alpha1/build-suggestion-nasrl.sh
test/scripts/v1alpha1/build-suggestion-random.sh
test/scripts/v1alpha1/build-ui.sh
test/scripts/v1alpha2/build-katib-controller.sh
test/scripts/v1alpha2/build-manager-rest.sh
test/scripts/v1alpha2/build-manager.sh
test/scripts/v1alpha2/build-suggestion-random.sh
test/scripts/v1alpha2/build-ui.sh

Latest tag is provided on the wrong image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/603)

Fixing latest tag

---

examples/v1alpha2/nasjob-example-RL.yaml

Quick fix for NAS RL example in v1alpha2.
/cc @johnugeorge @hougangliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/609)

Fix nasrl example in v1alpha2

---

hack/verify-golint.sh

This is related to https://github.com/kubeflow/kfserving/issues/135
/cc @hougangliu @gaocegege 
Fixes #
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/621)

Updated help message for golint.

---

examples/v1alpha2/NAS-training-containers/RL-cifar10/Dockerfile
examples/v1alpha2/NAS-training-containers/RL-cifar10/ModelConstructor.py
examples/v1alpha2/NAS-training-containers/RL-cifar10/RunTrial.py
examples/v1alpha2/NAS-training-containers/RL-cifar10/op_library.py
examples/v1alpha2/NAS-training-containers/RL-cifar10/requirements.txt

This is the training container with model constructor for NAS RL Suggestion.
/assign @johnugeorge @hougangliu @gaocegege 
/cc @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/614)

Training Container for NAS RL Suggestion in v1alpha2

---

test/scripts/v1alpha2/build-suggestion-bo.sh

Latest tag is applied on the right image.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/627)

Fixing tag for Suggestion BO

---

cmd/suggestion/hyperband/v1alpha2/Dockerfile
cmd/suggestion/hyperband/v1alpha2/main.py
cmd/suggestion/hyperband/v1alpha2/requirements.txt
examples/v1alpha2/hyperband-example.yaml
manifests/v1alpha2/suggestion/hyperband/deployment.yaml
manifests/v1alpha2/suggestion/hyperband/service.yaml
pkg/controller/v1alpha2/experiment/experiment_controller.go
pkg/controller/v1alpha2/experiment/util/status_util.go
pkg/controller/v1alpha2/trial/trial_controller.go
pkg/suggestion/v1alpha2/hyperband_service.py
test/scripts/v1alpha2/build-suggestion-hyperband.sh
test/scripts/v1alpha2/run-tests.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/631)

v1alpha2 hyperband suggestion service

---

pkg/suggestion/v1alpha1/hyperband_service.go
pkg/suggestion/v1alpha1/hyperband_service_test.go

v1alpha1 hyperband suggestion service algorithm does not match [this paper](https://arxiv.org/pdf/1603.06560.pdf)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/634)

Fix v1alpha1 hyperband algorithm mismatch

---

pkg/controller/v1alpha2/experiment/experiment_controller.go
pkg/controller/v1alpha2/experiment/experiment_controller_suite_test.go
pkg/controller/v1alpha2/experiment/experiment_controller_test.go
pkg/controller/v1alpha2/trial/trial_controller_suite_test.go
pkg/controller/v1alpha2/trial/trial_controller_test.go

Fixes https://github.com/kubeflow/katib/issues/619
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/626)

refactor: Remove requests check for most test cases

---

scripts/mockgen.sh

Generated mock file name is wrong from the one which is in the repo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/651)

Wrong mock file name

---

test/e2e/v1alpha2/run-e2e-experiment.go
test/scripts/v1alpha2/run-tests.sh
test/workflows/components/workflows-v1alpha2.libsonnet

Added grid example to the e2e test in presubmit
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/652)

Add e2e test to presubmit

---

examples/v1alpha1/NAS-training-containers/RL-cifar10/Dockerfile
examples/v1alpha1/nasjob-example-RL.yaml
examples/v1alpha2/NAS-training-containers/RL-cifar10/Dockerfile
examples/v1alpha2/nasjob-example-RL.yaml
test/scripts/v1alpha1/build-tc-nasrl-cifar10.sh
test/scripts/v1alpha2/build-tc-nasrl-cifar10.sh
test/workflows/components/workflows-v1alpha1.libsonnet
test/workflows/components/workflows-v1alpha2.libsonnet

I added build training container image for v1alpha2.
/cc @johnugeorge @richardsliu @hougangliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/669)

Build images for nasrl training container

---

scripts/v1alpha2/build.sh
test/scripts/v1alpha2/run-tests.sh

I updated build script with implemented Suggestions in v1alpha2.
/assign @hougangliu @richardsliu @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/672)

Update Build Script for v1alpha2

---

test/scripts/v1alpha1/create-cluster.sh
test/scripts/v1alpha1/run-tests.sh
test/scripts/v1alpha2/create-cluster.sh
test/workflows/app.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/684)

Fix prow error

---

examples/v1alpha2/hyperband-example.yaml
scripts/v1alpha1/undeploy.sh
scripts/v1alpha2/deploy.sh
scripts/v1alpha2/undeploy.sh

`kubectl delete resourceType namespace/resourceName` is invalid.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/687)

Fix error of undeploy.sh

---

cmd/katib-controller/v1alpha1/Dockerfile
cmd/katib-controller/v1alpha2/Dockerfile
cmd/manager-rest/v1alpha1/Dockerfile
cmd/manager-rest/v1alpha2/Dockerfile
cmd/manager/v1alpha1/Dockerfile
cmd/manager/v1alpha2/Dockerfile
cmd/metricscollector/v1alpha1/Dockerfile
cmd/metricscollector/v1alpha2/Dockerfile
cmd/suggestion/bayesianoptimization/v1alpha1/Dockerfile
cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile
cmd/suggestion/grid/v1alpha1/Dockerfile
cmd/suggestion/grid/v1alpha2/Dockerfile
cmd/suggestion/hyperband/v1alpha1/Dockerfile
cmd/suggestion/hyperband/v1alpha2/Dockerfile
cmd/suggestion/random/v1alpha1/Dockerfile
cmd/suggestion/random/v1alpha2/Dockerfile
cmd/ui/v1alpha1/Dockerfile
cmd/ui/v1alpha2/Dockerfile

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/673)

update some dockerfiles to support power

---

pkg/controller/v1alpha2/trial/trial_controller.go

Fixes: #694
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/695)

Fix wrong end state of trial

---

test/workflows/components/workflows-v1alpha2.libsonnet

Minor fix in using the same test worker image for all workflow steps.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/720)

Update test worker image 

---

pkg/webhook/v1alpha2/webhook.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/729)

Inject pod sidecar for specified namespace

---

cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/731)

Fix bayesianoptimization build for ppc64le

---

scripts/v1alpha2/build.sh
test/scripts/v1alpha2/build-katib-controller.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/730)

fix: Add build for sidecar

---

pkg/webhook/v1alpha2/pod/inject_webhook.go
pkg/webhook/v1alpha2/webhook.go

sidecar container should only be injected into pod which is triggerred by katib.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/733)

Inject sidecar only for katib belongs

---

test/scripts/v1alpha2/build-tc-nasrl-cifar10.sh
test/scripts/v1alpha2/build-ui.sh
test/scripts/v1alpha3/build-tc-nasrl-cifar10.sh
test/scripts/v1alpha3/build-ui.sh

Timeout is changed to 20 min for long running builds.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/741)

Adding extra timeouts to builds

---

manifests/v1alpha3/katib-controller/crd-suggestion.yaml
manifests/v1alpha3/katib-controller/rbac.yaml
pkg/controller.v1alpha3/add_suggestion.go
pkg/controller.v1alpha3/consts/const.go
pkg/controller.v1alpha3/suggestion/composer/composer.go
pkg/controller.v1alpha3/suggestion/suggestion_controller.go
pkg/controller.v1alpha3/suggestion/suggestion_controller_status.go
pkg/controller.v1alpha3/suggestion/suggestion_controller_suite_test.go
pkg/controller.v1alpha3/suggestion/suggestion_controller_test.go
pkg/controller.v1alpha3/suggestion/suggestion_controller_util.go
pkg/controller.v1alpha3/suggestion/suggestionclient/fake/fake.go
pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
pkg/controller.v1alpha3/util/help.go
test/scripts/v1alpha2/run-tests.sh
test/scripts/v1alpha3/run-tests.sh
test/workflows/components/workflows-v1alpha3.libsonnet

Add the basic controller for suggestion CRD. It does not contain:
- Logic to create suggestions according to algorithms (only supports random now).
- Logic to communicate with suggestions (Use a fake implementation instead).
Ref #507 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

feat: Add suggestion controller

---

manifests/v1alpha3/katib-controller/katib-config.yaml
pkg/apis/controller/common/v1alpha3/common_types.go
pkg/webhook/v1alpha3/pod/inject_webhook.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/747)

Ignore injecting sidecar for none collector kind

---

manifests/v1alpha3/katib-controller/katib-config.yaml
pkg/apis/controller/common/v1alpha3/common_types.go
pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
pkg/webhook/v1alpha3/experiment/validator/validator.go
pkg/webhook/v1alpha3/experiment/validator/validator_test.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/749)

Experiment webhook for metricsCollector

---

manifests/v1alpha3/katib-controller/katib-config.yaml
pkg/apis/controller/experiments/v1alpha3/constants.go
pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
pkg/common/v1alpha3/katib_manager_util.go
pkg/controller.v1alpha3/consts/const.go
pkg/controller.v1alpha3/suggestion/composer/composer.go
pkg/controller.v1alpha3/suggestion/suggestion_controller.go
pkg/controller.v1alpha3/suggestion/suggestion_controller_test.go
pkg/webhook/v1alpha3/pod/inject_webhook.go
pkg/webhook/v1alpha3/webhook.go

Suggestion image mappings are populated in ConfigMap so that right suggestion algorithm services are spawned for each experiment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/754)

Adding suggestion images to configmap

---

pkg/controller.v1alpha3/experiment/experiment_controller.go

When suggestion fails, experiment is marked failed so that user gets to know the status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/773)

Marking experiment failed when suggestion fails

---

pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
pkg/apis/controller/suggestions/v1alpha3/util.go
pkg/controller.v1alpha3/suggestion/suggestion_controller.go
pkg/controller.v1alpha3/suggestion/suggestion_controller_status.go

Add status of suggestion deployment to Suggestion CR status
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/784)

Adding algorithm deployment status to Suggestion status

---

test/scripts/v1alpha3/check-katib-ready.sh
test/scripts/v1alpha3/create-cluster.sh
test/scripts/v1alpha3/run-suggestion-bayesian.sh
test/scripts/v1alpha3/run-suggestion-grid.sh
test/scripts/v1alpha3/run-suggestion-random.sh
test/workflows/components/workflows-v1alpha3.libsonnet

Run e2e tests in parallel
Fixes: #788
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/790)

Run e2e tests parallel

---

cmd/ui/v1alpha3/main.go
pkg/ui/v1alpha3/backend.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/786)

UI: Fix problems

---

pkg/controller.v1alpha3/consts/const.go
pkg/controller.v1alpha3/suggestion/suggestion_controller.go
test/e2e/v1alpha3/run-e2e-experiment.go
test/scripts/v1alpha3/run-suggestion-bayesian.sh
test/scripts/v1alpha3/run-suggestion-grid.sh
test/scripts/v1alpha3/run-suggestion-random.sh

Add events in Suggestion Controller
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/796)

feat: Add events in suggestion

---

scripts/v1alpha3/build.sh

Supports commands like: `./scripts/v1alpha3/build.sh -t v1 -r docker.io -p katib`
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/795)

build: Support arguments

---

test/scripts/v1alpha3/check-katib-ready.sh
test/scripts/v1alpha3/run-suggestion-bayesian.sh
test/scripts/v1alpha3/run-suggestion-grid.sh
test/scripts/v1alpha3/run-suggestion-random.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/799)

fix: Use commitid

---

test/scripts/v1alpha3/run-suggestion-bayesian.sh
test/scripts/v1alpha3/run-suggestion-grid.sh
test/scripts/v1alpha3/run-suggestion-random.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/802)

fix: Remove copy

---

cmd/suggestion/nasrl/v1alpha3/Dockerfile
cmd/suggestion/nasrl/v1alpha3/main.py
cmd/suggestion/nasrl/v1alpha3/requirements.txt
examples/v1alpha3/nasjob-example-RL.yaml
pkg/controller.v1alpha3/suggestion/suggestionclient/nas.go
pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
pkg/suggestion/v1alpha3/nasrl_service.py
scripts/v1alpha3/build.sh
test/scripts/v1alpha3/check-katib-ready.sh
test/scripts/v1alpha3/python-tests.sh
test/scripts/v1alpha3/run-suggestion-bayesian.sh
test/scripts/v1alpha3/run-suggestion-nasrl.sh
test/suggestion/v1alpha3/test_nasrl_service.py
test/workflows/components/workflows-v1alpha3.libsonnet

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/793)

feat: Add NAS RL based algorithm

---

examples/v1alpha3/bayesianoptimization-example.yaml
examples/v1alpha3/grid-example.yaml
test/scripts/v1alpha3/check-katib-ready.sh

Deprecated configs are removed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/803)

Removing unnecessary config from examples

---

cmd/suggestion/chocolate/v1alpha3/main.py
examples/v1alpha3/hyperband-example.yaml

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/813)

fix: Fix the type

---

test/scripts/v1alpha3/check-katib-ready.sh
test/scripts/v1alpha3/run-suggestion-bayesian.sh
test/scripts/v1alpha3/run-suggestion-grid.sh
test/scripts/v1alpha3/run-suggestion-hyperband.sh
test/scripts/v1alpha3/run-suggestion-nasrl.sh
test/scripts/v1alpha3/run-suggestion-random.sh
test/scripts/v1alpha3/run-suggestion-tpe.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/822)

fix: Build e2e-runner

---

pkg/controller.v1alpha3/util/suggestion.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/826)

fix: Support multiple namespaces when using kubectl

---

manifests/v1alpha3/katib-controller/rbac.yaml
pkg/webhook/v1alpha3/common/const.go
pkg/webhook/v1alpha3/experiment/validation_webhook.go
pkg/webhook/v1alpha3/webhook.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/828)

Make sure experiment namespace can inject metriccollector sidecar

---

manifests/v1alpha3/ui/deployment.yaml
pkg/util/v1alpha3/katibclient/katib_client.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/829)

feat: Use env var for namespace

---

examples/v1alpha3/pytorchjob-example.yaml
examples/v1alpha3/tfjob-example.yaml

Inorder to save resources, delete jobs when trials are completed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/838)

Delete jobs when trials are completed

---

cmd/ui/v1alpha3/main.go
pkg/ui/v1alpha3/backend.go
pkg/ui/v1alpha3/frontend/src/actions/nasCreateActions.js
pkg/ui/v1alpha3/frontend/src/actions/nasMonitorActions.js
pkg/ui/v1alpha3/frontend/src/components/App.jsx
pkg/ui/v1alpha3/frontend/src/components/NAS/Create/NASParameters.jsx
pkg/ui/v1alpha3/frontend/src/components/NAS/Create/Params/Trial.jsx
pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobInfo.jsx
pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobList.jsx
pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
pkg/ui/v1alpha3/frontend/src/sagas/index.js
pkg/ui/v1alpha3/hp.go
pkg/ui/v1alpha3/nas.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/839)

feat: Support namespace in NAS UI

---

pkg/ui/v1alpha3/hp.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/846)

fix: Use namespace to get trial list

---

pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Trial.jsx
pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/850)

feat: Set default namespace and template for trial

---

.dockerignore
manifests/v1alpha3/manager/deployment.yaml
pkg/controller.v1alpha3/suggestion/composer/composer.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/851)

chore: Add dockerignore, enhance liveness for manager

---

pkg/controller.v1alpha3/trial/trial_controller.go
pkg/controller.v1alpha3/trial/trial_controller_consts.go
pkg/controller.v1alpha3/trial/trial_controller_test.go
pkg/controller.v1alpha3/trial/trial_controller_util.go

Adding events to trials for better debuggability
Fixes: #848
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/852)

Adding events to trials

---

docs/algorithm-settings.md

Fixes #466 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/867)

feat: Add doc about algorithm

---

test/scripts/v1alpha3/run-pytorchjob.sh
test/scripts/v1alpha3/run-tfjob.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/875)

fix: Use binary in test

---

pkg/controller.v1alpha3/experiment/experiment_consts.go
pkg/controller.v1alpha3/experiment/experiment_controller.go
pkg/controller.v1alpha3/trial/trial_controller.go

Similar to #879 
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/880)

feat: Add events in experiment

---

Gopkg.lock
Gopkg.toml

In dep, operators are tagged to 0.7 branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/885)

Pin operators to 0.7 branch

---

pkg/job/v1alpha3/job/job.go
pkg/job/v1alpha3/kubeflow/kubeflow.go
prow_config.yaml
test/scripts/v1alpha3/build-suggestion-chocolate.sh
test/scripts/v1alpha3/build-suggestion-hyperband.sh
test/scripts/v1alpha3/build-suggestion-hyperopt.sh
test/scripts/v1alpha3/build-suggestion-nasrl.sh
test/scripts/v1alpha3/build-suggestion-skopt.sh
test/scripts/v1alpha3/check-katib-ready.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/895)

feat: Patch to fix running condition

---

pkg/db/v1alpha3/mysql/mysql.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/899)

Revert env for katib-db

---

pkg/controller.v1alpha3/consts/const.go
pkg/controller.v1alpha3/experiment/manifest/generator.go
pkg/controller.v1alpha3/suggestion/composer/composer.go
pkg/mock/v1alpha3/experiment/manifest/generator.go
pkg/mock/v1alpha3/util/katibclient/katibclient.go
pkg/util/v1alpha3/katibclient/katib_client.go
pkg/util/v1alpha3/katibconfig/config.go
pkg/webhook/v1alpha3/experiment/validator/validator.go
pkg/webhook/v1alpha3/experiment/validator/validator_test.go
pkg/webhook/v1alpha3/pod/const.go
pkg/webhook/v1alpha3/pod/inject_webhook.go

Now, a user can specify algorithmName with any value. By this PR, only valid algorithmName can be accepted
Part fix for #905 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/904)

Validate algorithm

---

cmd/suggestion/chocolate/v1alpha3/Dockerfile
cmd/suggestion/hyperband/v1alpha3/Dockerfile
cmd/suggestion/hyperopt/v1alpha3/Dockerfile
cmd/suggestion/nasrl/v1alpha3/Dockerfile
cmd/suggestion/skopt/v1alpha3/Dockerfile
test/scripts/v1alpha3/build-suggestion-chocolate.sh
test/scripts/v1alpha3/build-suggestion-hyperband.sh
test/scripts/v1alpha3/build-suggestion-hyperopt.sh
test/scripts/v1alpha3/build-suggestion-nasrl.sh
test/scripts/v1alpha3/build-suggestion-skopt.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/907)

fix: Add Suggestion into CI

---

cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile
cmd/suggestion/grid/v1alpha2/Dockerfile
cmd/suggestion/hyperband/v1alpha2/Dockerfile
cmd/suggestion/random/v1alpha2/Dockerfile
examples/v1alpha3/custom-metricscollector-example.yaml
pkg/webhook/v1alpha3/pod/const.go
pkg/webhook/v1alpha3/pod/inject_webhook.go
test/scripts/v1alpha3/run-custom-metricscollector.sh
test/workflows/components/workflows-v1alpha3.libsonnet

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/908)

Support custom metrics collector kind

---

pkg/controller.v1alpha3/experiment/manifest/generator.go
pkg/metricscollector/v1alpha3/common/const.go
pkg/mock/v1alpha3/experiment/manifest/generator.go
pkg/webhook/v1alpha3/experiment/validator/validator.go
pkg/webhook/v1alpha3/experiment/validator/validator_test.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/909)

Enhance validation for metrics collector

---

pkg/db/v1alpha3/common/const.go
pkg/db/v1alpha3/mysql/mysql.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/910)

feat: Support custom databases

---

pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/911)

Fix wrong suggestion service endpoint

---

pkg/suggestion/v1alpha3/chocolate_service.py

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/913)

Fix grid suggestion ValidateAlgorithmSettings return

---

cmd/metricscollector/v1alpha3/tfevent-metricscollector/Dockerfile.ppc64le
scripts/v1alpha3/build.sh

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/912)

tfevent-metricscollector support ppc64le

---

pkg/metricscollector/v1alpha3/tfevent-metricscollector/tfevent_loader.py

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/920)

Tfevent metriccollector fails when multiple files exist

---

pkg/webhook/v1alpha3/webhook.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/933)

Change web failPolicy to fail instead of default ingore

---

pkg/webhook/v1alpha3/pod/inject_webhook.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/969)

Remove redundant serviceAccountName assignment

---

pkg/controller.v1alpha3/experiment/experiment_controller.go
pkg/controller.v1alpha3/experiment/experiment_controller_test.go
pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
pkg/controller.v1alpha3/trial/prometheus_metrics.go
pkg/controller.v1alpha3/trial/trial_controller.go
pkg/controller.v1alpha3/trial/trial_controller_test.go
pkg/controller.v1alpha3/trial/trial_controller_util.go

Signed-off-by: yeya24 <yb532204897@gmail.com>
Similar to https://github.com/kubeflow/katib/pull/954, but for trial
Additionally, use prometheus.Registerer interface to register metrics, to avoid duplicate metrics registration in tests.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/974)

add metrics for trial

---

docs/workflow-design.md

Fixed some typos mentioned in the review of PR https://github.com/kubeflow/katib/pull/990
I decided not to change the capitalisation of the headings, as suggested in the comments on the above PR, because capitalization is a style choice and the guide isn't part of a doc set where we're looking for consistency.)
This PR doesn't change any image versions.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1001)

Fixed a few typos

---

pkg/ui/v1alpha3/frontend/src/components/Menu/Main.jsx

Updated the links to "additional information" on the Katib dashboard. We now have one link for docs (website) and another for contributors (GitHub).
Fixes https://github.com/kubeflow/katib/issues/1002
This PR does not change any image versions.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1003)

Updated links to docs/github on Katib dashboard

---

pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1012)

fix: Avoid out-of-range exception

---

pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/README.md

**What this PR does / why we need it**: This PR fixes a typo in a README.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1000)

Nerual -> Neural

---

pkg/apis/manager/v1alpha3/api.proto

* Added the version number to the API proto description, so that the docs will show which version they refer to.
* Added a description to the `TODO` comments for the early stopping feature, so that the docs give more information about what is still to do. For context, see comments on docs issue https://github.com/kubeflow/website/pull/1531#discussion_r366682651.
No change to image versions.
```release-note
NONE
```
---
This change …

Added version number and TODO descriptions to API proto

---

docs/community/adopters.md

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1019)

feat: Add adopters

---

README.md
pkg/apis/manager/README.md
pkg/apis/manager/v1alpha3/gen-doc/api.md

Updated the API doc links in the `kubeflow/katib` READMEs so that they point to the docs on kubeflow.org.
Updated the doc generation instructions to tell people where to put the generated docs next time they re-generate the docs.
Fixes https://github.com/kubeflow/katib/issues/1021
This PR does not change any image versions.
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" …

Updated links and instructions for Katib API docs

---

docs/community/adopters.md

Add [antfin](https://www.antfin.com) into list of adoptors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1025)

add antfin into list of adoptors

---

docs/community/adopters.md

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1026)

Adding cisco in Katib adopters

---

pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx

This PR fixes problem when user can't see all metrics in Trial Info graph.
Now we should see all metrics from DB in the Plot.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1027)

UI: Fix Trial Metric in the Plot

---

README.md
docs/developer-guide.md

Add links for all docs
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1024)

chore: Update docs

---

pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobPlot.jsx
pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobTable.jsx
pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx
pkg/ui/v1alpha3/frontend/src/index.js
pkg/ui/v1alpha3/hp.go

Fixes https://github.com/kubeflow/katib/issues/1030.
As well, I fixed error with date in Trial Metric Info. Since I changed formatTime to correct one in `FetchHPJobTrialInfo` function , we don't need to format date in the UI.
/assign @johnugeorge @gaocegege @hougangliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1032)

UI: Add Trial Status to HP Job Table

---

pkg/ui/v1alpha3/hp.go

Fixes https://github.com/kubeflow/katib/issues/884.
/cc @hougangliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1048)

UI: The best metrics in Trial table

---

README.md

Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1056)

MXNet -> Apache MXNet

---

docs/community/adopters.md

Adding Karrot as adopter 
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1074)

Adding Karrot as adopter 

---

cmd/ui/v1alpha3/main.go
pkg/ui/v1alpha3/backend.go
pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
pkg/ui/v1alpha3/frontend/src/components/Common/ExperimentInfoDialog.jsx
pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
pkg/ui/v1alpha3/frontend/src/components/NAS/Monitor/NASJobInfo.jsx
pkg/ui/v1alpha3/frontend/src/reducers/general.js
pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
pkg/ui/v1alpha3/frontend/src/sagas/index.js
pkg/ui/v1alpha3/hp.go

I added Experiment view Button for NAS jobs, like in HP.
Also, I moved action to view Experiment from hp to general.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1077)

UI: Add Experiment view for NAS Jobs

---

pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py

Fixes: https://github.com/kubeflow/katib/issues/1094.
I tried to run mocmaes algorithm.
The run was successful for me.
I was using search space from this example: https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/grid-example.yaml.
/cc @gaocegege @terrykong
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1097)

Fix Chocolate mocmaes algorithm name in Suggestion

---

prow_config.yaml

I updated prow config with the latest Suggestion folders.
Also, I added `examples/v1alpha3/*.yaml` folder to prow.
I think we should trigger e2e test, if we change examples.
And I added these folders to postsubmit, to be consistent with presubmit:
```
test/e2e/v1alpha3/*
manifests/v1alpha3/*
scripts/v1alpha3/*
```

Update prow config with the latest folders

---

pkg/ui/v1alpha3/frontend/src/components/HP/Create/YAML.jsx
pkg/ui/v1alpha3/frontend/src/components/NAS/Create/YAML.jsx

I changed style for submit Experiment to be consistent with other YAML sheets.
/cc @johnugeorge @gaocegege

UI: Change style for submit Experiment from YAML

---

ROADMAP.md

I added ENAS steps to the ROADMAP 2020.

Add ENAS enhancements to ROADMAP

---

ROADMAP.md
pkg/suggestion/v1alpha3/chocolate_service.py
pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
pkg/suggestion/v1alpha3/internal/search_space.py
pkg/suggestion/v1alpha3/skopt_service.py

Fix typo and add a minor refactoring change.
None
None
```release-note
NONE
```

Fix typo in suggestion packages

---

docs/proposals/suggestion.md

Remove Anneal from supported algorthms because it is unsupported:
https://github.com/kubeflow/katib/blob/cd27da5bcd9a36c922570e2994fdfb6a69b17eb5/pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py#L20-L21
None
None
```release-note
NONE
```

Remove Anneal from supported algorithms

---

test/scripts/v1alpha3/run-suggestion-cmaes.sh
test/workflows/components/workflows-v1alpha3.libsonnet

Part of https://github.com/kubeflow/katib/issues/1152.
I added E2E test for CMA-ES Goptuna Suggestion.
/assign @c-bata 

E2E test for CMA-ES Suggestion

---

manifests/v1alpha3/katib-controller/katib-config.yaml
prow_config.yaml
test/e2e/v1alpha3/resume-e2e-experiment.go
test/e2e/v1alpha3/run-e2e-experiment.go
test/scripts/v1alpha3/build-suggestion-darts.sh
test/workflows/components/workflows-v1alpha3.libsonnet

Part of https://github.com/kubeflow/katib/issues/1167.
I added build image for DARTS suggestion in CI and update katib-config.

Build image for DARTS Suggestion

---

examples/v1alpha3/nas/darts-cnn-cifar10/model.py
examples/v1alpha3/nas/darts-cnn-cifar10/run_trial.py
examples/v1alpha3/nas/darts-example-gpu.yaml
pkg/suggestion/v1alpha3/nas/darts/README.md
pkg/suggestion/v1alpha3/nas/darts/service.py

I added more algorithm settings for DARTS suggestion.

Add more algorithm settings to DARTS

---

README.md

Add citation information

---

examples/v1beta1/metric-strategy-example.yaml

I changed example for metric strategies to support new Trial Template API in v1beta1.
/assign @sperlingxx 

Modify metric strategies example for new Trial Template

---

docs/community/adopters.md

Rename Ant Financial to Ant Group

---

pkg/webhook/v1beta1/experiment/validator/validator.go
pkg/webhook/v1beta1/experiment/validator/validator_test.go

Related: https://github.com/kubeflow/katib/issues/1229.
I added validation for different parameter types.
See comment: https://github.com/kubeflow/katib/issues/1229#issuecomment-649817821.

Validation for parameters in HP Experiments

---

.github/ISSUE_TEMPLATE/bug_report.md

Hope this helps new bug reporters

Add hints to obtain Kubeflow and Minikube version

---

pkg/ui/v1beta1/frontend/src/components/HP/Monitor/HPJobTable.jsx

Fixes: https://github.com/kubeflow/katib/issues/1095.
I added sorting by each Trial table column in Experiment monitor.
/cc @terrykong

UI: Sorting for Trials information table

---

pkg/apis/controller/common/v1beta1/common_types.go
pkg/apis/controller/experiments/v1beta1/experiment_types.go
pkg/apis/v1beta1/openapi_generated.go
pkg/apis/v1beta1/swagger.json

I fixed few typos in API comments.
/assign @gaocegege @johnugeorge.

Fix few API comments typos

---

pkg/util/v1beta1/katibclient/katib_client.go
test/e2e/v1beta1/resume-e2e-experiment.go
test/e2e/v1beta1/run-e2e-experiment.go
test/scripts/v1beta1/run-from-volume.sh
test/workflows/components/workflows-v1beta1.libsonnet

I added e2e test for ResumePolicy = FromVolume.

Add e2e test for FromVolume ResumePolicy

---

pkg/controller.v1beta1/experiment/experiment_controller.go
pkg/controller.v1beta1/experiment/suggestion/suggestion.go
pkg/controller.v1beta1/suggestion/suggestion_controller.go
pkg/controller.v1beta1/suggestion/suggestion_controller_util.go
pkg/controller.v1beta1/trial/trial_controller.go

After this PR, we will use logger in suggestion controller util with Suggestion `namespace/name`.
That can improve logging.
Also, I changed some log message to be consistent.
/assign @gaocegege @johnugeorge @sperlingxx

Use Logger in suggestion controller util

---

README.md
sdk/python/v1alpha3/README.md
sdk/python/v1beta1/README.md

I updated doc for v1beta1 and v1alpha3 SDK.
/assign @sperlingxx @gaocegege @johnugeorge

Update docs for v1beta1 SDK

---

.travis.yml
docs/new-algorithm-service.md
prow_config.yaml
test/scripts/v1alpha3/check-katib-ready.sh
test/scripts/v1alpha3/create-cluster.sh
test/scripts/v1beta1/build-file-metrics-collector.sh
test/scripts/v1beta1/build-tfevent-metrics-collector.sh
test/scripts/v1beta1/check-katib-ready.sh
test/scripts/v1beta1/create-cluster.sh
test/workflows/components/workflows-v1alpha3.libsonnet
test/workflows/components/workflows-v1beta1.libsonnet

We should use `automl-ci` project to run our prow infra.

Switch test from kubeflow-ci to automl-ci project.

---

docs/community/adopters.md

reapply #1325 which was closed accidentially

[Adopters] change adopter of Ant Group

---

sdk/python/v1beta1/README.md
sdk/python/v1beta1/examples/cmaes-and-resume-policies.ipynb
sdk/python/v1beta1/examples/nas-with-darts.ipynb

I added examples (CMA-ES and DARTS) for v1beta1 SDK.

Add SDK examples for v1beta1

---

README.md

Related: #1332.
I will debug the infra in this PR.

Improve Katib README

---

manifests/v1beta1/katib-controller/crd-experiment.yaml

no more information needed, it is clear.

fix typo in crd-experiment

---

manifests/v1beta1/mysql-db/deployment.yaml

See this: https://github.com/kubeflow/manifests/pull/1562.
/assign @gaocegege @johnugeorge @thesuperzapper

Add recreate strategy to MySQL deployment

---

ADOPTERS.md

Following the WG discussion in last meeting - #1400

Adding to ADOPTERS.md

---

sdk/python/v1beta1/examples/cmaes-and-resume-policies.ipynb
sdk/python/v1beta1/examples/nas-with-darts.ipynb

We should fix our SDK examples to work with Katib 0.10.

Fix SDK examples for 0.10 version

---

ADOPTERS.md

add adopter
Fixes #
```release-note
```

add adopter

---

cmd/cert-generator/v1beta1/Dockerfile
scripts/v1beta1/build.sh
scripts/v1beta1/release.sh
test/scripts/v1beta1/setup-katib.sh
test/workflows/components/workflows-v1beta1.libsonnet

I added Katib cert generator build to the CI process.

Add cert generator build to the CI

---

Makefile
scripts/v1beta1/build.sh
scripts/v1beta1/push.sh
test/workflows/components/workflows-v1beta1.libsonnet

Related: https://github.com/kubeflow/katib/issues/1469.
I added new ui image to the `build.sh`, `push.sh` scripts and CI pre-build process.
/assign @kimwnasptd 
/cc @yanniszark @gaocegege @johnugeorge

Add new UI image to release scripts

---

sdk/python/v1beta1/README.md
sdk/python/v1beta1/docs/KatibClient.md
sdk/python/v1beta1/kubeflow/katib/api/katib_client.py

I updated documentation for the latest changes in Katib SDK API client.
Please, can you take a look.
We probably should automate this process in the future.

Update documentation for SDK Katib Client

---

README.md
scripts/update-readme-toc.sh

I added Blog Post section in the README, it might be useful for our users.

Add Blog Posts in the README

---

test/scripts/v1beta1/setup-katib.sh

Cherry pick commit for the fix CI process on the release branch.
/assign @yanniszark @gaocegege @johnugeorge

Automated cherry pick of #1508: Fix setup Katib script to work on the release branch

---

docs/presentations.md

I added the new presentations in the list from 2021.
/assign @kimwnasptd @gaocegege @johnugeorge

Add the new Katib presentations 2021

---

pkg/webhook/v1beta1/experiment/validator/validator.go

I fixed gofmt error.
Check this run: https://github.com/kubeflow/katib/runs/2718289703.
/cc @johnugeorge @anencore94

Fix gofmt to validate Experiment name

---

operators/README.md

See https://github.com/canonical/bundle-kubeflow/issues/371
cc @knkski @evilnick

Adds docs on how to use within KF

---

.github/PULL_REQUEST_TEMPLATE.md

As we discussed earlier at the community meeting, we should add documentation check list to the PR template.

Add Doc checklist to PR template

---

examples/v1beta1/tekton/README.md

Our image names have been changed.
This command should be modified also.

Fix grep in Tekton Experiment Doc

---

README.md
docs/presentations.md

I added our AutoML and Training Summit info.

Add AutoML and Training WG Summit July 2021

---

README.md
manifests/v1beta1/components/controller/katib-config.yaml
pkg/suggestion/v1beta1/optuna/service.py
prow_config.yaml
scripts/v1beta1/push.sh
test/scripts/v1beta1/setup-katib.sh
test/workflows/components/workflows-v1beta1.libsonnet

I updated CI and some scripts for Optuna Suggestion.
/assign @c-bata @g-votte @gaocegege @johnugeorge

Add Optuna Suggestion to Katib CI

---

test/workflows/components/workflows-v1beta1.libsonnet

Adding tests in multiple steps for reducing test flakinesss and better resource utilisation

Adding tests in multiple steps

---

CHANGELOG.md

I updated Changelog for Katib 0.12.0-rc.0 release.
I combined our work in these sections:
```
New Features
Algorithms and Components
UI Features
Documentation
Bug Fixes
Misc
```
@gaocegege @johnugeorge @jbottum Please let me know what do you think about it ?
cc @c-bata @g-votte @anencore94 @RFMVasconcelos @knkski 
/hold for the review

Update Changelog for Katib 0.12.0-rc.0 release

---

CHANGELOG.md

This is Changelog for Katib 0.12.0-rc.1 release.

Add Changelog for Katib 0.12.0-rc.1 release

---

pkg/new-ui/v1beta1/OWNERS

I noticed that I didn't have permissions to approve PRs for the new UI so I added an OWNERS file.
I added myself and @andreyvelich as reviewers since we've been keeping a close eye on the PRs for the UI, but feel free to discuss any suggestions. @andreyvelich is also an approver in the entire repo so I thought it was redundant to also add him here.

Add OWNERS file for the new ui

---

CHANGELOG.md

This is Changelog for Katib 0.12.0 release.

Add Changelog for Katib 0.12.0 release

---

README.md

Update link to training operator

---

examples/v1beta1/sdk/cmaes-and-resume-policies.ipynb
examples/v1beta1/sdk/nas-with-darts.ipynb

I updated SDK examples to support newer version of Katib SDK.
Once Katib 0.12 is released, we can merge this PR.

Modify SDK examples for Katib 0.12 release

---

CHANGELOG.md

I updated Changelog for Katib `0.13.0-rc.0` release.
I combined our work in these sections:
```
New Features
Algorithms and Components
UI Features
Documentation
Bug Fixes
Misc
```
Please let me know what do you think about it ?
/cc @gaocegege @johnugeorge @tenzen-y @anencore94 @knkski @kimwnasptd @terrytangyuan @seong7 @eliaskoromilas @DnPlas @DomFleischmann @henrysecond1 @alexeykaplin @haoxins @midhun1998 @ca-scribner 
cc @jbottum  
/hold for the review

Update Changelog for Katib v0.13.0-rc.0 release

---

sdk/python/v1beta1/setup.py

Update our SDK version to the 0.13.0 in the master branch.

Update sdk version to 0.13.0 version

---

examples/v1beta1/fpga/xgboost-example.yaml

**What this PR does**:
* Update Xilinx AWS VU9P F1 platform

Update FPGA XGBoost example

---

cmd/earlystopping/medianstop/v1beta1/requirements.txt

I upgraded the Kubernetes Python client to 22.6.0.
Fixes #
**Checklist:**

Upgrade the Kubernetes Python client to 22.6.0

---

manifests/v1beta1/components/mysql/mysql.yaml

I upgraded the MYSQL of the katib-mysql version to v8.0.29.
Fixes #
**Checklist:**

Upgrade mysql version to v8.0.29

---

test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh

Update CI training operator image to v1.5.0-rc.0

Updating the training operator image in CI

---

scripts/v1beta1/push.sh

Push script was not updated with new image names

Fix push script to include new images

---

.github/workflows/test-go.yaml
Makefile
docs/developer-guide.md
go.mod
go.sum
hack/swagger/main.go
hack/verify-golangci-lint.sh
test/e2e/v1beta1/hack/aws/run-e2e-experiment.go
test/e2e/v1beta1/hack/gh-actions/run-e2e-experiment.go

I upgraded Go version to v1.18.
Fixes #
**Checklist:**

[chore] Upgrade Go version to v1.18

---

sdk/python/v1beta1/setup.py

Update Katib SDK version to latest in the master

Update Katib SDK version

---

test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh

Update the training operator image to latest v1.5.0 release

Update training operator image in CI

---

cmd/suggestion/optuna/v1beta1/requirements.txt
pkg/suggestion/v1beta1/optuna/base_service.py

To use the latest Optuna, the version is v3, which is going to be released Aug. 29.
Fixes #1851 
**Checklist:**

Upgrade Optuna from v2.x.x to v3.0.0

---

README.md

I updated the katib version to v0.14.0 in docs.
Fixes #
**Checklist:**

Update the katib version in docs

---

.github/workflows/test-charmed-katib.yaml

As discussed in [this](https://github.com/kubeflow/katib/pull/1986#issuecomment-1294402001), I changed the UI component to `katib-new-ui` for Charmed GH-Action.
/assign @andreyvelich @DomFleischmann @knkski @ca-scribner 
Fixes #
**Checklist:**

Use the katib-new-ui for Charmed gh-actions

---

pkg/new-ui/v1beta1/backend.go
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.html
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.spec.ts
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.module.ts
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.html
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.scss
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.spec.ts
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.ts
pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.module.ts
pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts

**What this PR does / why we need it:**
Cherry-pick of https://github.com/kubeflow/katib/pull/2101 on release-0.15.

Automated cherry pick of #2101: Create the LOGS tab of Trial's details page in KWA

---

sdk/python/v1beta1/setup.py

Bump Katib Python SDK to 0.15.0rc1 version

---

CHANGELOG.md

I added Changelog for Katib v0.15.0-rc.1
/assign @gaocegege @johnugeorge @tenzen-y @elenzio9

Add Changelog for Katib v0.15.0-rc.1

---

sdk/python/v1beta1/setup.py

Bump Katib Python SDK to 0.15.0 version

---

pkg/ui/v1beta1/frontend/src/app/services/experiment-form.service.ts

**What this PR does / why we need it**: UI Fix for for ResumePolicy as 'Never' by default
Fixes #
**Checklist:**

Default Resume Policy to never from UI

---

cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
cmd/suggestion/nas/enas/v1beta1/requirements.txt
examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
sdk/python/v1beta1/kubeflow/katib/constants/constants.py

Cherry-pick of https://github.com/kubeflow/katib/pull/2201 on release-0.16.
Fixes #
**Checklist:**

Automated cherry pick of #2201: Upgrade Tensorflow version to v2.13.0

---

CHANGELOG.md
docs/release/changelog.py

I added Changelog for Katib v0.16.0-rc.0
I identify a few **Breaking Changes.**
Thanks everyone for your contributions!
Please take a look.
/cc @tenzen-y @johnugeorge @gaocegege @elenzio9 @droctothorpe @nagar-ajay @orfeas-k 
cc @kubeflow/release-team

Add Changelog for Katib v0.16.0-rc.0

---

.github/workflows/build-and-publish-images.yaml
.github/workflows/e2e-test-darts-cifar10.yaml
.github/workflows/e2e-test-enas-cifar10.yaml
.github/workflows/e2e-test-pytorch-mnist.yaml
.github/workflows/e2e-test-simple-pbt.yaml
.github/workflows/e2e-test-tf-mnist-with-summaries.yaml
.github/workflows/e2e-test-ui-random-search-postgres.yaml
.github/workflows/template-publish-image/action.yaml
.github/workflows/template-setup-e2e-test/action.yaml
.github/workflows/test-go.yaml
.github/workflows/test-lint.yaml
.github/workflows/test-node.yaml
.github/workflows/test-python.yaml

Fixes https://github.com/kubeflow/katib/issues/2323
**Checklist:**

Update outdated actions

---

CHANGELOG.md

I updated Changelog for Katib 0.17.0-rc.0.
Thanks everyone for your contribution to Katib 🎉 
/hold for review
/assign @kubeflow/wg-training-leads @kubeflow/release-team @lkaybob @ckcd @bharathk005 @shipengcheng1230 @droctothorpe @Electronic-Waste @sifa1024 @tarilabs

Add Changelog for Katib v0.17.0-rc.0

---

.github/ISSUE_TEMPLATE/config.yml
README.md

Fixes: https://github.com/kubeflow/katib/issues/2343
I updated Slack invitation for Katib Slack channel.
Does this description look good to you @orfeas-k @kubeflow/wg-training-leads ?

Update Slack Invitation

---

sdk/python/v1beta1/README.md

Fixes: https://github.com/kubeflow/katib/issues/2283.
I added info about Python version support for Katib SDK.
/assign @tenzen-y @droctothorpe @johnugeorge

[SDK] Explain Python version support cycle

---

.github/workflows/test-go.yaml

Fix warning: Restore cache failed
https://github.com/kubeflow/katib/actions/runs/9485512882/job/26140408190#step:3:18
the speed of runs can be improved.
Fixes #
**Checklist:**

Use cache-dependency-path in actions/setup-go for CI workflow

---

OWNERS
sdk/python/v1beta1/OWNERS

This PR proposes to promote new reviewers for Katib project:
- @Electronic-Waste for contributions to the Katib control plane and helping with other PRs.
- @helenxie-bit for contributions to the Katib SDK including enhancements in Training Operator to support `tune` API for LLMs.
Thank you for your great contributions and we are looking forward to continue working with all of you 🎉 
/assign @kubeflow/wg-automl-leads

Promote @Electronic-Waste and @helenxie-bit as Katib reviewers

---

pkg/ui/v1beta1/frontend/src/app/enumerations/metrics-collector.ts
pkg/ui/v1beta1/frontend/src/app/models/experiment.k8s.model.ts
pkg/ui/v1beta1/frontend/src/app/models/trial.k8s.model.ts
pkg/ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.html
pkg/ui/v1beta1/frontend/src/app/services/experiment-form.service.ts

After we rename `None` collector to `Push` collector in https://github.com/kubeflow/katib/pull/2369, we have not updated the UI so far. So I do some changes in the UI package.
Fixes #
**Checklist:**

fix(ui): update None Collector with Push Collector.

---

CHANGELOG.md

Part of: https://github.com/kubeflow/katib/issues/2386
I added changelog for Katib v0.18.0-rc.0. Please take a look.
I grouped PRs by:
```
```
Thanks everyone for your contributions 🎉 
/assign @kubeflow/wg-training-leads @Electronic-Waste @helenxie-bit @kubeflow/release-team @shashank-iitbhu @saileshd1402 @mahdikhashan @forsaken628 @Jerry-yz @AydanPirani @mahdikhashan @Doris-xm @lianghao208 @caiofralmeida @gonmmarques @Ygnas @droctothorpe @jaffe-fly @eltociear @tariq-hasan @ckcd @vihangm 
/hold for review

Add Changelog for Katib v0.18.0-rc.0

---

docs/proposals/README.md

Add 'KEP Usage' KEP and template link

---

pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
test/unit/v1beta1/metricscollector/test_tfevent_metricscollector.py
test/unit/v1beta1/requirements.txt

cherry-pick of https://github.com/kubeflow/katib/issues/2466
Fixes -
**Checklist:**

cherry-picked `c18035e1`

---

.github/workflows/trivy-scan.yaml

Related: https://github.com/kubeflow/community/issues/885
We want to introduce Trivy CVEs scan.
/cc @kubeflow/kubeflow-trainer-team @kubeflow/kubeflow-sdk-team @thesuperzapper @andyatmiami

feat(ci): Add Trivy Vulnerability Scan
