kubeflow/katib

- README.md
- docs/CLI.md
- docs/developer-guide.md
- docs/getting-start.md
The README is a liitle long and I think there are something that the users do not need know. Thus I split it into different parts in `docs`.
PTAL
> doc: Refactor

- README.md
typos, tenses, and some cleanup
> Fixing some basic typos in README

- suggestion/grid/main.go
- suggestion/grid_service.go
- suggestion/hyperband/main.go
- suggestion/hyperband_service.go
- suggestion/random/main.go
- suggestion/random_service.go
- suggestion/types.go
- Fix a typo in hyperband service `MaxParallel`
- Move the service to the suggestion package
- Move the port to the suggestion package
- Fix import order and some variable names
Close #18 
> suggestion: Refactor

- docs/developer-guide.md
- manifests/vizier/suggestion/grid/deployment.yaml
- manifests/vizier/suggestion/hyperband/deployment.yaml
- manifests/vizier/suggestion/random/deployment.yaml
- suggestion/grid/Dockerfile
- suggestion/hyperband/Dockerfile
- suggestion/random/Dockerfile
- Reduce the time spent on building (80% faster in China)
- Reduce the size of the image （891 MB -> 16.7 MB (2% of the original image))
/assign @YujiOshima
> Dockerfile: Use multiple stage builds

- dlk/Dockerfile
- manager/modeldb/Dockerfile
Same as #25 
/assign @gaocegege
> Dockerfile: Support multiple stage build in dlk and frontend

- build.sh
- cli/Dockerfile
- docs/getting-start.md
- manager/Dockerfile
- manifests/vizier/core/deployment.yaml
Same as #23 
I am not sure if we should copy the CLI from the docker container. But I follow the convention to use centos instead of alpine to get the runnable binary from the container.
/assign @YujiOshima
> Dockerfile: Support multiple stage build in manager and cli

- manifests/dlk/deployment.yaml
- manifests/vizier/suggestion/random/deployment.yaml
There are some unnecessary setting in manifests.
> delete unnecessary settings

- docs/getting-start.md
I uploaded a binary for linux amd64. And I think it is time to update the docs.
> docs: Update katib-cli

- cli/Dockerfile
> Dockerfile: Use alpine as base image

- test/scripts/run-tests.sh
Not to use a const value for the number of pods.
> improve test script

- dlk/dlkmanager/learningTask.go
- manager/main.go
- manager/modelstore/modeldb.go
Fix bug that the last trial of the study won't be saved when a study has completed.
I changed to save models of all completed trials before breaking `trialIteration`.
> Fix modelsave

- manager/main.go
- Remove the flag `init` since it is not used in the code
- Remove the function `spawn-worker` since it is not used in the code
- Fix some variable names
> main.go: Fix style

- scripts/deploy.sh
- test/scripts/build-earlystoppings.sh
- test/scripts/build-manager.sh
- test/scripts/build-suggestions.sh
- test/scripts/run-tests.sh
- test/workflows/components/workflows.libsonnet
For more robust parallel build, separate build containers with components(manager, suggestions, and earlystopping)
Depends on #74
> Build parallel

- docs/getting-start.md
> Some fix to getting-started.md

- pkg/manager/worker/kubernetes/kubernetes.go
Fix drop logs bug.
Log collection should be done after worker status is checked.
> save logs after check status

- docs/getting-start.md
Added the missing command to download katib-cli on mac.
> Add katib-cli download command for Mac

- examples/GKEDemo/GKE-Demo.md
- examples/GKEDemo/deploy.sh
- examples/GKEDemo/destroy.sh
- examples/GKEDemo/manifests/modeldb/frontend/service.yaml
- examples/GKEDemo/manifests/vizier/core/service.yaml
- examples/MinikubeDemo.md
- examples/MinikubeDemo/destroy.sh
- examples/MinikubeDemo/manifests/modeldb/frontend/service.yaml
- examples/MinikubeDemo/manifests/vizier/core/service.yaml
In the getting-start demo, using `kubectl port-forward` is probably easier way to access to katib services.
/assign @gaocegege 
> use kubectl port-forward in demos

- pkg/api/api.proto
Let me know in case you prefer to use tabs everywhere. But, in general, it is better to use one consistently rather than a mix of both.
> Fix indentation to use spaces (instead of a mix of tabs and spaces)

- cmd/manager/main.go
- pkg/manager/worker/kubernetes/kubernetes.go
- pkg/suggestion/hyperband_service.go
- test/e2e/test-client.go
* When calling `GetWorkers`, the status of workers are updated. You can get the latest status of workers.
* Add GetWorker check to e2e test.
/assign @gaocegege
> Update status of workers in GetWorkers

- examples/worker-config.yml
The mxnet/python image version was updated on docker hub, the worker pods in the example study fail to start. mxnet folder seems to be missing from / in the latest image, I see the following error in the logs - 
`python: can't open file '/mxnet/example/image-classification/train_mnist.py': [Errno 2] No such file or directory`
> pin mxnet/python image version

- examples/MinikubeDemo/manifests/vizier/suggestion/hyperband/deployment.yaml
- examples/MinikubeDemo/manifests/vizier/suggestion/hyperband/service.yaml
Corrected typos in hyperband example yml, from 'hayperband' to 'hyperband' in order to make it possible to deploy the pods and services.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/146)
> Corrected typos in hyperband example yml

- manifests/studyjobcontroller/crd.yaml
While CustomResourceDefinition.spec.scope defaults to Namespaced,
omitting this generates a validation error. Just supply the default.
Signed-off-by: IWAMOTO Toshihiro <iwamoto@valinux.co.jp>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/191)
> Fix CRD validation

- pkg/controller/studyjobcontroller/studyjob_controller.go
Avoid ResourceExhausted error when the log of a worker is very long.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/200)
> enlarge max of check status grpc

- examples/random-example.yaml
- examples/workerConfigMap.yaml
- manifests/studyjobcontroller/metricsControllerConfigMap.yaml
- manifests/studyjobcontroller/workerConfigMap.yaml
- pkg/controller/studyjobcontroller/studyjob_controller.go
*Check request count when the next suggestion is scheduled. Avoid completing studyjob during evaluating workers.
* Fix cont check when ReqestCount is not set.
This depends on #213
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/214)
> Fix reqest count

- pkg/db/db_init.go
- pkg/db/interface.go
This PR ensures worker logs are stored correctly.
Also tweak DB table definitions for consistency.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/222)
> Fix storelogs

- pkg/suggestion/hyperband_service.go
Fix slice range when minimize optimization, in this PR.
This prevents "index out of range" of tids from occurring in later for loops.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/226)
> fix slice range

- pkg/db/interface.go
The retry logic is used to generate an unique ID, but if there is
another error the DB code can fall into an infinite loop.
Signed-off-by: IWAMOTO Toshihiro <iwamoto@valinux.co.jp>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/229)
> Only retry an INSERT operation on unique constraint violation

- pkg/db/interface.go
- pkg/db/interface_test.go
Add basic UTs for DB methods. Also fixes bugs in those methods discovered during the process.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/234)
> More DB unit tests

- pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
- pkg/controller/studyjobcontroller/studyjob_controller.go
In order to accurately control the resources, we need to get the start and end time of the worker.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/236)
> add starttime and completiontime to worker

- pkg/db/interface_test.go
- test/scripts/unit-test.sh
- test/workflows/components/workflows.libsonnet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/243)
> Add mysql based unit tests

- examples/MinikubeDemo.md
- examples/MinikubeDemo/deploy.sh
Fixes: https://github.com/kubeflow/katib/issues/250
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/252)
> Change deploy.sh for Minikube example

- manifests/vizier/core/deployment.yaml
- manifests/vizier/db/deployment.yaml
- manifests/vizier/db/secret.yaml
- pkg/db/interface.go
- scripts/deploy.sh
- test/scripts/run-tests.sh
For security reasons, we better to (a). factor out hard-coded mysql root password and use Secret instead + (b). set dynamically generated random password.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/253)
> Set MYSQL_ROOT_PASSWORD via Secret

- manifests/vizier/db/secret.yaml
Commit b6f8e07d26a ("Update manifests (#246)") has just changed the
namespace as a whole. This new manifest should be updated as well.
Fixes: 67e94c7697b ("Set MYSQL_ROOT_PASSWORD via Secret (#253)")
Signed-off-by: Koichiro Den <den@valinux.co.jp>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/260)
> Fix incorrectly set namespace

- Gopkg.lock
- Gopkg.toml
- manifests/studyjobcontroller/metricsControllerConfigMap.yaml
- pkg/controller/studyjob/pod_control.go
- pkg/controller/studyjob/studyjob_controller.go
This is to ensure that tf-operator can be imported to katib. Katib uses controller-runtime which is compatible with k8s 1.10.1. Tf-operator uses 1.10.0 (upgrading to 1.11.2 breaks a lot of things).
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/256)
> Downgrade kubernetes dependency to 1.10.1

- pkg/suggestion/grid_service_test.go
- pkg/suggestion/hyperband_service_test.go
- pkg/suggestion/random_service_test.go
add unit test of ranfom algorithm, grid algorithm, and hyperband algorithm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/237)
> add UT of each suggestion algorithm

- manifests/vizier/db/deployment.yaml
- manifests/vizier/db/secret.yaml
- pkg/db/interface.go
- pkg/db/interface_test.go
When we run `./scripts/deploy.sh` for the first time, `vizier-core` is highly likely to undergo a few times of "Pod Restart". This is because `vizier-db` takes much longer time to become ready. This PR intends to have `vizier-core` wait for DB to become ready, so that we no longer see any pod Restart if all components are properly deployed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/261)
> Prevent pod restarts caused by slow db boot

- pkg/ui/ui.go
Fix Bug in UI
* UI show wrong value when the value of metrics is empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/238)
> fix uncompleted value in ui

- pkg/db/interface.go
- pkg/db/interface_test.go
- pkg/mock/db/db.go
Will be needed by future API expansions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/269)
> Add Update{Study,Trial}

- pkg/suggestion/grid_service.go
Fix timing to determine slice size. With this fix, error due to the empty part of the slice doesn't occur.
(Fixes: https://github.com/kubeflow/katib/issues/215)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/271)
> fix timing to determine slice size in grid search

- Gopkg.lock
- Gopkg.toml
- examples/tfjob-example.yaml
- manifests/studyjobcontroller/rbac.yaml
- manifests/studyjobcontroller/tfjobsCrd.yaml
- pkg/api/operators/apis/addtoscheme_tfjob_v1beta1.go
- pkg/controller/studyjob/const.go
- pkg/controller/studyjob/studyjob_controller.go
- scripts/deploy.sh
- test/scripts/run-tests.sh
This is the first iteration for #39.
The example provided is trivially simple. The code is borrowed from https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist_with_summaries.py. It only uses 1 TF worker and exposes learning_rate and batch_size as tunable hyperparameters.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/267)
> POC: Katib integration with tf-operator

- manifests/studyjobcontroller/rbac.yaml
After https://github.com/kubeflow/katib/pull/256, when StudyJobs are deleted we need to manually delete pods created by the study jobs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/278)
> Allow studyjobcontroller to delete pods

- examples/MinikubeDemo.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/280)
> fix typo error

- examples/MinikubeDemo.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/282)
> fix typo error for MinikubeDemo

- test/scripts/create-cluster.sh
K8s cluster 1.9 is no more supported in us-east1-d zone which is used for ci tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/286)
> Update k8s cluster version to 1.10

- Gopkg.lock
- Gopkg.toml
- cmd/metricscollector/main.go
- examples/pytorchjob-example.yaml
- manifests/studyjobcontroller/metricsControllerConfigMap.yaml
- manifests/studyjobcontroller/pytorchjobsCrd.yaml
- manifests/studyjobcontroller/rbac.yaml
- pkg/api/operators/apis/addtoscheme_pytorchjob_v1beta1.go
- pkg/controller/studyjob/const.go
- pkg/controller/studyjob/manifest_parser.go
- pkg/controller/studyjob/studyjob_controller.go
- pkg/manager/metricscollector/meticscollector.go
- scripts/deploy.sh
- test/scripts/run-tests.sh
This PR tracks
1. Integration of Pytorch job in Katib Studyjob
2. Support multiple worker kinds in the default Metric Collector
Related:  #39 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/283)
> Support Pytorch job in Katib

- pkg/controller/studyjob/const.go
- pkg/controller/studyjob/manifest_parser.go
- pkg/controller/studyjob/studyjob_controller.go
studyJob should go to 'Failed' status when worker kind is invalid
fixes: #285
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/287)
> fix invalid worker kind issue

- pkg/controller/studyjob/katib_api_util.go
- pkg/controller/studyjob/studyjob_controller.go
Fixes: #289
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/290)
> fix studyJob status suggestionCount mismatch error

- examples/MinikubeDemo/deploy.sh
We need to fix two deploy.sh when components updated, so I fixed deploy.sh in MinikubeDemo to use scripts/deploy.sh for maintainability.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/284)
> Use same deploy.sh when deploy katib components

- pkg/manager/studyjobclient/studyjobclient.go
I added namespace parameter to studyJob client API functions.
After this we can use the API not only inside containers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/288)
> Extend studyjob client API 

- manifests/studyjobcontroller/metricsControllerConfigMap.yaml
- manifests/studyjobcontroller/workerConfigMap.yaml
- pkg/controller/studyjob/manifest_parser.go
- pkg/controller/studyjob/studyjob_controller.go
- pkg/types.go
Fixes: #301
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/302)
> studyJob with non-kubeflow namespace cannot work

- pkg/controller/studyjob/studyjob_controller.go
Now, when metricsCollector for a worker failed to be created, the worker job status in studyjob.status.trials will not be updated (blocked in Running), and the corresponding job will not be deleted even completed.
Fixes: #298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/299)
> sync up worker status all the time

- OWNERS
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/310)
> add hougangliu as a reviewer

- Gopkg.lock
- pkg/controller/studyjob/katib_api_util.go
- pkg/controller/studyjob/manifest_parser.go
- pkg/controller/studyjob/utils.go
Fixes: #297
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/308)
> validate studyJob when first reconcile it

- examples/pytorchjob-example.yaml
1. Added distributed pytorch mnist example
2. Since all changes are merged into the default metric collector,  overriden metric collector is removed from the example.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/309)
> Adding distributed pytorch example for katib

- cmd/metricscollector/main.go
- manifests/studyjobcontroller/metricsControllerConfigMap.yaml
- manifests/studyjobcontroller/studyjobcontroller.yaml
- pkg/controller/studyjob/manifest_parser.go
- pkg/types.go
Fixes: #323
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/324)
> katib should be able to be deployed in any namespace

- examples/xgboost-bayesian-example.yaml
This example uses the image built from https://github.com/kubeflow/examples/tree/master/xgboost_ames_housing.
The hyperparameters being tuned are:
- Number of boost trees
- learning rate
We are trying to minimize the mean_absolute_error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/320)
> Add xgboost example using Bayesian optimization

- pkg/api/operators/apis/studyjob/v1alpha1/studyjob_types.go
EarlyStoppingParameterID should not be shown in studyjob status to mislead user since EarlyStopping feature cannot work now.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/336)
> omit empty fields for studyjob status

- docs/developer-guide.md
Easier for new-to-go developers to get up and running.
Looks like Google protobufs might also be a dependency?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/369)
> Include go dependencies in developer-guide.md

- test/scripts/run-tests.sh
- test/scripts/unit-test.sh
It has been using the cluster where argo ran
Hopefully fixes #359
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/360)
> Properly initialize CI cluster credential

- py/study_job_client.py
add studyjob python client so that other kubeflow components can use it to get/create/delete studyjob  handily.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/379)
> add studyjob python client

- manifests/studyjobcontroller/crd.yaml
```
NAME                     CONDITION   AGE
random-example-default   Completed   13m
test-grid                Running     3s
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/389)
> show studyjob condition when run kubectl get

- cmd/manager/main_test.go
- pkg/db/interface_test.go
- test/scripts/create-cluster.sh
I deleted ModelDB from unit tests in db. 
Right now, Katib doesn't use ModelDB.
As well, I changed version of cluster to 1.11 to pass presubmit tests.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/391)
> Delete modeldb from unit tests

- pkg/controller/studyjob/studyjob_controller.go
- pkg/controller/studyjob/utils.go
During StudyJob run, there are no more operator specific code. The unstructured is used to create the resource, get the resource and get the status
The only remaining is the watch changes that has to be separately handled in #317. Current controller runtime code(0.1.7 and less) doesn't support dynamic watch. Refer: https://github.com/kubernetes-sigs/kubebuilder/issues/422  
Related: #341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/387)
> Removing Operator specific handling during a StudyJob run

- manifests/studyjobcontroller/rbac.yaml
- manifests/studyjobcontroller/service.yaml
- manifests/studyjobcontroller/studyjobcontroller.yaml
- pkg/controller/studyjob/katib_api_util.go
- pkg/controller/studyjob/studyjob_controller.go
- pkg/controller/studyjob/utils.go
- pkg/controller/studyjob/validating_webhook.go
- test/e2e/invalid-studyjob.yaml
- test/e2e/valid-studyjob.yaml
- test/scripts/run-tests.sh
If create/update a studyJob with bad CR manifest or invalid configuration, k8s api
server will reject the request.
Fixes: #314
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/383)
> add validating webhook for studyJob

- cmd/metricscollector/main.go
- manifests/studyjobcontroller/metricsControllerConfigMap.yaml
Instead of returning, metric collector must fail if unable to collect logs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/405)
> Metric collector must fail on error

- docs/developer-guide.md
Fixes: https://github.com/kubeflow/katib/issues/403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/415)
> Fix path to API protobuf in developer guide

- examples/NAS-training-containers/cifar10/requirements.txt
Fix the package version of tensorflow-gpu to be 1.12.0 and keras to be 2.2.4.
The training container uses CUAD 9.0, which is compatible with tensorflow-gpu 1.12. The default version of tensorflow-gpu in pip has just changed to 1.13.1, which uses CUDA 10.0. Not specifying the tf version will lead to cuda library not found error.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/418)
> Fix the package version in training container

- pkg/suggestion/NAS_Reinforcement_Learning/README.md
- pkg/suggestion/nasrl_service.py
In practice, even the training container is correctly implemented, trials may fail due to a variety of reasons such as insufficient GPU memories. If trials fail, `GetEvaluationResult()` will return None. The suggestion should be able to handle that exception. My solution is: 
- If not all the trials failed, use the metrics of the successful ones to do the update
- If all the trials failed:
1. Firstly, try to respawn the previous trials after sleeping for `RESPAWN_SLEEP` seconds.
2. If respawning the trials for `RESPAWN_LIMIT` times still cannot collect valid results, then fail the task because it may indicate that the training container has errors.
Besides, this PR also fixes some small bugs and adds some important TODOs.
An example of fault handling output
``` …
```
> Add fault tolerance support for trial failure

- manifests/vizier/db/deployment.yaml
I try to run katib on GKE, but vizier-db cannot start with following error.
```
Initializing database
2019-03-14T07:13:42.050153Z 0 [Note] Basedir set to /usr/
2019-03-14T07:13:42.050470Z 0 [Warning] The syntax '--symbolic-links/-s' is deprecated and will be removed in a future release
2019-03-14T07:13:42.051712Z 0 [ERROR] --initialize specified but the data directory has files in it. Aborting.
2019-03-14T07:13:42.051812Z 0 [ERROR] Aborting
```
It is due to `lost+found` directory in mounted path.
This PR is a same solution as below.
https://github.com/kubeflow/kubeflow/blob/4e6c645eeee0915999c33bf6772d2a996cb55ee4/kubeflow/katib/vizier.libsonnet#L303-L306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Change datadir for avoid failure due to lost+found

- pkg/controller/studyjob/studyjob_controller.go
The resources which has same namespacedname are never reconciled concurrently.  This behavior is guaranteed by [workqueue](https://godoc.org/k8s.io/client-go/util/workqueue).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/444)
> Remove redundant lock

- pkg/manager/metricscollector/metricscollector.go
Labels were renamed in job operators:
Related: https://github.com/kubeflow/pytorch-operator/pull/146 https://github.com/kubeflow/tf-operator/pull/951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/447)
> Fix labels matching the job operator implementation

- README.md
- docs/developer-guide.md
- docs/rest-api.md
- examples/v1alpha1/README.md
- pkg/api/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/452)
> Update REAME example links for v1alpha1

- prow_config.yaml
Fix https://github.com/kubeflow/katib/issues/374
/cc @alexandraj777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/467)
> chore: Skip test when code is not changed

- manifests/v1alpha1/vizier/ui/deployment.yaml
We missed Service Account in Katib UI deployment. 
We should add it, since we have rbac for the UI: https://github.com/kubeflow/katib/blob/master/manifests/v1alpha1/vizier/ui/rbac.yaml#L19
/assign @hougangliu @YujiOshima 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/469)
> Add serviceAccountName in UI deployment

- pkg/db/v1alpha2/db_init.go
- pkg/db/v1alpha2/interface.go
- pkg/db/v1alpha2/interface_test.go
`condition` is keyword of mysql, we need escape it in sql, otherwise an error in your SQL syntax occurs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/476)
> katib manager db error

- pkg/util/v1alpha2/katibclient/katib_client.go
Quick fix for KatibClient structure name to make it exportable to other services. 
In the UI we need this client.
/assign @hougangliu @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/483)
> Fix KatibClient name in v1alpha2

- README.md
I believe these are outdated. TODOs can be found in issues/code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/468)
> Remove outdated TODOs in README.md

- examples/NAS-Envelopenet-trainingcontainer/Dockerfile
- examples/NAS-Envelopenet-trainingcontainer/README.md
- examples/NAS-Envelopenet-trainingcontainer/cell.py
- examples/NAS-Envelopenet-trainingcontainer/cell_classification.py
- examples/NAS-Envelopenet-trainingcontainer/cell_init.py
- examples/NAS-Envelopenet-trainingcontainer/cell_main.py
- examples/NAS-Envelopenet-trainingcontainer/cifar10_input.py
- examples/NAS-Envelopenet-trainingcontainer/evaluate.py
- examples/NAS-Envelopenet-trainingcontainer/model_constructor.py
- examples/NAS-Envelopenet-trainingcontainer/net.py
- examples/NAS-Envelopenet-trainingcontainer/requirements.txt
- examples/NAS-Envelopenet-trainingcontainer/run_trial.py
- examples/NAS-Envelopenet-trainingcontainer/test.py
This PR has all files for the training and evaluation required in NAS Envelopenet Suggestion service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/429)
> Training container for NAS Envelopenet

- pkg/common/v1alpha1/common.go
- pkg/common/v1alpha2/common.go
- pkg/controller/v1alpha1/studyjob/katib_api_util.go
- pkg/controller/v1alpha1/studyjob/manifest_parser.go
- pkg/controller/v1alpha1/studyjob/studyjob_controller.go
- pkg/controller/v1alpha2/experiment/util/manifest_util.go
- pkg/suggestion/v1alpha1/grid_service.go
- pkg/suggestion/v1alpha1/hyperband_service.go
- pkg/suggestion/v1alpha1/random_service.go
- pkg/ui/ui.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/491)
> add common package

- pkg/controller/v1alpha2/experiment/experiment_util.go
- pkg/controller/v1alpha2/experiment/util/manifest_util.go
- pkg/controller/v1alpha2/experiment/util/webhook_util.go
- pkg/controller/v1alpha2/trial/trial_controller.go
Controller-side changes for #442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/496)
> v1alpha2 metrics collector - controller

- docs/developer-guide.md
This can help dev to check more detail for what is wrong with
`dep ensure` if there are some errors.
/cc @hougangliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/504)
> Enabled verbose logging for dev guide.

- Gopkg.lock
- cmd/katib-controller/v1alpha2/main.go
- pkg/controller/v1alpha2/consts/const.go
- pkg/controller/v1alpha2/experiment/experiment_controller.go
- pkg/controller/v1alpha2/experiment/suggestion/fake/fake.go
- pkg/controller/v1alpha2/experiment/suggestion/suggestion.go
- pkg/controller/v1alpha2/experiment/util/api_util.go
- pkg/util/v1alpha2/katibclient/katib_client.go
There are some benefits to define an interface instead of using util.GetSuggestions function:
- Easy to test and maintain. We can write unit test cases for the interface.
- Easy to integrate. We can mock the suggestion when testing the experiment controller, or use a fake controller to run the experiment without affecting the real logic.
This PR:
- added a CLI argument to control if we use fake implementation in the controller. If not, now we will always return an error becuase we do not implement suggestion logic now.
```
-fake-experiment-suggestion
Use the fake suggestion in experiment controller
````
- added a interface about suggestion.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> refactor(suggestion): Use interface

- pkg/common/v1alpha2/common.go
- pkg/common/v1alpha2/katib_manager_util.go
- pkg/controller/v1alpha2/experiment/util/api_util.go
- pkg/db/v1alpha2/interface.go
Part of #510 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/509)
> create experiment in db

- prow_config.yaml
files in `manifests`, `scripts` and `test/e2e` are used for test, they are useful during presubmit, but for postsubmit, these files should not trigger corresponding workflow
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/520)
> Fix prow to trigger corresponding workflow

- prow_config.yaml
I imported a never used dep in lock, this PR is to remove it. Sorry about it.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/521)
> godep: Remove useless dep

- pkg/db/v1alpha2/interface.go
- pkg/db/v1alpha2/interface_test.go
- test/scripts/v1alpha2/unit-test.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/524)
> Fix ut test and enable ut-test of v1alpha2

- Gopkg.lock
- examples/v1alpha2/pytorchjob-example.yaml
- pkg/api/operators/apis/addtoscheme_pytorchjob_v1beta2.go
- pkg/api/operators/apis/addtoscheme_tfjob_v1beta2.go
- pkg/common/v1alpha2/common.go
- pkg/controller/v1alpha2/experiment/util/webhook_util.go
- pkg/controller/v1alpha2/trial/trial_controller.go
- pkg/controller/v1alpha2/trial/util/status_util.go
This PR adds support for TF v1beta2 and PyTorch v1beta2 job. Pytorch example is added. 
/assign @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/512)
> Support for Custom Job resources

- pkg/db/v1alpha2/interface.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/529)
> Fix wrong error-handling logic in db interface

- pkg/controller/v1alpha2/trial/trial_controller.go
Fix #531 
We will meet an error during the creation and retry it again and again. I strongly suggest using state compare pattern instead of current state machine based implementation. But it is another topic.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/kati …
> fix: Avoid side effect

- manifests/v1alpha2/katib/manager-rest/deployment.yaml
- manifests/v1alpha2/katib/manager-rest/service.yaml
- scripts/v1alpha2/build.sh
- scripts/v1alpha2/deploy.sh
- test/scripts/v1alpha2/run-tests.sh
Adding manifests for rest server for API manger
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/542)
> Adding manifests for manager rest

- pkg/api/operators/apis/experiment/v1alpha2/experiment_defaults.go
- pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
- pkg/api/operators/apis/experiment/v1alpha2/zz_generated.deepcopy.go
- pkg/common/v1alpha2/katib_manager_util.go
- pkg/controller/v1alpha2/experiment/experiment_controller.go
- pkg/controller/v1alpha2/experiment/suggestion/fake/fake.go
- pkg/controller/v1alpha2/experiment/suggestion/suggestion.go
- pkg/controller/v1alpha2/experiment/util/status_util.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/546)
> Implement GetSuggestions for general suggestion

- cmd/earlystopping/medianstopping/v1alpha1/main.go
- cmd/katib-controller/v1alpha1/main.go
- cmd/katib-controller/v1alpha2/main.go
- cmd/manager-rest/v1alpha1/proxy.go
- cmd/manager-rest/v1alpha2/proxy.go
- cmd/manager/v1alpha1/main.go
- cmd/manager/v1alpha2/main.go
- cmd/metricscollector/v1alpha1/main.go
- cmd/metricscollector/v1alpha2/main.go
- cmd/suggestion/grid/v1alpha1/main.go
- cmd/suggestion/hyperband/v1alpha1/main.go
- cmd/suggestion/random/v1alpha1/main.go
- pkg/controller/v1alpha1/studyjob/katib_api_util.go
- pkg/controller/v1alpha1/studyjob/studyjob_controller.go
- pkg/controller/v1alpha1/studyjob/utils.go
- pkg/db/v1alpha1/db_init.go
- pkg/db/v1alpha1/interface.go
- pkg/db/v1alpha2/db_init.go
- pkg/db/v1alpha2/interface.go
- pkg/earlystopping/v1alpha1/medianstopping.go
- pkg/manager/modelstore/modeldb.go
- pkg/manager/v1alpha1/metricscollector/metricscollector.go
- pkg/suggestion/v1alpha1/grid_service.go
- pkg/suggestion/v1alpha1/hyperband_service.go
- pkg/suggestion/v1alpha1/random_service.go
- pkg/ui/v1alpha1/ui.go
- pkg/util/v1alpha2/metricscollector/metricscollector.go
- test/e2e/v1alpha1/test-client.go
Fixes part of https://github.com/kubeflow/katib/issues/506
```release-note
Used klog for katib.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/526)
> Used klog for katib - part 1.

- examples/v1alpha2/nasjob-example-RL.yaml
- pkg/api/operators/apis/experiment/v1alpha2/experiment_types.go
I added NAS RL example yaml for v1alpha2 and fix small bug in Experiment API for NAS config.
/cc @hougangliu @richardsliu @gaocegege @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/554)
> Add NAS RL yaml example for v1alpha2

- manifests/v1alpha1/studyjobcontroller/metricsControllerConfigMap.yaml
- manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
Fixes: #549
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/550)
> Fix default metricsController wrong args

- prow_config.yaml
Postsubmit jobs fail currently because workflow pods name length exceeds 63 characters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/562)
> Reducing the Prow workflow name length 

- pkg/api/operators/apis/experiment/v1alpha2/util.go
This PR is to avoid the potential bug of finalizers. The object cannot be deleted without the PR.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/567)
> fix: Check if the deletion time is nil or zero

- pkg/controller/v1alpha2/experiment/experiment_util.go
- pkg/controller/v1alpha2/experiment/manifest/generator.go
- pkg/controller/v1alpha2/experiment/manifest/generator_test.go
- pkg/controller/v1alpha2/experiment/validator/validator.go
- pkg/controller/v1alpha2/experiment/validator/validator_test.go
- pkg/mock/v1alpha2/experiment/manifest/producer.go
This PR unified the interface. Buffer should not be returned.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/568)
> refactor: Unify the interface

- pkg/api/operators/apis/trial/v1alpha2/trial_types.go
- pkg/controller/v1alpha2/experiment/experiment_util.go
- pkg/controller/v1alpha2/trial/trial_controller.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/572)
> Retain for job and metricsCollector

- cmd/manager/v1alpha1/main_test.go
- cmd/manager/v1alpha2/main_test.go
- hack/update-gofmt.sh
- hack/verify-gofmt.sh
- hack/verify-golint.sh
- pkg/common/v1alpha2/common.go
- pkg/common/v1alpha2/katib_manager_util.go
- pkg/controller/v1alpha1/studyjob/studyjob_controller.go
- pkg/db/v1alpha1/interface_test.go
- pkg/db/v1alpha2/interface_test.go
- pkg/suggestion/v1alpha1/hyperband_service_test.go
- test/e2e/v1alpha1/test-client.go
Fixes #
```release-note
NONE
```
/cc @hougangliu @gaocegege @richardsliu 
I will try to enable this in CI later.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/573)
> Adding go tools scripts - part 1

- pkg/controller/v1alpha2/trial/managerclient/managerclient.go
- pkg/controller/v1alpha2/trial/trial_controller.go
- pkg/controller/v1alpha2/trial/trial_controller_consts.go
- pkg/controller/v1alpha2/trial/trial_controller_test.go
- pkg/controller/v1alpha2/trial/trial_controller_util.go
- pkg/mock/v1alpha2/trial/managerclient/katibmanager.go
Now the code to communicate with katib manager to get the log is hard coded in the main workflow. Thus we cannot run unit test because in unit test we do not have such a manager instance. This PR moves the function call to managerclient to mock it in test.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/569)
> refactor: Use manager client to get log for test

- manifests/v1alpha1/studyjobcontroller/crd.yaml
- manifests/v1alpha2/katib-controller/crd-experiment.yaml
- manifests/v1alpha2/katib-controller/crd-trial.yaml
```
NAME                STATUS      AGE
random-experiment   Succeeded   23h
NAME                         STATUS      AGE
random-experiment-4x8q6r6d   Succeeded   23h
random-experiment-5bvj7rrz   Succeeded   23h
NAME                STATUS      AGE
random-experiment   Succeeded   23h
NAME                         STATUS      AGE
random-experiment-4x8q6r6d   Succeeded   23h
random-experiment-5bvj7rrz   Succeeded   23h
NAME                STATUS      AGE
random-experiment   Succeeded   23h
NAME                         STATUS      AGE
random-experiment-4x8q6r6d   Succeeded   23h
random-experiment-5bvj7rrz   Succeeded   23h
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/576)
> Add categories for katib CRDs

- scripts/v1alpha1/undeploy.sh
- scripts/v1alpha2/undeploy.sh
I think, we should move deletion for PV under Katib-db.
Persistent Volume can't be deleted before db.
It will stuck in deletion step, because it used by Katib-db.
/assign @gyliu513 @hougangliu 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/587)
> Change undeploy script

- Makefile
- docs/developer-guide.md
Fixes #
```release-note
NONE
```
/cc @hougangliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/585)
> Default make target to v1alpha2.

- manifests/v1alpha2/katib-controller/katib-controller.yaml
- manifests/v1alpha2/katib/manager/deployment.yaml
- manifests/v1alpha2/katib/manager/service.yaml
- manifests/v1alpha2/katib/suggestion/random/deployment.yaml
- manifests/v1alpha2/katib/ui/deployment.yaml
- manifests/v1alpha2/katib/ui/rbac.yaml
- manifests/v1alpha2/katib/ui/service.yaml
- scripts/v1alpha2/deploy.sh
- test/scripts/v1alpha2/build-ui.sh
- test/scripts/v1alpha2/run-tests.sh
/assign @andreyvelich @johnugeorge @hougangliu 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/591)
> feat: Add UI in manifests v1alpha2

- pkg/controller/v1alpha1/studyjob/studyjob_controller.go
- pkg/suggestion/v1alpha1/hyperband_service.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/596)
> Fix issue of hyperband suggestion service cannot move on

- pkg/db/v1alpha1/interface.go
- pkg/db/v1alpha2/interface.go
I faced with the same error as here: https://github.com/kubeflow/katib/issues/340.
Problem was with my Coredns in Kubernetes cluster. After I changed pod network from `Flannel` to `Calico`, it was fixed.
I didn't see any logs from the katib-manager and it was hard to found this problem. 
I think, we should print these error messages to the user, then it will be easier to find the problem.
/cc @gaocegege @johnugeorge @hougangliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/588)
> Check error in OpenSQLConnection

- pkg/manager/v1alpha1/metricscollector/metricscollector.go
When I configure wrong metrics-collector role for `list` pods in namespace `kubeflow` by mistake, metricsCollectors always goes to `Error` with message `F0528 09:59:09.429051       1 main.go:81] Failed to collect logs: No Pods are found in Job v2cc12862537d2e9`, which is really confusing user.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/600)
> Mini fix for v1alpha1 metricsCollector

- pkg/controller/v1alpha2/experiment/managerclient/managerclient.go
Fixes #
```release-note
NONE
```
/cc @hougangliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/606)
> fix make check

- .travis.yml
Fixes https://github.com/kubeflow/katib/issues/607
```release-note
NONE
```
/cc @gaocegege @hougangliu @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/608)
> Enabled make check in travis.

- pkg/controller/v1alpha2/experiment/experiment_controller.go
During reconcile, CreateTrials and GetSuggestion calls should be skipped if add count is zero.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/617)
> Skip creating trials if add count is zero

- pkg/controller/v1alpha2/trial/trial_controller.go
- pkg/controller/v1alpha2/trial/trial_controller_util.go
Fixes: #615 
Trial status is updated only if trial observation field is updated. (This will be set if metrics are collected)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/616)
> Set trial completion status only after metric collection

- pkg/util/v1alpha2/katibclient/katib_client.go
To use Experiment CRD we need to add the Scheme to the Katib Client. 
Without this Scheme, we will have this error in Katib Client:
```
no kind is registered for the type v1alpha2.Experiment
no kind is registered for the type v1alpha2.ExperimentList
```
/assign @johnugeorge @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/620)
> Fix Scheme in Katib Client for v1alpha2

- cmd/suggestion/grid/v1alpha2/Dockerfile
- cmd/suggestion/grid/v1alpha2/main.py
- cmd/suggestion/grid/v1alpha2/requirements.txt
- examples/v1alpha2/grid-example.yaml
- manifests/v1alpha2/suggestion/grid/deployment.yaml
- manifests/v1alpha2/suggestion/grid/service.yaml
- pkg/suggestion/v1alpha2/grid_service.py
- scripts/v1alpha2/deploy.sh
- scripts/v1alpha2/undeploy.sh
- test/scripts/v1alpha2/build-suggestion-grid.sh
- test/scripts/v1alpha2/run-tests.sh
This tracks the implementation of  v1alpha2 grid search suggestion algorithm
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/622)
> Implementing v1alpha2 grid search suggestion algorithm

- test/e2e/v1alpha2/test-katib-manager.py
Test for grid suggestion algorithm is added.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/628)
> Add tests for grid suggestion algorithm

- pkg/controller/v1alpha2/trial/trial_controller.go
Pods have to be deleted when jobs are deleted.  Hence, DeletionPropogation strategy is set to Foreground.(https://github.com/kubernetes/kubernetes/blob/release-1.7/staging/src/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L370)
Fixes: #597
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/632)
> Adding cascading delete of pods when jobs are deleted

- pkg/common/v1alpha2/katib_manager_util.go
- pkg/controller/v1alpha2/experiment/managerclient/managerclient.go
If algorithm settings are present in the experiment, it has to be updated in algorithm extra settings via UpdateAlgorithmExtraSettings call. The suggestion algorithms look for algorithm settings using GetAlgorithmExtraSettings call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/630)
> Update Algorithm extra settings during experiment creation

- pkg/db/v1alpha2/interface.go
- pkg/db/v1alpha2/interface_test.go
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/633)
> Fix sql syntax for UpdateAlgorithmExtraSettings

- pkg/controller/v1alpha2/experiment/experiment_controller.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/647)
> feat(experiment): Delete dup trials

- examples/v1alpha2/hyperband-example.yaml
- pkg/controller/v1alpha2/experiment/managerclient/managerclient.go
- pkg/suggestion/v1alpha2/hyperband_service.py
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/648)
> v1alpha2 hyperband suggestion service validation

- pkg/controller/v1alpha2/experiment/experiment_controller.go
- pkg/controller/v1alpha2/experiment/experiment_controller_suite_test.go
- pkg/controller/v1alpha2/experiment/experiment_controller_test.go
Unit test will use the same real API server for all test cases. And there are some uncertain problems during experiment test. Ref #604 
This PR is to avoid adding webhooks to avoid it.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/657)
> fix: Do not use webhook in UT

- manifests/v1alpha1/studyjobcontroller/metricsControllerConfigMap.yaml
- manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
This changes the `spec.concurrencyPolicy` of the metric collector 
cron-job from "Allow" (default) to "Forbid". The cronjob used to
create a new job even if the previous job had not succeeded. On
high-load clusters this could lead to a high number of jobs which
never finished. 
**Which issue(s) this PR fixes** *:
This fixes #659 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/660)
> MetricController: Run only a single job per task

- manifests/v1alpha1/studyjobcontroller/metricsControllerConfigMap.yaml
- manifests/v1alpha1/studyjobcontroller/studyjobcontroller.yaml
- manifests/v1alpha1/vizier/core-rest/deployment.yaml
- manifests/v1alpha1/vizier/core/deployment.yaml
- manifests/v1alpha1/vizier/earlystopping/medianstopping/deployment.yaml
- manifests/v1alpha1/vizier/suggestion/bayesianoptimization/deployment.yaml
- manifests/v1alpha1/vizier/suggestion/grid/deployment.yaml
- manifests/v1alpha1/vizier/suggestion/hyperband/deployment.yaml
- manifests/v1alpha1/vizier/suggestion/nasenvelopenet/deployment.yaml
- manifests/v1alpha1/vizier/suggestion/nasrl/deployment.yaml
- manifests/v1alpha1/vizier/suggestion/random/deployment.yaml
- manifests/v1alpha1/vizier/ui/deployment.yaml
- manifests/v1alpha2/katib-controller/katib-controller.yaml
- manifests/v1alpha2/katib-controller/metricsControllerConfigMap.yaml
- manifests/v1alpha2/manager-rest/deployment.yaml
- manifests/v1alpha2/manager/deployment.yaml
- manifests/v1alpha2/suggestion/bayesianoptimization/deployment.yaml
- manifests/v1alpha2/suggestion/grid/deployment.yaml
- manifests/v1alpha2/suggestion/hyperband/deployment.yaml
- manifests/v1alpha2/suggestion/nasrl/deployment.yaml
- manifests/v1alpha2/suggestion/random/deployment.yaml
- manifests/v1alpha2/ui/deployment.yaml
- test/scripts/v1alpha1/run-tests.sh
- test/scripts/v1alpha2/run-tests.sh
After this patch, user can install katib individually (not install kubeflow) with latest images by `deploy.sh`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/682)
> Use latest katib images to deploy katib

- test/scripts/v1alpha1/run-tests.sh
- test/scripts/v1alpha2/run-tests.sh
I think, we can use the latest tag in e2e tests.
Here: https://github.com/kubeflow/katib/blob/master/test/scripts/v1alpha2/build-katib-controller.sh#L41, while we are building images, we assign latest tag to the images.
It is not necessary to take version from `git describe --tags --always --dirty`.
/assign @johnugeorge @hougangliu @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/686)
> Change Image Tags to the latest in e2e tests

- pkg/webhook/v1alpha2/pod/const.go
- pkg/webhook/v1alpha2/pod/inject_webhook.go
- pkg/webhook/v1alpha2/pod/utils.go
1. support kubernetes`Job` pod metrics collector injection, not just Pytorch and tfjob worker kind
2. Tfjob/pytorch job labels backward compatibility
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/738)
> MetricsCollector pod injection for katib job

- prow_config.yaml
v1alpha3 paths are wrong after directory restructuring.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/752)
> Fix v1alpha3 paths in prow

- pkg/controller.v1alpha3/experiment/experiment_util.go
Best Parameter assignment is not populated in Experiment as trial spec was not updated.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/751)
> Populate Parameter assignments in trials

- pkg/db/v1alpha3/interface.go
If password is not set, DB should not have password.
Related: #725
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/756)
> Removing backup db password

- pkg/controller.v1alpha3/experiment/experiment_controller_test.go
- pkg/controller.v1alpha3/suggestion/suggestion_controller.go
- pkg/mock/v1alpha3/experiment/manifest/generator.go
- pkg/mock/v1alpha3/util/katibclient/katibclient.go
- pkg/util/v1alpha3/katibclient/katib_client.go
- pkg/webhook/v1alpha3/experiment/validator/validator_test.go
- test/e2e/v1alpha3/run-e2e-experiment.go
/assign @johnugeorge 
```
2019/09/19 10:34:09 Waiting for Experiment hyperopt-random-example to finish.
2019/09/19 10:34:09 Experiment hyperopt-random-example's trials: 2 trials, 0 pending trials,
2 running trials, 0 killed trials, 0 succeeded trials, 0 failed trials.
2019/09/19 10:34:09 Optimal Trial for Experiment hyperopt-random-example: {[] {[]}}
2019/09/19 10:34:09 Experiment hyperopt-random-example's conditions: [{Created True ExperimentCreated Experiment is created 2019-09-19 10:33:49 +0800 CST 2019-09-19 10:33:49 +0800 CST} {Running True ExperimentRunning Experiment is running 2019-09-19 10:33:51 +0800 CST 2019-09-19 10:33:51 +0800 CST}]
```
**Which issue(s) this PR fixes** *(optional, in `fixes …
> feat: Add more output in e2e test for debug purpose and fix test cases

- cmd/suggestion/hyperopt/v1alpha3/Dockerfile
- cmd/suggestion/hyperopt/v1alpha3/main.py
- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/suggestion/composer/composer.go
- pkg/suggestion/v1alpha3/base_health_service.py
- pkg/suggestion/v1alpha3/hyperopt_service.py
- scripts/v1alpha3/build.sh
- test/scripts/v1alpha3/python-tests.sh
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/779)
> feat: Add GRPC health check in suggestions

- cmd/suggestion/hyperopt/v1alpha3/requirements.txt
- pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
grpc.WaitForReady(true) waits  for ready in GRPC calls. All packages are versioned for reproducibility
Related: https://github.com/grpc/grpc-go/issues/2636
Related: https://github.com/grpc/grpc-go/pull/2503
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/785)
> Wait for GRPC server to be up

- cmd/suggestion/skopt/v1alpha3/Dockerfile
- cmd/suggestion/skopt/v1alpha3/main.py
- cmd/suggestion/skopt/v1alpha3/requirements.txt
- examples/v1alpha3/skopt-bayesian-optimization-example.yaml
- manifests/v1alpha3/katib-controller/katib-config.yaml
- pkg/controller.v1alpha3/suggestion/composer/composer.go
- pkg/controller.v1alpha3/suggestion/suggestion_controller.go
- pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
- pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
- pkg/suggestion/v1alpha3/skopt_service.py
- scripts/v1alpha3/build.sh
- test/scripts/v1alpha3/build-suggestion-skopt.sh
- test/scripts/v1alpha3/python-tests.sh
- test/scripts/v1alpha3/run-tests.sh
- test/suggestion/v1alpha3/test_skopt_service.py
- test/workflows/components/workflows-v1alpha3.libsonnet
Support bayesian with the help of skopt.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/777)
> feat: Add bayesian

- cmd/suggestion/chocolate/v1alpha3/Dockerfile
- cmd/suggestion/chocolate/v1alpha3/main.py
- cmd/suggestion/chocolate/v1alpha3/requirements.txt
- examples/v1alpha3/chocolate-grid-example.yaml
- manifests/v1alpha3/katib-controller/katib-config.yaml
- pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
- pkg/suggestion/v1alpha3/chocolate_service.py
- scripts/v1alpha3/build.sh
- test/scripts/v1alpha3/build-suggestion-chocolate.sh
- test/scripts/v1alpha3/python-tests.sh
- test/scripts/v1alpha3/run-tests.sh
- test/suggestion/v1alpha3/test_chocolate_service.py
- test/suggestion/v1alpha3/test_chocolate_service.py.failed
- test/suggestion/v1alpha3/test_requirements.txt
- test/workflows/components/workflows-v1alpha3.libsonnet
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/780)
> feat: Add grid with the help of chocolate

- pkg/controller.v1alpha3/trial/trial_controller.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
When job fails, trial is marked as failed. 
Currently, status was not updated if trial observation was not available.  This was true  for both successful and failed jobs.  This PR skips status update only for successful jobs  if trial observation is not available.
Fixes: #759 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/791)
> Mark trial as failed when job fails

- examples/v1alpha3/bayesianoptimization-example.yaml
- examples/v1alpha3/grid-example.yaml
- examples/v1alpha3/random-example.yaml
- examples/v1alpha3/tfjob-example.yaml
- examples/v1alpha3/tpe-example.yaml
- manifests/v1alpha3/katib-controller/katib-config.yaml
- pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
- pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
- pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
- pkg/suggestion/v1alpha3/skopt_service.py
- test/scripts/v1alpha3/run-suggestion-bayesian.sh
- test/scripts/v1alpha3/run-suggestion-grid.sh
- test/scripts/v1alpha3/run-suggestion-random.sh
- test/suggestion/v1alpha3/test_chocolate_service.py.failed
- test/suggestion/v1alpha3/test_hyperopt_service.py
- test/suggestion/v1alpha3/test_skopt_service.py
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/794)
> feat: Rename algorithms

- manifests/v1alpha3/katib-controller/trialTemplateConfigmap.yaml
Current default doesn't emit any metrics. Because of this, experiment won't get succeeded if default trial template is used.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/801)
> Using example as the default trial 

- pkg/apis/controller/experiments/v1alpha3/experiment_types.go
- pkg/apis/controller/experiments/v1alpha3/util.go
- pkg/controller.v1alpha3/experiment/experiment_controller_test.go
As we do not have db in the main workflow, we do not need RetainHistoricalData anymore.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/806)
> Remove unused field from Experiment Spec

- test/scripts/v1alpha3/run-suggestion-tpe.sh
- test/workflows/components/workflows-v1alpha3.libsonnet
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/809)
> feat: Add tpe e2e test case

- pkg/controller.v1alpha3/suggestion/composer/composer.go
- pkg/controller.v1alpha3/suggestion/suggestion_controller_test.go
- pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1alpha3/util/labels.go
- pkg/controller.v1alpha3/util/suggestion.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/814)
> Rename algorithm deployment and service

- manifests/v1alpha3/katib-controller/crd-suggestion.yaml
- pkg/apis/controller/suggestions/v1alpha3/suggestion_types.go
- pkg/controller.v1alpha3/suggestion/suggestionclient/fake/fake.go
- pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
Added a new field 'SuggestionCount' which provides number of suggestions returned.  The printer columns are enhanced for better debugging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/817)
> Adding additional printer columns for better debugging

- pkg/webhook/v1alpha3/pod/inject_webhook.go
Fixes: #810
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/819)
> Fix stdout of worker container show nothing

- cmd/ui/v1alpha3/main.go
- pkg/ui/v1alpha3/frontend/package.json
- pkg/ui/v1alpha3/frontend/scripts/start.js
- pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Parameters.jsx
- pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/821)
> feat: Support step when using grid in UI

- pkg/controller.v1alpha3/suggestion/suggestion_controller.go
- pkg/controller.v1alpha3/suggestion/suggestion_controller_status.go
Update Status conditions during reconcile error because status conditions might be updated. Rest all status fields should be ignored
Fixes: #804 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/831)
> Update status conditions during reconcile error

- pkg/ui/v1alpha3/backend.go
- pkg/ui/v1alpha3/frontend/src/actions/templateActions.js
- pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Trial.jsx
- pkg/ui/v1alpha3/frontend/src/components/Templates/Trial.jsx
- pkg/ui/v1alpha3/frontend/src/sagas/index.js
- pkg/util/v1alpha3/katibclient/katib_client.go
Add a namespace field for the template.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/827)
> feat: support namespace for trial template

- pkg/controller.v1alpha3/suggestion/composer/composer.go
Ref https://srcco.de/posts/kubernetes-liveness-probes-are-dangerous.html
We should not use the same specification for readiness and liveness
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/833)
> fix: Update liveness probe to avoid problems

- examples/v1alpha3/pytorchjob-example.yaml
- test/e2e/v1alpha3/run-e2e-experiment.go
- test/scripts/v1alpha3/check-katib-ready.sh
- test/scripts/v1alpha3/run-pytorchjob.sh
- test/scripts/v1alpha3/run-tfjob.sh
- test/workflows/components/workflows-v1alpha3.libsonnet
TFJob and PytorchJob examples are added to e2e tests
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/820)
> Add tfjob and pytorch examples to e2e

- cmd/ui/v1alpha3/main.go
- pkg/ui/v1alpha3/backend.go
- pkg/ui/v1alpha3/frontend/src/actions/generalActions.js
- pkg/ui/v1alpha3/frontend/src/actions/hpCreateActions.js
- pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
- pkg/ui/v1alpha3/frontend/src/components/App.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Create/HPParameters.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Create/Params/Trial.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobList.jsx
- pkg/ui/v1alpha3/frontend/src/components/Menu/DeleteDialog.jsx
- pkg/ui/v1alpha3/frontend/src/reducers/general.js
- pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
- pkg/ui/v1alpha3/frontend/src/sagas/index.js
- pkg/ui/v1alpha3/nas.go
- pkg/ui/v1alpha3/types.go
- pkg/ui/v1alpha3/util.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/835)
> feat: Show all experiments in monitor

- pkg/controller.v1alpha3/trial/trial_controller.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
Close #845 
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/847)
> fix: Reorder to skip observation collection

- pkg/apis/controller/experiments/v1alpha3/util.go
- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1alpha3/experiment/util/status_util.go
- test/e2e/v1alpha3/run-e2e-experiment.go
- test/scripts/v1alpha3/check-katib-ready.sh
Experiment reconcile is set to complete only after running trials are complete
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/861)
> Finish reconcile only after running trials are complete 

- cmd/ui/v1alpha3/main.go
- pkg/ui/v1alpha3/frontend/package.json
- pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
- pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
- pkg/ui/v1alpha3/frontend/src/sagas/index.js
- pkg/ui/v1alpha3/hp.go
Not sure if we want it. Richard complains that we do not show experiment info in UI, and I am not good at data-visualization. Thus use react-json-view to visualize json directly.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/853)
> feat: Show experiment status in json

- manifests/v1alpha3/katib-controller/crd-trial.yaml
- pkg/apis/controller/trials/v1alpha3/util.go
- pkg/controller.v1alpha3/trial/trial_controller.go
- pkg/controller.v1alpha3/trial/trial_controller_consts.go
- pkg/controller.v1alpha3/trial/trial_controller_test.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
When job has succeeded without any available metrics, add a warning event notifying that metrics are not available. This will be helpful in debugging
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/864)
> Adding metric unavailability to events

- manifests/v1alpha3/db/deployment.yaml
Fixes https://github.com/kubeflow/katib/issues/334
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/871)
> feat: Add liveness probe for DB

- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1alpha3/experiment/experiment_util.go
- pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
- pkg/controller.v1alpha3/experiment/util/status_util.go
- pkg/controller.v1alpha3/trial/prometheus_metrics.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/870)
> Add prometheus metrics for experiment and trial

- pkg/common/v1alpha3/common.go
- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/trial/trial_controller.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
- pkg/job/v1alpha3/consts.go
- pkg/job/v1alpha3/job/job.go
- pkg/job/v1alpha3/kubeflow/kubeflow.go
- pkg/job/v1alpha3/provider.go
- pkg/webhook/v1alpha3/experiment/validator/validator.go
- pkg/webhook/v1alpha3/pod/const.go
- pkg/webhook/v1alpha3/pod/inject_webhook.go
- pkg/webhook/v1alpha3/pod/utils.go
This PR introduces a new Interface Provider, to make it easy to add new kinds.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/865)
> feat: Refactor to make it easy to extend new kinds

- pkg/controller.v1alpha3/trial/trial_controller.go
- pkg/controller.v1alpha3/trial/trial_controller_consts.go
When the reconcile has errors, we cannot get it from trial event. It is hard to debug. Thus I suggest sending an Event to trial if the reconcile is failed. It will not have the performance issue since the events are only kept for 1 hour by default.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/879)
> feat: Add event when the reconcile is failed

- cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
- pkg/metricscollector/v1alpha3/tfevent-metricscollector/tfevent_loader.py
Fixes #877 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/881)
> fix: Use as instead of , to support python 3 in tfevent metrics collector

- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/883)
> fix: Use 64 instead of 32 since we are using float64

- pkg/db/v1alpha3/common/const.go
- pkg/db/v1alpha3/mysql/mysql.go
In kubeflow cluster, there is a service named "mysql" from pipeline. so in each kubeflow POD, there is will ENV for mysql service like below, which will make `getDbName()` return in katib mysql DB invalid (owning to env `MYSQL_PORT`)
```
MYSQL_PORT_3306_TCP_ADDR=10.0.251.111
MYSQL_PORT_3306_TCP_PORT=3306
MYSQL_SERVICE_HOST=10.0.251.111
MYSQL_PORT_3306_TCP_PROTO=tcp
MYSQL_HOST=katib-db.kubeflow
MYSQL_PORT=tcp://10.0.251.111:3306
MYSQL_SERVICE_PORT=3306
MYSQL_PORT_3306_TCP=tcp://10.0.251.111:3306
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/900)
> Fix katib-manager crash in kubeflow cluster

- cmd/metricscollector/v1alpha3/file-metricscollector/main.go
- cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
- pkg/metricscollector/v1alpha3/common/const.go
- pkg/metricscollector/v1alpha3/common/pns.go
- pkg/metricscollector/v1alpha3/common/pns.py
- pkg/webhook/v1alpha3/pod/inject_webhook.go
Fixes: #896
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/901)
> Support restarting training job

- cmd/manager/v1alpha3/Dockerfile
- cmd/suggestion/chocolate/v1alpha3/Dockerfile
- cmd/suggestion/hyperband/v1alpha3/Dockerfile
- cmd/suggestion/hyperopt/v1alpha3/Dockerfile
- cmd/suggestion/nasrl/v1alpha3/Dockerfile
- cmd/suggestion/skopt/v1alpha3/Dockerfile
Fixes #890 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/893)
> support ppc64le

- cmd/katib-controller/v1alpha2/Dockerfile
- cmd/katib-controller/v1alpha3/Dockerfile
- cmd/manager-rest/v1alpha2/Dockerfile
- cmd/manager/v1alpha2/Dockerfile
- cmd/manager/v1alpha3/Dockerfile
- cmd/metricscollector/v1alpha2/Dockerfile
- cmd/metricscollector/v1alpha3/file-metricscollector/Dockerfile
- cmd/metricscollector/v1alpha3/tfevent-metricscollector/Dockerfile.aarch64
- cmd/suggestion/bayesianoptimization/v1alpha2/Dockerfile
- cmd/suggestion/chocolate/v1alpha3/Dockerfile
- cmd/suggestion/grid/v1alpha2/Dockerfile
- cmd/suggestion/hyperband/v1alpha2/Dockerfile
- cmd/suggestion/hyperband/v1alpha3/Dockerfile
- cmd/suggestion/hyperopt/v1alpha3/Dockerfile
- cmd/suggestion/nasrl/v1alpha2/Dockerfile.aarch64
- cmd/suggestion/nasrl/v1alpha3/Dockerfile
- cmd/suggestion/nasrl/v1alpha3/Dockerfile.aarch64
- cmd/suggestion/random/v1alpha2/Dockerfile
- cmd/suggestion/skopt/v1alpha3/Dockerfile
- cmd/tfevent-metricscollector/v1alpha2/Dockerfile.aarch64
- cmd/ui/v1alpha2/Dockerfile
- cmd/ui/v1alpha3/Dockerfile
- scripts/v1alpha2/build.sh
- scripts/v1alpha3/build.sh
- Changed Dockerfiles and build scripts to support images on arm64, tested on both x86_64 machine and arm64 machine.
- Followed by discussions with @gaocegege in #779 ([comment](https://github.com/kubeflow/katib/pull/779#discussion_r337413401)), fixed problems of only have x86_64 version binary of grpc_health_probe in original Dockerfiles.
Change-Id: I5ddee7e8fbe96b8e0a025e3f182b4a5192c45597
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/897)
> Enable arm64 architecture support for katib images and fix grpc health probe multiarch error.

- examples/v1alpha3/file-metrics-collector/mnist.py
- examples/v1alpha3/file-metricscollector-example.yaml
- pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
for now, in one line, only $metricsName=$value (without blank) can be parsed.
By this PR, blank can be tolerant before and after "="; Also in the same line, multiple metrics couple can be parsed
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/925)
> Support multiple metric logs in one line

- pkg/controller.v1alpha3/suggestion/composer/composer.go
Now the resource limitation is hard-coded. In the future, it should be configured in katib-config.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/932)
> feat: Add limit for suggestion pod

- scripts/v1alpha3/deploy.sh
- scripts/v1alpha3/undeploy.sh
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/935)
> Remove katib webhook when undeploy

- README.md
- cmd/metricscollector/v1alpha3/file-metricscollector/main.go
- cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
- docs/user-guide.md
- examples/v1alpha3/file-metrics-collector/mnist.py
- examples/v1alpha3/file-metricscollector-example.yaml
- pkg/metricscollector/v1alpha3/common/const.go
- pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
- pkg/webhook/v1alpha3/experiment/validator/validator.go
- pkg/webhook/v1alpha3/pod/inject_webhook.go
Fixes #939
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/947)
> Implement metrics custom filters

- pkg/ui/v1alpha3/frontend/src/components/NAS/Create/Params/Trial.jsx
- pkg/ui/v1alpha3/frontend/src/components/Templates/Trial.jsx
- pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
In this PR:
1. Fixed empty page while clicking on Trial Manifests in the Menu
2. Fetch Trial templates when opening submit by parameters in NAS page.
I did it in v1alpha3 version, should I make changes in v1alpha2 also @johnugeorge @gaocegege ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/938)
> Fix: Empty Trial templates in Katib UI

- manifests/v1alpha2/db/deployment.yaml
- manifests/v1alpha2/manager-rest/deployment.yaml
- manifests/v1alpha2/manager/deployment.yaml
- manifests/v1alpha2/suggestion/bayesianoptimization/deployment.yaml
- manifests/v1alpha2/suggestion/grid/deployment.yaml
- manifests/v1alpha2/suggestion/hyperband/deployment.yaml
- manifests/v1alpha2/suggestion/nasrl/deployment.yaml
- manifests/v1alpha2/suggestion/random/deployment.yaml
- manifests/v1alpha2/ui/deployment.yaml
- manifests/v1alpha3/db/deployment.yaml
- manifests/v1alpha3/manager/deployment.yaml
- manifests/v1alpha3/ui/deployment.yaml
Signed-off-by: yeya24 <yb532204897@gmail.com>
Since extensions/v1beta1 is deprecated since k8s 1.16, so migrating to apps/v1
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/937)
> update deployment api version

- pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
- pkg/controller.v1alpha3/trial/prometheus_metrics.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
See https://github.com/kubeflow/tf-operator/pull/1055,  add _total suffix.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/942)
> rename counter metrics

- examples/v1alpha3/bayesianoptimization-example.yaml
- examples/v1alpha3/custom-metricscollector-example.yaml
- examples/v1alpha3/file-metricscollector-example.yaml
- examples/v1alpha3/grid-example.yaml
- examples/v1alpha3/hyperband-example.yaml
- examples/v1alpha3/random-example.yaml
- examples/v1alpha3/tpe-example.yaml
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/949)
> Use kubeflowkatib repo as image repo of example

- pkg/controller.v1alpha3/trial/trial_controller.go
- pkg/controller.v1alpha3/trial/trial_controller_consts.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
- pkg/job/v1alpha3/job/job.go
- pkg/job/v1alpha3/kubeflow/kubeflow.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/894)
> feat: Support running

- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1alpha3/experiment/experiment_controller_test.go
- pkg/controller.v1alpha3/experiment/experiment_util.go
- pkg/controller.v1alpha3/experiment/util/prometheus_metrics.go
- pkg/controller.v1alpha3/experiment/util/status_util.go
Signed-off-by: yeya24 <yb532204897@gmail.com>
1. Add a gauge metric `katib_experiments_current` to track the current experiments in the cluster and their status.
2. Add a namespace label in previous counter metrics.
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/954)
> Add a gauge metric for current experiments

- pkg/apis/controller/experiments/v1alpha3/util.go
- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1alpha3/experiment/util/status_util.go
- pkg/mock/v1alpha3/util/katibclient/katibclient.go
- pkg/util/v1alpha3/katibclient/katib_client.go
- test/e2e/v1alpha3/resume-e2e-experiment.go
- test/scripts/v1alpha3/check-katib-ready.sh
- test/scripts/v1alpha3/run-suggestion-random.sh
Fixes: #891 
Resuming experiment feature is added.  If user wants to try the same experiment with more number of trials, max trials can be reconfigured to restart the experiment from the last checkpoint. 
Experiment is restarted only when experiment is in succeeded state with max trials reached previously.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/952)
> Resume experiment with extra trials from last checkpoint

- pkg/controller.v1alpha3/experiment/util/status_util.go
- pkg/webhook/v1alpha3/experiment/validation_webhook.go
- pkg/webhook/v1alpha3/experiment/validator/validator.go
- pkg/webhook/v1alpha3/experiment/validator/validator_test.go
Fixes #956 
Fixes #768
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/957)
> Validate experiment

- cmd/ui/v1alpha3/Dockerfile
- manifests/v1alpha3/ui/deployment.yaml
- manifests/v1alpha3/ui/service.yaml
This PR changes the port used by `katib-ui` from `80` (needs root privileges) to `8080` so that we can run `katib-ui` on OpenShift with default security context.
As `katib-ui` already supports port configuration it is really just about changing manifests, but I have also changed the `USER` in `Dockerfile` as running as unprivileged user is generally considered a good practice in containers.
Fixes #966 
There is not a  change of the image, but there is a …
> Use port 8080 for Katib UI

- pkg/webhook/v1alpha3/pod/inject_webhook.go
- pkg/webhook/v1alpha3/pod/utils.go
This PR fixes a potential typo in a function name (`getKabitJob` vs. `getKatibJob`) - unless it was intended for some reason.
Might not be a high priority, but I noticed it when I tried to search for `getKatibJob` and got 0 results back.
**Which issue(s) this PR fixes** 
Not really an issue, more a nit-picker personality trait
No image change
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/965)
> Fix typo in getKabitJob function name

- manifests/v1alpha3/db/deployment.yaml
As described in the issue, the `readinessProbe` will fail when the container is not running as `root`. This PR explicitly uses `-u root` in `readinessProbe`.
Fixes #961 
No image changes
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/962)
> User root user explicitely for DB readinessProbe

- cmd/katib-controller/v1alpha3/Dockerfile
- cmd/katib-controller/v1alpha3/main.go
- manifests/v1alpha3/katib-controller/katib-controller.yaml
- manifests/v1alpha3/katib-controller/service.yaml
- pkg/webhook/v1alpha3/webhook.go
This PR allows Katib Controller to run as a non-root user. This is important from security point of view and especially to enable Katib on enterprise distributions of Kubernetes like OpenShift.
This PR adds a parameter `--webhook-port` to allow configuring port > 1024 for admission webhooks and also changes the default port (`443`) to `8443`.
It also changes the `USER` in `Dockerfile` as it is not necessary to run as root with this change even on the vanilla Kubernetes.
Fixes #959
1. Please confirm that if this PR changes any image versions, then that's the …
> Use port higher than 1024 to be able to run as a non-root user

- cmd/katib-controller/v1alpha3/main.go
- pkg/controller.v1alpha3/consts/const.go
- pkg/webhook/v1alpha3/webhook.go
Fixes #975 
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/980)
> feat(config): Add a new config for webhook

- pkg/apis/controller/experiments/v1alpha3/experiment_types.go
- pkg/controller.v1alpha3/experiment/util/status_util.go
This PR added a new field in v1alpha3 Exepriment status, which stores the best trial name.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/986)
> feat(experiment_status): Add trial name

- pkg/db/v1alpha3/common/const.go
- pkg/db/v1alpha3/mysql/mysql.go
Fixes #984 
After this PR, 
* can dynamically configure the user name of mysql databases via environment variables
* can use external mysql instead of the mysql in pods
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/985)
> Get dbUser from Env or default('root')

- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/suggestion/composer/composer.go
- pkg/util/v1alpha3/katibconfig/config.go
The aim of this PR is appending the setting of disk(EphemeralStorage) into configuration of suggestion service.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/989)
> add disk setting into suggestionConfiguration

- pkg/webhook/v1alpha3/pod/inject_webhook.go
The issue is that the injected container does not have `securityContext` initialized (as that is done by some earlier mutating webhook). The simplest solution for now is to simply copy the `securityContext` from the container that already exists (and is fully mutated) in the pod.
Fixes #963
No image changes
```release-note
NONE
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Initialize securityContext in injected metrics container

- cmd/katib-controller/v1alpha3/main.go
- pkg/controller.v1alpha3/consts/const.go
- pkg/webhook/v1alpha3/pod/inject_webhook.go
- pkg/webhook/v1alpha3/webhook.go
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/994)
> feat: Add a flag to control the logic about sc

- pkg/webhook/v1alpha3/webhook.go
When katib-controller is unavailable, the mutation webhook will fail all the pods in the namespace. I think we should avoid it.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/996)
> fix: Ignore the failure

- cmd/katib-controller/v1alpha3/main.go
- manifests/v1alpha3/katib-controller/katib-config.yaml
- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/experiment/manifest/generator.go
- pkg/util/v1alpha3/katibconfig/config.go
- pkg/webhook/v1alpha3/pod/inject_webhook.go
- pkg/webhook/v1alpha3/webhook.go
Supports resource limits in sidecar.
/cc @sperlingxx 
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/991)
> feat: Support resource in sidecar

- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/experiment/suggestion/suggestion.go
- pkg/controller.v1alpha3/suggestion/composer/composer.go
- pkg/controller.v1alpha3/util/labels.go
Suggestions are owned by experiments. Thus inheriting labels and annotations is helpful for debugging purposes.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/998)
> fix: Inherit labels and annotations from experiment

- pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/AlgorithmSettings.py
- pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/Controller.py
- pkg/suggestion/v1alpha3/NAS_Reinforcement_Learning/Trainer.py
- pkg/suggestion/v1alpha3/nasrl_service.py
I fixed bug in NAS RL Suggestion. 
`experiment.num_trials` should be updated every `GetSuggestions` call, since `request_number` value can be different during one experiment.
Also, I change deprecated TF functions to decrease warning in Suggestion logs and I added `logger` instead of `print` in AlgorithmSettings.
/cc @johnugeorge @gaocegege @hougangliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1009)
> Fix number of Trials problem in NAS RL Suggestion

- examples/v1alpha3/nasjob-example-RL-cpu.yaml
- examples/v1alpha3/nasjob-example-RL-gpu.yaml
- test/scripts/v1alpha3/run-suggestion-nasrl.sh
I added e2e test for NAS RL Suggestion.
It uses simple 1 layer CNN architecture with 1 epoch and CPU training.
That should not take much time in CI.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1011)
> E2E Test for NAS RL Suggestion

- manifests/v1alpha3/katib-controller/katib-config.yaml
- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/suggestion/composer/composer.go
- pkg/util/v1alpha3/katibconfig/config.go
- pkg/webhook/v1alpha3/pod/inject_webhook.go
After this PR we can change `imagePullPolicy` value for MetricsCollector and Suggestion in Katib Config.
/assign @johnugeorge @gaocegege @hougangliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1013)
> [Feature] Enable imagePullPolicy in Katib Config

- .gitignore
- pkg/webhook/v1alpha3/pod/inject_webhook.go
- pkg/webhook/v1alpha3/pod/inject_webhook_test.go
We should not inject sh -c if the command already contains it.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1010)
> feat: Do not inject sh -c when it exists

- pkg/controller.v1alpha3/experiment/util/status_util.go
When the last trial is failed, we did not set the condition to failed before.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1015)
> fix: First check failed condition

- cmd/katib-controller/v1alpha3/main.go
- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/suggestion/composer/composer.go
It is to add a flag to decide if we should enable the GRPC probe.
Fixes #
```release-note
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1020)
> feat: Add a flag to support removing GRPC probe at runtime

- pkg/suggestion/v1alpha3/internal/trial.py
Some metrics will be ignored if it is none.
```
ERROR:grpc._server:Exception calling application: 'str' object has no attribute 'value'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 434, in _call_behavior
response_or_iterator = behavior(argument, context)
File "/usr/src/app/github.com/kubeflow/katib/pkg/suggestion/v1alpha3/hyperopt_service.py", line 27, in GetSuggestions
search_space, trials, request.request_number)
File "/usr/src/app/github.com/kubeflow/katib/pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py", line 95, in getSuggestions
objective_for_hyperopt = float(trial.target_metric.value)
AttributeError: 'str' object has no attribute …
```
> fix: Ignore trials without metrics

- pkg/ui/v1alpha3/frontend/package.json
- pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/ExperimentInfoDialog.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobTable.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx
- pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
I added button to open dialog with current experiment JSON view instead of showing experiment in the bottom page.
Let me know, if this design is ok.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1031)
> UI: Experiment view in the Dialog

- docs/community/adopters.md
Adding [Babylon Health](https://www.babylonhealth.com/) as an adopter of Katib.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1046)
> Adding Babylon Health as adopter

- pkg/ui/v1alpha3/hp.go
This PR fixes problem when different metrics have the same timestamp.
We should show all data from Observation Logs table in the Plot.
/assign @johnugeorge 
/cc @hougangliu @gaocegege
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1047)
> UI: Fix problem with equal time in different Trial metrics

- pkg/util/v1alpha3/katibclient/katib_client.go
This PR adds error propagation for K8s client creation in `katib_client.NewClient()`
**Which issue(s) this PR fixes**
If the `Client` creation fails for some reason - the error is silently ignored and Katib UI backend starts normally. However, when a new experiment is submitted from the UI, it results in nil pointer dereference panic because the `Client` has not been initialized.
This PR doesn't change any image versions
```release-note
Fixed nil pointer dereference in `KatibClient`
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1053)
> Adding error propagation for K8s client creation in KatibClient

- pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
Fixes: https://github.com/kubeflow/katib/issues/1052.
/cc @richardsliu @hougangliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1055)
> Change tell method for BO Suggestion

- cmd/db-manager/v1alpha3/Dockerfile
In my previous PR #897 for the aarch64 platform support for katib Dockerfiles, the version of db-manager was v1alpha2, which has been deprecated now. 
This PR adds the missing GRPC health probe binary to v1alpha3 aarch64 images.
Signed-off-by: Henry Wang <<henry.wang@arm.com>>
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1059)
> Add missing GRPC health probe for arm64 to db-manager

- pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
- pkg/suggestion/v1alpha3/skopt_service.py
Fixes: https://github.com/kubeflow/katib/issues/1039.
In this PR I added `is_first_run` flag.
We must create `Optimizer` instance using `search_space` only for the first `GetSuggestions` call.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1057)
> Create Optimizer in BO Suggestion only for the first run

- pkg/mock/v1alpha3/util/katibclient/katibclient.go
- pkg/ui/v1alpha3/frontend/src/actions/hpMonitorActions.js
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobInfo.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/HPJobTable.jsx
- pkg/ui/v1alpha3/frontend/src/components/HP/Monitor/TrialInfoDialog.jsx
- pkg/ui/v1alpha3/frontend/src/reducers/hpMonitor.js
- pkg/ui/v1alpha3/frontend/src/sagas/index.js
- pkg/ui/v1alpha3/hp.go
- pkg/util/v1alpha3/katibclient/katib_client.go
If metrics have the same time, we should show metrics with best objective value in the Trial metrics information plot, instead of latest.
This PR fixes this problem.
Also, I added Trial name to the metrics plot.
/assign @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1068)
> UI: Show best metrics in the Trial metrics information plot

- README.md
- ROADMAP.md
- docs/community/adopters.md
- docs/developer-guide.md
- docs/new-algorithm-service.md
- docs/new-trial-kind.md
- docs/proposals/metrics-collector.md
- docs/proposals/suggestion.md
- docs/quick-start.md
- docs/workflow-design.md
This PR updates Katib docs:
1. Remove all references to Vizier
2. Change ROADMAP 2020. I tried to delete outdated issues and I added few in-progress tasks, but maybe we need to add or delete more. Please take a look on this.
3. Make Katib capitalised in all docs
4. Add links and missed algorithms in README
5. Add a step to create e2e test for the new Katib algorithm
6. Fix few broken links.
Please, take a look.
/assign @johnugeorge @gaocegege @hougangliu @richardsliu
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1066)
> Update Katib docs

- cmd/suggestion/hyperopt/v1alpha3/requirements.txt
- pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
- pkg/suggestion/v1alpha3/hyperopt_service.py
This PR fixes some problems in hyperopt Suggestion.
1. I tested `tpe` Algorithm on large-amount of Trials. After 20 Succeeded Trial I always got this error:
```
INFO:hyperopt.tpe:tpe_transform took 0.001436 seconds
INFO:hyperopt.tpe:TPE using 20/20 trials with best loss -0.955490
ERROR:grpc._server:Exception calling application: '>' not supported between instances of 'int' and 'str'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 434, in _call_behavior
response_or_iterator = behavior(argument, context)
File "/usr/src/app/github.com/kubeflow/katib/pkg/suggestion/v1alpha3/hyperopt_service.py", line 27, in GetSuggestions
search_space, trials, request.request_number)
File "/usr/src/app/github.com/kubeflow/katib/pkg/suggestion/v1alpha3/hype …
```
> Fix TPE Suggestion

- pkg/ui/v1alpha3/frontend/src/reducers/hpCreate.js
- pkg/ui/v1alpha3/frontend/src/reducers/nasCreate.js
I updated Katib supported algorithms in the UI and I changed default value for `additionalMetricNames`, since we are using `Train-accuracy` metric in the main Katib training container.
/assign @johnugeorge
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1070)
> UI: Update supported algorithms

- cmd/suggestion/chocolate/v1alpha3/requirements.txt
Fixes: https://github.com/kubeflow/katib/issues/1093.
For some reason, `git+https://github.com/AIworx-Labs/chocolate@master` command doesn't add `ghalton` package.
I tested quasirandom with this search space: https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/grid-example.yaml. Experiment was succeeded.
/assign @gaocegege 
/cc @terrykong
> Add ghalton package to Chocolate Suggestion

- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/suggestion/composer/composer.go
- pkg/util/v1alpha3/katibconfig/config.go
Fixes: https://github.com/kubeflow/katib/issues/1079.
I added functionality to add Service Account Name using Katib config.
We can add Validation part, for example here: https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1alpha3/experiment/validation_webhook.go#L88, to Validate Katib config.
For example, users can't submit Experiment with Service Account, if they don't have appropriate Service Account in Experiment Namespace. I don't know if it useful or not for us.
What do you think @gaocegege @johnugeorge @hougangliu ?
/cc @nrchakradhar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kubeflow/katib/1092)
> Enable to add Service Account Name in Katib config

- pkg/suggestion/v1alpha3/base_health_service.py
- pkg/suggestion/v1alpha3/hyperband_service.py
- pkg/suggestion/v1alpha3/hyperopt_service.py
- pkg/suggestion/v1alpha3/nasrl_service.py
- pkg/suggestion/v1alpha3/parameter.py
* Remove unused imports.
* Remove redundant parentheses.
* Use new-style classes because suggestion modules are run on Python 3.6 (See Dockerfiles in [cmd/suggestion](https://github.com/kubeflow/katib/tree/master/cmd/suggestion).
* Follow pep8.
None.
None
```release-note
NONE
```
> Refactor python files of suggestion services

- pkg/common/v1alpha3/katib_manager_util.go
- pkg/controller.v1alpha3/consts/const.go
- pkg/ui/v1alpha3/backend.go
Fixes this comment: https://github.com/kubeflow/katib/issues/981#issuecomment-600170773.
If users want to use their own DB Manager, they must specify these env variables in **Katib controller** and **Katib UI** manifests:
```
KATIB_DB_MANAGER_SERVICE_NAMESPACE = <db manager namespace>
KATIB_DB_MANAGER_SERVICE_IP = <db manager ip (service name)>
KATIB_DB_MANAGER_SERVICE_PORT = <db manager port>
```
Also, if user specifies `KATIB_DB_MANAGER_SERVICE_NAMESPACE=''`, we will use `KATIB_DB_MANAGER_SERVICE_IP:KATIB_DB_MANAGER_SERVICE_PORT` for DB manager address .
This might be useful, if user needs to send metrics to DataBase which is not deployed in Kubernetes.
I tried to deploy `katib-db-manager` in the different namespace than `katib-controller`. After set correct env, metrics got collected. …
> Fix custom Katib DB Manager env variables

- pkg/suggestion/v1alpha3/internal/search_space.py
- pkg/suggestion/v1alpha3/internal/trial.py
* Avoid shadows of built-in methods (type, min, max, list).
* Fix comparison operator.
None
None.
```release-note
NONE
```
> Refactor suggestion-internal-modules

- pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
- pkg/suggestion/v1alpha3/chocolate_service.py
- pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
- pkg/suggestion/v1alpha3/hyperopt_service.py
- pkg/suggestion/v1alpha3/internal/search_space.py
- pkg/suggestion/v1alpha3/internal/trial.py
- pkg/suggestion/v1alpha3/skopt/base_skopt_service.py
- pkg/suggestion/v1alpha3/skopt_service.py
See the following quotes from the Python official documentation.
> The name is potentially a period-separated hierarchical value, like foo.bar.baz (though it could also be just plain foo, for example). Loggers that are further down in the hierarchical list are children of loggers higher up in the list. For example, given a logger with a name of foo, loggers with names of foo.bar, foo.bar.baz, and foo.bam are all descendants of foo. The logger name hierarchy is analogous to the Python package hierarchy, and identical to it if you organise your loggers on a per-module basis using the recommended construction logging.getLogger(__name__).
https://docs.python.org/3/library/logging.html
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue …
> Fix logger namespace

- cmd/suggestion/hyperopt/v1alpha3/main.py
- cmd/suggestion/nasrl/v1alpha3/main.py
- cmd/suggestion/skopt/v1alpha3/main.py
* Remove `__init__.py` from `cmd/suggestion/**/__init__.py` because that are not python import modules, just providing a command-line entrypoint.
* Follow pep8.
None.
None.
```release-note
NONE
```
> Refactor python files in cmd/suggestion

- docs/developer-guide.md
- pkg/ui/v1alpha3/README.md
- pkg/ui/v1alpha3/frontend/src/components/Menu/Menu.jsx
- pkg/ui/v1alpha3/frontend/src/components/Menu/Snack.jsx
This PR:
1. Fixes: https://github.com/kubeflow/katib/issues/636. Close menu after click.
2. I deleted "About" page, since it is not needed.
3. Information Snack Bar closes after 6 seconds. It is not necessary to click on close icon.
4. I added Material UI link to the Katib UI README and link from developer-guide.
/cc @richardsliu
> UI: Close menu on click

- test/scripts/v1alpha3/run-custom-metricscollector.sh
- test/scripts/v1alpha3/run-file-metricscollector.sh
- test/scripts/v1alpha3/run-pytorchjob.sh
- test/scripts/v1alpha3/run-suggestion-bayesian.sh
- test/scripts/v1alpha3/run-suggestion-grid.sh
- test/scripts/v1alpha3/run-suggestion-hyperband.sh
- test/scripts/v1alpha3/run-suggestion-nasrl.sh
- test/scripts/v1alpha3/run-suggestion-random.sh
- test/scripts/v1alpha3/run-suggestion-tpe.sh
- test/scripts/v1alpha3/run-tfjob.sh
I made few changes in e2e test. I hope it will fix running problems.
1. Deleted part of creating ${GO_DIR}. According to this PR: https://github.com/kubeflow/katib/pull/802, we deleted from some e2e test this part. I think it should fix problem with `cp: cannot create symbolic link` error.
2. Deleted `NAMESPACE` and `REGISTRY` env variable, since it is not needed.
3. Deleted part of describing pods and deploy in default namespace and other describe in some e2e test.
4. I left only `describe` appropriate Experiment in each e2e test. I think it is more informative.
> Fix Katib e2e tests

- pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
- pkg/suggestion/v1alpha3/hyperopt/base_hyperopt_service.py
- pkg/suggestion/v1alpha3/internal/search_space.py
Fixes: https://github.com/kubeflow/katib/issues/1119.
I added parsing step in Internal Search Space function.
Default value for the int parameter step is 1.
/assign @gaocegege 
/cc @StefanoFioravanzo
> Support step for int parameter in Chocolate and Hyperopt Suggestion

- pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
- pkg/suggestion/v1alpha3/chocolate_service.py
I changed Chocolate Suggestion to be consistent with other Suggestions (Hyperopt, skopt).
1. Chocolate suggestion should analyse search space only for the first run.
2. I changed mechanism of saving information to sqlite3 DB. We don't need to override all Trial data every GetSuggestions call. We just update current DB data with the new Trial loss and Trial name for appropriate `_chocolate_id`. For this, I use list of recorded dictionaries `self.created_trials` variable. I update this list when receive new information about Trials.
3. Because of that, Chocolate sampler generates correct `_chocolate_id` for each new assignment and Chocolate algorithms should work correct. User can check data in sqlite3 DB.
4. Added few logs steps.
5. Removed warnings from SQLAlchemy about different threads …
> Optimize Chocolate Suggestion

- ROADMAP.md
> feat: Add 2020 roadmap

- pkg/suggestion/v1alpha3/hyperopt_service.py
I deployed katib (rev ab3dab07) to my kubernetes cluster, then applied [this experiment](https://github.com/c-bata/katib-goptuna-example/blob/master/experiment.yaml) which specifies `random` as an `algorithmName` attribute.
```
$ kubectl logs cmaes-example-random-7dd54668f8-ffgvs -n kubeflow
ERROR:grpc._server:Exception calling application: Method not implemented!
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/grpc/_server.py", line 434, in _call_behavior
response_or_iterator = behavior(argument, context)
File "/usr/src/app/github.com/kubeflow/katib/pkg/apis/manager/v1alpha3/python/api_pb2_grpc.py", line 135, in ValidateAlgorithmSettings
raise NotImplementedError('Method not implemented!')
NotImplementedError: Method …
```
> Fix NotImplementedError for TPE and Random suggestion.

- .travis.yml
- hack/verify-gofmt.sh
In the PR #1131, I added `gonum` as a dependency. Then CI fails at `go vet ./pkg/...` because it raises syntax error at the following line:
https://github.com/kubeflow/katib/blob/71a59ff49adf24d428b76ae6d94d599aa5759b6f/vendor/gonum.org/v1/gonum/lapack/gonum/lapack.go#L39
It seems that the above line uses the syntax added from Go 1.13. See [this commit](https://github.com/gonum/gonum/commit/32189f28b71ad0780d99b0dfd39523492dc72a71) for details.
```
$ GOROOT=/usr/local/go1.12 /usr/local/go1.12/bin/go vet ./pkg/...
vendor/gonum.org/v1/gonum/lapack/gonum/lapack.go:39:15: syntax error: unexpected p, expecting semicolon or newline or )
$
```
```
$ GOROOT=/usr/local/go1.13 /usr/local/go1.13/bin/go vet ./pkg/...
$
```
I checked Dockerfiles under `cmd/` …
> Bump up the Go version to 1.14.2 at Travis CI

- cmd/metricscollector/v1alpha3/file-metricscollector/main.go
- pkg/metricscollector/v1alpha3/file-metricscollector/file-metricscollector.go
Add some refactoring changes to `flie-metricscollector`.
None
None
```release-note
NONE
```
> Refactor file-metricscollector

- pkg/suggestion/v1alpha3/nas/enas/AlgorithmSettings.py
- pkg/suggestion/v1alpha3/nas/enas_service.py
I moved validate Algorithm Settings to appropriate function for Enas.
Currently, I left validation for Graph Config and Operations in Suggestion.
After implementing new NAS algorithms, we will figure out if we need to move it to Katib Controller Validator Webhook.
> ENAS Check Algorithm Settings in Validate Function

- examples/v1alpha3/grid-example.yaml
- pkg/suggestion/v1alpha3/chocolate/base_chocolate_service.py
Fixes: https://github.com/kubeflow/katib/issues/1124.
After this PR all Chocolate algorithms should support string values for Categorical parameters.
I insert index of the list to DB instead of list value.
> Support Categorical string values in Chocolate Suggestion

- pkg/suggestion/v1alpha3/nas/enas/AlgorithmSettings.py
- pkg/suggestion/v1alpha3/nas/enas/Controller.py
- pkg/suggestion/v1alpha3/nas/enas_service.py
After this PR user can specify None values for some algorithm settings defined in `enableNoneSettingsList`.
This might be useful for some experiments with ENAS.
> ENAS enable to add None values in algorithm settings

- examples/v1alpha3/cmaes-example.yaml
Add an example of Goptuna suggestion service.
Part of #1152
1. This experiment is almost the same with `tpe-example`. I just change the name and algorithm name.
1. Please note that Goptuna's CMA-ES does not support categorical search space. So `--optimizer` param is sampled by Goptuna independent sampler (default: random sampler).
```release-note
NONE
```
> Add an example of Goptuna suggestion service

- manifests/v1alpha3/katib-controller/katib-config.yaml
- prow_config.yaml
- test/scripts/v1alpha3/build-suggestion-goptuna.sh
- test/workflows/components/workflows-v1alpha3.libsonnet
Part of https://github.com/kubeflow/katib/issues/1152.
I added Goptuna suggestion build to CI and updated `katib-config` with the new image.
/assign @c-bata 
/cc @johnugeorge @gaocegege
> Build Goptuna Suggestion image in CI

- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1alpha3/experiment/experiment_controller_test.go
- pkg/controller.v1alpha3/experiment/suggestion/fake/fake.go
- pkg/controller.v1alpha3/experiment/suggestion/suggestion.go
- pkg/mock/v1alpha3/experiment/suggestion/suggestion.go
I removed `suggestionRequestsCount` from `UpdateSuggestion` function call, because we don't use it.
We update suggestion CR with new instance.
/cc @sperlingxx
> Remove Suggestion Request from Update Suggestion

- ROADMAP.md
I updated ROADMAP with support MXNet, XGBoost, MPI operator.
Also, I renamed Hyperparameter Tuning to Common, since this steps are related to HP and NAS.
/cc @animeshsingh
> Add support Kubeflow operators to ROADMAP

- pkg/suggestion/v1alpha3/hyperopt/base_service.py
- pkg/suggestion/v1alpha3/hyperopt/service.py
- test/suggestion/v1alpha3/test_hyperopt_service.py
Restructuring algorithm configuration related codes for hyperopt_service, which makes it easier to modify algorithm schema in future.
@andreyvelich @gaocegege @c-bata
> restructure algorithm configuration for hyperopt_service

- pkg/suggestion/v1alpha3/chocolate/base_service.py
- pkg/suggestion/v1alpha3/chocolate/service.py
Rename chocolate algorithm names for consistency.
To close https://github.com/kubeflow/katib/issues/1163.
Related discussions are https://github.com/kubeflow/website/pull/1907#discussion_r413510637 and https://github.com/kubeflow/katib/pull/1131#discussion_r407955790.
None
```release-note
Rename algorithm names of chocolate suggestion service.
Algorithm names that start with `chocolate-` are deprecated.
```
> Rename chocolate algorithm names for consistency

- examples/v1alpha3/nas/enas-cnn-cifar10/Dockerfile.gpu
- examples/v1alpha3/nas/enas-example-cpu.yaml
- examples/v1alpha3/nas/enas-example-gpu.yaml
Cuda version in Tensorflow 1.15 must be greater than 10.0.
Ref: https://www.tensorflow.org/install/gpu.
I fixed it in enas gpu training container.
Also, python version to run training container should be `python3`
> Fix Cuda version in training container for ENAS

- pkg/apis/controller/experiments/v1alpha3/constants.go
- pkg/apis/controller/experiments/v1alpha3/experiment_defaults.go
- pkg/apis/controller/experiments/v1alpha3/experiment_types.go
- pkg/apis/v1alpha3/openapi_generated.go
- pkg/apis/v1alpha3/swagger.json
- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1alpha3/experiment/experiment_util.go
- pkg/controller.v1alpha3/suggestion/suggestion_controller.go
- pkg/controller.v1alpha3/suggestion/suggestion_controller_util.go
- pkg/webhook/v1alpha3/experiment/validator/validator.go
- pkg/webhook/v1alpha3/experiment/validator/validator_test.go
- test/e2e/v1alpha3/resume-e2e-experiment.go
- test/e2e/v1alpha3/run-e2e-experiment.go
This PR responds to the #1061  issue.
I'd like to implement suggestion eviction at first. Then work on how to persist the status of suggestion #1062  (maybe through pv?). 
@andreyvelich @johnugeorge @richardsliu @hougangliu @gaocegege
> Delete Suggestion deployment after Experiment is finished

- pkg/apis/controller/common/v1alpha3/common_types.go
- pkg/controller.v1alpha3/experiment/util/status_util.go
- pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
- test/e2e/v1alpha3/resume-e2e-experiment.go
- test/e2e/v1alpha3/run-e2e-experiment.go
I added support for string values in `CurrentOptimalTrial.Observation.Metrics` for Experiment and `Observation.Metrics` for Trial. This will be useful if user wants to report some text information from Trial.
See comment: https://github.com/kubeflow/katib/pull/1175#issue-412394244.
> Support string metrics values in Controller

- test/scripts/v1alpha3/python-tests.sh
- test/suggestion/v1alpha3/test_chocolate_service.py
- test/suggestion/v1alpha3/test_darts_service.py
Part of https://github.com/kubeflow/katib/issues/1167.
I added unittest for Darts service and removed failed from chocolate unittest, it should work now without warning on same thread running.
In the future we can add e2e test for Darts, I think.
This can be done after we implement more parameters in `AlgorithmSettings` to control Darts running. Currently, running Darts on CPU is extremely long.
> Unittest for DARTS Suggestion

- cmd/suggestion/skopt/v1alpha3/requirements.txt
New version of Scikit learn: 0.23, doesn't work with scikit-optimize version: 0.5.2.
I changed Scikit learn version to 0.22 for BO Suggestion.
> Change scikit-learn version to 0.22.0 for BO Suggestion

- pkg/apis/controller/common/v1alpha3/common_types.go
- pkg/controller.v1alpha3/experiment/util/status_util.go
- pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1alpha3/trial/trial_controller_util.go
- test/e2e/v1alpha3/resume-e2e-experiment.go
- test/e2e/v1alpha3/run-e2e-experiment.go
Fixes: https://github.com/kubeflow/katib/issues/1186.
String metric values can break current Running Katib user's Experiments.
I reverted this commit from the upstream, we will add this commit after we switch to the new Katib version.
/assign @johnugeorge @gaocegege @sperlingxx
> Revert 1176 PR (Support string metric values)

- examples/v1alpha3/nas/darts-cnn-cifar10/model.py
- prow_config.yaml
I added support for one and two neural network layers in DARTS.
If Num Layers = 1, only Normal Cell is used.
If Num Layers = 2, First layer: Normal Cell, Second Layer: Reduction Cell.
That will be useful for e2e test in the future.
I have pushed to `docker.io/kubeflowkatib/darts-cnn-cifar10` new image.
> Support one and two NN layers in DARTS

- pkg/ui/v1alpha3/hp.go
We should cast metrics to float values before making comparison between values.
Comparing string values can be not right.
> UI: Fix comparison of metric values in Metrics Info Plot

- cmd/metricscollector/v1alpha3/tfevent-metricscollector/main.py
- pkg/metricscollector/v1alpha3/tfevent-metricscollector/tfevent_loader.py
Fixes: https://github.com/kubeflow/katib/issues/1188.
I changed split metrics from "," to ";".
See comment: https://github.com/kubeflow/katib/issues/1188#issuecomment-630320234.
Do we need to modify TF Job example (https://github.com/kubeflow/katib/blob/master/examples/v1alpha3/tfjob-example.yaml) with additional metric, for example: `cross_entropy_1`?
/cc @sadeel
> Fix additional metrics in TF Event metrics collector

- docs/new-algorithm-service.md
I added step to new algorithm service doc to modify `check-katib-ready.sh` script.
To run e2e test we should change registry to `gcr.io/kubeflow-ci`.
> Modify new algorithm service doc

- pkg/apis/controller/common/v1beta1/common_types.go
- pkg/controller.v1beta1/experiment/util/status_util.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1beta1/trial/trial_controller_util.go
- test/e2e/v1beta1/resume-e2e-experiment.go
- test/e2e/v1beta1/run-e2e-experiment.go
Fixes: https://github.com/kubeflow/katib/issues/1190.
This PR as a copy of https://github.com/kubeflow/katib/pull/1176 in v1beta1.
> Re: Support string metrics values in Controller

- examples/v1alpha3/README.md
- examples/v1beta1/README.md
I updated doc with DARTS training container image `docker.io/kubeflowkatib/darts-cnn-cifar10`. 
> Update doc for training container images with DARTS

- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/experiment/manifest/generator.go
- pkg/mock/v1beta1/experiment/manifest/generator.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
- test/e2e/v1beta1/invalid-experiment.yaml
Part of: https://github.com/kubeflow/katib/issues/1208.
I added Validation for the New Trial Template. 
I believe I covered all test cases.
The most tricky part is how to validate that user specifies fully correct Job, TFJob or PyTorch Job (That all APIs are correct).
We can't just convert `unstructured` to according Kubernetes structure (e.g `batchv1.Job{}`) and convert it back to `unstructured`. And then use `DeepEqual` to compare with original.
After transforming Trial template to Kubernetes Job, some parameters will be added by default. For example, `metadata.creationTimestamp` will be `nil`. So JSON structure of original and transformed job is different.
My idea is to use JSON patch. After converting `unstructured` to Kubernetes structure we can try to use JSON patch on this …
> New Trial Template validation

- pkg/controller.v1beta1/experiment/manifest/generator_test.go
I added more unit test cases for Generator.
Part of: https://github.com/kubeflow/katib/issues/1208.
> Add more test cases for Generator

- pkg/ui/v1beta1/frontend/src/reducers/hpMonitor.js
- pkg/ui/v1beta1/frontend/src/reducers/nasMonitor.js
After this PR, user can view directly all namespaces when clicking on monitor, like in Trial template.
There will be no empty blank element.
> UI: Show all namespaces in experiment list 

- manifests/v1beta1/katib-controller/trial-template-configmap.yaml
I fixed indentation for PyTorch Trial Template and renamed it to `trial-template-configmap.yaml` to be consistent with `kubeflow/manifests`.
> Fix Trial template config map in v1beta1

- pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
I fixed default values for `metricStrategies`.
1. For additional metrics we should extract metric name from `AdditionalMetricNames` array.
2. I think, for additional metrics we should follow the same way as for Objective. If values is not set, check what user set in Objective `type`.
3. We can omit `ObjectiveTypeUnknown` since we have `default` case.
/assign @sperlingxx 
> Fix default metrics strategies

- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
We should not validate Trial template resources, because users can set custom resources in k8s cluster using Device plugins.
For example:  [`nvidia.com/gpu`](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/nas/darts-example-gpu.yaml#L88),  [`xilinx/aws-vu9p-f1`](https://docs.inaccel.com/labs/kubeflow/#accelerated-xgboost-with-katib-hyperparameter-tuning).
I added ignoring these paths to patching.
> Not validate Trial template resources

- examples/v1beta1/nas/darts-example-gpu.yaml
There was a mistake in Trial parameter name for DARTS example.
/cc @johnugeorge @gaocegege
> Fix Trial parameter name for v1beta1 DARTS example

- pkg/apis/controller/common/v1beta1/common_types.go
- pkg/apis/v1beta1/openapi_generated.go
- pkg/apis/v1beta1/swagger.json
- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/experiment/util/status_util.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
- pkg/controller.v1beta1/trial/trial_controller_test.go
- pkg/controller.v1beta1/trial/trial_controller_util.go
- test/e2e/v1beta1/resume-e2e-experiment.go
- test/e2e/v1beta1/run-e2e-experiment.go
Fixes: https://github.com/kubeflow/katib/issues/1227.
I changed metric value from `float64` to `string`.
If metrics can't be reported, `unavailable` value will be recorded.
I added condition that `metric.Latest` can't be `unavailable` here: https://github.com/andreyvelich/katib/blob/cd6b37b3614cd226781c0feac1dcf6d568d07f01/pkg/controller.v1beta1/trial/trial_controller_util.go#L133-L135.
If **Objective** metric values were not reported, Trial will be in `False` status and `Succeeded` condition with this message:
`Warning  MetricsUnavailable  2m11s (x2 over 2m11s)  trial-controller  Metrics are not available for Job`.
Experiment will be still running and waiting until at least one **Objective** metric value will be reported.
I think it is correct workflow, since user can see that …
> String type for metric values

- Gopkg.lock
- Gopkg.toml
- pkg/controller.v1alpha3/consts/const.go
- pkg/controller.v1alpha3/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/LICENSE
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/backoff.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/doc.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/options.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/retry/retry.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/backoffutils/backoff.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils/doc.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils/nicemd.go
- vendor/github.com/grpc-ecosystem/go-grpc-middleware/util/metautils/single_key.go
- vendor/k8s.io/client-go/discovery/fake/discovery.go
- vendor/k8s.io/client-go/testing/actions.go
- vendor/k8s.io/client-go/testing/fake.go
- vendor/k8s.io/client-go/testing/fixture.go
This PR adds retries for gRPC calls in `suggestionclient.go`. One of the specific problems resolved by retries is the timing issue in Katib controller pod when running on Istio 1.5+: when Experiment deployment is ready, Envoy sidecar health check doesn't treat it as a healthy upstream yet and `ValidateAlgorithmSettings` call from the controller fails with `no healthy upstream`.
In general, retries can improve resilience and help to avoid transient failures instead of marking experiment as failed after the first and the only attempt.
> Adding retries for gRPC calls

- prow_config.yaml
I made few changes in prow to not trigger v1alpha3 workflow when we make changes in v1beta1:
1. Changed to `pkg/apis/controller/a*.go`. `pkg/apis/controller/*.go` was triggering workflow for any changes in `.go` files under `pkg/apis/controller` dir. 
Here is an example: https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubeflow_katib/1140/kubeflow-katib-presubmit/1271359897765679104/. `Triggering workflow e2e-v1alpha3 because pkg/apis/controller/common/v1beta1/common_types.go in dir pkg/apis/controller/*.go is modified.`
2. Added `pkg/apis/v1alpha3/*`.
3. Changed to `examples/v1alpha3/*`, I think we should trigger workflow if we make changes in Training containers examples.
4. To trigger correct test for `test/workflows/components/workflows-<version>.libsonnet` we can wait …
> Fix paths in prow config

- pkg/mock/v1beta1/util/katibclient/katibclient.go
- pkg/ui/v1beta1/backend.go
- pkg/ui/v1beta1/frontend/src/components/Templates/Common/AddDialog.jsx
- pkg/ui/v1beta1/frontend/src/reducers/general.js
- pkg/ui/v1beta1/frontend/src/reducers/template.js
- pkg/ui/v1beta1/frontend/src/sagas/index.js
- pkg/ui/v1beta1/util.go
- pkg/util/v1beta1/katibclient/katib_client.go
- test/e2e/v1beta1/resume-e2e-experiment.go
- test/e2e/v1beta1/run-e2e-experiment.go
Fixes: https://github.com/kubeflow/katib/issues/1088.
If there are not Trial Templates, ConfigMap must be deleted.
I added snack boxes to inform that Templates was updated/not updated.
I renamed functions to `CreateRuntimeObject`, `DeleteRuntimeObject`, `UpdateRuntimeObject` in `katib-client`. We can use them for various k8s objects.
> UI: Delete ConfigMap with no Trial Templates

- pkg/ui/v1beta1/frontend/src/components/HP/Monitor/HPJobTable.jsx
I added rows per page and pages for Trial info table.
I think it will be useful for big count of Trials.
> UI: Add Trial table pages

- pkg/ui/v1beta1/backend.go
- pkg/ui/v1beta1/frontend/src/components/Templates/Common/AddDialog.jsx
- pkg/ui/v1beta1/frontend/src/components/Templates/Common/FilterPanel.jsx
- pkg/ui/v1beta1/frontend/src/components/Templates/Common/TemplateList.jsx
- pkg/ui/v1beta1/frontend/src/components/Templates/Trial.jsx
- pkg/ui/v1beta1/frontend/src/reducers/general.js
- pkg/ui/v1beta1/util.go
Fixes: https://github.com/kubeflow/katib/issues/1087.
After this PR, user can create new ConfigMap with Trial Templates.
> UI: Add new ConfigMap with Trial Templates

- examples/v1beta1/nas/darts-cnn-cifar10/model.py
- examples/v1beta1/nas/darts-example-cpu.yaml
- pkg/suggestion/v1beta1/nas/darts/service.py
- test/e2e/v1beta1/run-e2e-experiment.go
- test/scripts/v1beta1/run-suggestion-darts.sh
- test/workflows/components/workflows-v1beta1.libsonnet
I added e2e test for DARTS for v1beta1.
This example should be run fast on CPU because it has only 1 operation, 1 layer, 1 darts node and parameters for stem layer are minimal.
> Add e2e test for DARTS

- examples/v1alpha3/fpga/README.md
- examples/v1alpha3/fpga/xgboost-example.yaml
- examples/v1beta1/README.md
- examples/v1beta1/fpga/README.md
- examples/v1beta1/fpga/xgboost-example.yaml
* Provides instructions on how to accelerate Katib Experiments on AWS F1 instances.
* Includes an accelerated XGBoost Parameter Tuning example.
> Add FPGA accelerated examples

- manifests/v1beta1/katib-controller/crd-experiment.yaml
I added `status` to `additionalPrinterColumns` for Experiments CRD, like we did with Trials and Suggestions CR.
> Add status to experiment CRD manifest

- examples/v1beta1/resume-experiment/from-volume-resume.yaml
- examples/v1beta1/resume-experiment/never-resume.yaml
- manifests/v1beta1/katib-controller/rbac.yaml
- pkg/apis/controller/experiments/v1beta1/experiment_types.go
- pkg/apis/controller/suggestions/v1beta1/suggestion_types.go
- pkg/apis/controller/suggestions/v1beta1/util.go
- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/experiment/experiment_controller.go
- pkg/controller.v1beta1/experiment/experiment_controller_test.go
- pkg/controller.v1beta1/experiment/experiment_util.go
- pkg/controller.v1beta1/experiment/suggestion/suggestion.go
- pkg/controller.v1beta1/experiment/util/status_util.go
- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/controller.v1beta1/suggestion/suggestion_controller.go
- pkg/controller.v1beta1/suggestion/suggestion_controller_util.go
- pkg/controller.v1beta1/util/suggestion.go
- pkg/webhook/v1beta1/experiment/validation_webhook.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- test/scripts/v1beta1/run-never-resume.sh
Fixes: https://github.com/kubeflow/katib/issues/1250.
This is implementation for resuming experiment from the Volume.
Steps:
1. I added new `ResumePolicy=FromVolume` which represents resuming experiment from the volume. 
@gaocegege @johnugeorge @sperlingxx what do you think about the name? Should we rename it to `ResumePolicy=VolumeSource` or think about better name, maybe rename `LongRunning` also? 
2. I added `ResumePolicy` to Suggestion API to understand if controller needs to deploy volume for the Suggestion. 
Do we need to add some volume specification to Suggestion API also. 
For example: StorageClassName, PVC name ?
3. If `ResumePolicy=VolumeSource`, PVC is created. If `StorageClassName=DefaultSuggestionStorageClass`, PV with local cluster path is created also.
4. I didn’t attach …
> Resume Experiment from Volume

- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/experiment/experiment_controller_test.go
- pkg/controller.v1beta1/experiment/experiment_util.go
- pkg/controller.v1beta1/experiment/manifest/generator.go
- pkg/controller.v1beta1/experiment/manifest/generator_test.go
- pkg/mock/v1alpha3/api/manager.go
- pkg/mock/v1alpha3/api/suggestion.go
- pkg/mock/v1alpha3/db/db.go
- pkg/mock/v1alpha3/experiment/manifest/generator.go
- pkg/mock/v1alpha3/experiment/suggestion/suggestion.go
- pkg/mock/v1alpha3/trial/managerclient/katibmanager.go
- pkg/mock/v1alpha3/util/katibclient/katibclient.go
- pkg/mock/v1beta1/api/suggestion.go
- pkg/mock/v1beta1/db/db.go
- pkg/mock/v1beta1/experiment/manifest/generator.go
- pkg/mock/v1beta1/experiment/suggestion/suggestion.go
- pkg/mock/v1beta1/trial/managerclient/katibmanager.go
- pkg/mock/v1beta1/util/katibclient/katibclient.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
After the refactor of trial template rendering in v1beta1, users can only fetch nothing but hyperparameter values. But, in v1alpha3, users can fetch trial name via placeholder (`{{.Trial}}`), which is quite useful in many conditions, such as appending it at the end of model storage url/path to avoid model overwriting.
This PR is trying to bring this feature back through additional trial template transformation, which is specialized for metadata injection. 
cc @andreyvelich @gaocegege  @johnugeorge
> support trial meta injection in trial template rendering

- pkg/controller.v1alpha3/experiment/experiment_controller.go
- pkg/controller.v1beta1/experiment/experiment_controller.go
Fixes #1222 
```release-note
```
> feat(experiment): Add a check before deletion

- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/experiment/manifest/generator.go
- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/mock/v1beta1/experiment/manifest/generator.go
- pkg/util/v1beta1/katibconfig/config.go
- pkg/webhook/v1beta1/experiment/validation_webhook.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
I changed metrics collector config parser to be consistent with suggestion config (See PR: https://github.com/kubeflow/katib/pull/1282).
Validation for metrics collector config checks if `GetMetricsCollectorConfigData` doesn't return error for the appropriate collector kind.
As well, I fixed name for the PV, when we check if PV exists.
> Get metrics collector config data refactor

- pkg/controller.v1beta1/experiment/experiment_controller.go
- pkg/controller.v1beta1/experiment/util/status_util.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
I added validation for restarting experiment in the webhook.
After that, user can see if restart experiment is possible or not.
/assign @sperlingxx @johnugeorge @gaocegege
> Validate restart Experiment parameters

- pkg/apis/controller/suggestions/v1beta1/util.go
- pkg/controller.v1beta1/experiment/experiment_controller.go
- pkg/controller.v1beta1/experiment/experiment_controller_test.go
- pkg/controller.v1beta1/experiment/experiment_util.go
- pkg/controller.v1beta1/suggestion/suggestion_controller.go
- pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
- test/e2e/v1beta1/resume-e2e-experiment.go
- test/e2e/v1beta1/run-e2e-experiment.go
- test/scripts/v1beta1/run-from-volume.sh
When I tried to update `parallelTrialCount` to less value, I got errors in controller.
In `deleteTrials` we should verify that Trials were successfully deleted before running reconcile loop again and update suggestion `requests` and `status.suggestions`.
Otherwise, [`updateTrialsSummary`](https://github.com/andreyvelich/katib/blob/04d78c24e47c6fe951099c5e5353bc79ecadc5af/pkg/controller.v1beta1/experiment/util/status_util.go#L55) is resynchronized with Trial list and `addCount` for [`ReconcileSuggestion`](https://github.com/andreyvelich/katib/blob/04d78c24e47c6fe951099c5e5353bc79ecadc5af/pkg/controller.v1beta1/experiment/experiment_controller.go#L458) is incorrect.
> Verify that Trials were successfully deleted

- pkg/controller.v1beta1/experiment/experiment_controller.go
- pkg/controller.v1beta1/experiment/experiment_controller_test.go
- pkg/controller.v1beta1/suggestion/suggestion_controller.go
- pkg/controller.v1beta1/trial/trial_controller.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
See comment: https://github.com/kubeflow/katib/pull/1281#issuecomment-666016563.
I changed error to log message to improve controller logging.
If `UpdateStatus` fails, we print the error and requeued reconciler.
As well, I noticed that `pod.Name` is not printed in inject webhook.
That is happening because object name is generated after Mutation unless appropriate controller has not set name explicitly (See comment: https://github.com/kubernetes/kubernetes/issues/46107#issuecomment-537592278.
I changed it to `GenerateName` instead.
> Log update object status error

- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/controller.v1beta1/suggestion/composer/composer_test.go
- pkg/util/v1beta1/katibconfig/config.go
I added possibilities to set PVC and PV specification from Katib config.
By default PVC uses `katib-suggestion` storage class name.
If PVC is created with this StorageClass, controller also deploys PV for the suggestion with settings from Katib config.
User can change `HostPath`, but if `HostPath` is `/tmp/katib/suggestions/` we added:
`/tmp/katib/suggestions/<suggestion-name>-<suggestion-algorithm>-<suggestion-namespace>` to the `HostPath`.
/assign @johnugeorge @gaocegege @sperlingxx
> Support volume settings in Katib config

- docs/proposals/trial-custom-crd.md
See comment: https://github.com/kubeflow/katib/issues/1214#issuecomment-659756130.
I added proposal for supporting any kind of CRD in Trial Spec.
Please take a look @gaocegege @johnugeorge @czheng94
/cc @sperlingxx @jlewi @nielsmeima @terrykong
> Proposal: Support custom CRD in Trial Job

- test/scripts/v1alpha3/create-cluster.sh
- test/scripts/v1beta1/create-cluster.sh
- test/workflows/components/workflows-v1alpha3.libsonnet
- test/workflows/components/workflows-v1beta1.libsonnet
It seems that we can't create new GKE cluster with 1.14 version.
Ref: https://cloud.google.com/kubernetes-engine/docs/release-notes#august_27_2020_r28.
I update version to 1.16, KF serving [uses it](https://github.com/kubeflow/kfserving/blob/master/test/scripts/create-cluster.sh#L35) also.
/cc @yuzisun
> Update CI test cluster version to 1.16

- pkg/controller.v1beta1/experiment/experiment_controller.go
We should check that Experiment is restartable in controller as well as in validation webhook.
For example, when Experiment is completed because optimal Trial was found, restart Experiment should not be triggered.
/assign @gaocegege @sperlingxx @johnugeorge
> Fix restart check in controller for completed experiments

- cmd/katib-controller/v1beta1/main.go
- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/trial/trial_controller.go
- pkg/controller.v1beta1/trial/trial_controller_test.go
- pkg/controller.v1beta1/trial/util/flag_util.go
- pkg/controller.v1beta1/trial/util/prometheus_metrics.go
Related: https://github.com/kubeflow/katib/issues/1214.
I added possibility to set trial controller watchers from controller flags.
In controller deployment flags should be in format `Kind.version.group`.
For example:
```
args:
- "-trial-resource=TFJob.v1.kubeflow.org".
- "-trial-resource=Workflow.v1alpha1.argoproj.io"
- "-trial-resource=Job.v1.batch"
```
/assign @gaocegege @sperlingxx @johnugeorge
> Custom CRD: Set dynamic watch from controller flags

- pkg/apis/controller/experiments/v1beta1/experiment_types.go
- pkg/apis/controller/experiments/v1beta1/zz_generated.deepcopy.go
- pkg/apis/controller/trials/v1beta1/trial_types.go
- pkg/apis/controller/trials/v1beta1/zz_generated.deepcopy.go
- pkg/apis/v1beta1/openapi_generated.go
- pkg/apis/v1beta1/swagger.json
- pkg/controller.v1beta1/experiment/experiment_util.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
- pkg/webhook/v1beta1/pod/utils.go
- sdk/python/v1beta1/docs/V1beta1SuggestionSpec.md
- sdk/python/v1beta1/docs/V1beta1TrialSpec.md
- sdk/python/v1beta1/docs/V1beta1TrialTemplate.md
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_suggestion_spec.py
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_spec.py
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_template.py
Related: https://github.com/kubeflow/katib/issues/1214.
I named API: `PrimaryPodLabels` instead of `PrimaryPodLabel` because user can set more than 1 label there.
`PrimaryPodLabels` defines labels that mutated Pod must have.
I didn't remove `isMasterRole` to not brake current test examples.
Later we can update all examples with new APIs and remove redundant code.
Also I generated codegens and SDK.
/assign @gaocegege @johnugeorge @sperlingxx
> Custom CRD: Add primary pod labels

- pkg/suggestion/v1beta1/hyperopt/base_service.py
See comment: https://github.com/kubeflow/katib/issues/1314#issuecomment-681076525.
After this fix, we should not see `list index out of range` error.
/assign @gaocegege @sperlingxx 
/cc @jimmy-hawkfish
> Fix problem with Hyperopt Out of Range error

- pkg/webhook/v1beta1/pod/const.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
- pkg/webhook/v1beta1/pod/utils.go
Fixes: https://github.com/kubeflow/katib/issues/1271.
I refactored `getKatibJob` to correctly inject metrics collector.
`getKatibJob` is looking for Trial ownership in all pod's nested objects recursively.
These objects should be created ones Pod is mutated.
Also, I moved functions that are not belong to `sidecarInjector` struct to `utils` to be consistent with [Validation webhook](https://github.com/kubeflow/katib/blob/master/pkg/webhook/v1beta1/experiment/validation_webhook.go).
/assign @sperlingxx @gaocegege @johnugeorge
> Fix Pod's ownership to inject metrics collector

- pkg/apis/controller/experiments/v1beta1/experiment_types.go
- pkg/apis/controller/trials/v1beta1/trial_types.go
- pkg/apis/v1beta1/openapi_generated.go
- pkg/apis/v1beta1/swagger.json
- pkg/controller.v1beta1/experiment/experiment_util.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
- pkg/webhook/v1beta1/pod/utils.go
- sdk/python/v1beta1/docs/V1beta1TrialSpec.md
- sdk/python/v1beta1/docs/V1beta1TrialTemplate.md
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_spec.py
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_template.py
Related: https://github.com/kubeflow/katib/issues/1214.
WIP until we merge this: https://github.com/kubeflow/katib/pull/1305, after that I will generate API clients, etc, but it would be great if you can start to review it.
`PrimaryContainerName ` defines container name that metrics collector should mutate.
/assign @gaocegege @johnugeorge @sperlingxx
> Custom CRD: Add primary container name

- Gopkg.lock
- Gopkg.toml
- pkg/apis/controller/experiments/v1beta1/experiment_types.go
- pkg/apis/controller/trials/v1beta1/trial_types.go
- pkg/apis/v1beta1/openapi_generated.go
- pkg/apis/v1beta1/swagger.json
- pkg/controller.v1beta1/experiment/experiment_util.go
- pkg/controller.v1beta1/trial/trial_controller.go
- pkg/controller.v1beta1/trial/trial_controller_util.go
- pkg/controller.v1beta1/trial/util/job_util.go
- pkg/controller.v1beta1/trial/util/job_util_test.go
- sdk/python/v1beta1/docs/V1beta1TrialSpec.md
- sdk/python/v1beta1/docs/V1beta1TrialTemplate.md
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_spec.py
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_trial_template.py
- vendor/github.com/tidwall/gjson/LICENSE
- vendor/github.com/tidwall/gjson/gjson.go
- vendor/github.com/tidwall/match/LICENSE
- vendor/github.com/tidwall/match/match.go
- vendor/github.com/tidwall/pretty/LICENSE
- vendor/github.com/tidwall/pretty/pretty.go
Related: https://github.com/kubeflow/katib/issues/1214.
WIP until we merge this: https://github.com/kubeflow/katib/pull/1305, after that I will generate API clients, etc, but it would be great if you can start to review it.
I changed a bit API from proposal to support various success and failure conditions in CRD.
As I can see not all CRDs are using the same status approach with Conditions list as Kubeflow operators or BatchJobs. 
For example, [Argo](https://github.com/argoproj/argo/blob/master/pkg/apis/workflow/v1alpha1/workflow_types.go#L945) uses `.status.phase` to define whether Node is succeeded or failed.
To handle all of these cases, I proposed approach when user defines `SuccessCondition` and `FailureCondition` in Experiment.
This condition is …
> Custom CRD: Support dynamic Trial's jobs conditions

- .travis.yml
- hack/update-gofmt.sh
- hack/verify-gofmt.sh
See comment: https://github.com/kubeflow/katib/pull/1312#issuecomment-693612090.
We should not update .pb files in `update-gofmt` script.
Also, I update nvm version for travis.
/cc @khersey
> feat: Ignore pb files in update gofmt

- examples/v1beta1/trial-metadata-substitution.yaml
Part of https://github.com/kubeflow/katib/issues/1280.
I added example for trial metadata injection from template.
/assign @sperlingxx
> Add trial metadata substitution example

- pkg/apis/controller/trials/v1beta1/util.go
- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
- pkg/controller.v1beta1/trial/trial_controller.go
- pkg/controller.v1beta1/trial/trial_controller_util.go
- pkg/controller.v1beta1/trial/util/job_util.go
- pkg/controller.v1beta1/util/annotations.go
- pkg/db/v1beta1/mysql/mysql.go
- pkg/db/v1beta1/mysql/mysql_test.go
- pkg/metricscollector/v1beta1/common/const.py
- pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
- pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
- pkg/webhook/v1beta1/pod/utils.go
- test/e2e/v1beta1/invalid-experiment.yaml
I was testing Custom CRD.
I was able to run Tekton `TaskRun` as Trial CR. I Will submit PR with few examples soon.
I found these problems while running:
- I disabled `MutateJob` in controller. We will track it in this issue: https://github.com/kubeflow/katib/issues/1320.
- I disabled validation for Job other than `SupportedJobList`.
- We should verify `PrimaryContainerName` in `MutateVolume` also.
- I changed `INSERT` in `RegisterObservationLog` function. It is better to insert all lines in one SQL query, instead of running separate query for each line. It helps to avoid unnecessary Trial updates.
- I added reconcile re-queue if metrics are not available. This use-case happens in Tekton job. Tekton task is succeeded once Training container is finished, but metrics can be not collected, …
> Enhancement for Custom CRD

- examples/v1beta1/README.md
- examples/v1beta1/mpijob-horovod.yaml
- manifests/v1beta1/katib-controller/katib-controller.yaml
- manifests/v1beta1/katib-controller/rbac.yaml
This example of using MPI operator with Horovod mnist example. Blocked by: https://github.com/kubeflow/katib/pull/1333.
Fixes: https://github.com/kubeflow/katib/issues/1181.
/cc @terrytangyuan @YuxiJin-tobeyjin @carmark
> Add MPI operator horovod example

- examples/v1beta1/tekton/README.md
- examples/v1beta1/tekton/pipeline-run.yaml
- manifests/v1beta1/katib-controller/katib-controller.yaml
- manifests/v1beta1/katib-controller/rbac.yaml
This is example of using Tekton Pipeline in Katib Trial template. Blocked by: https://github.com/kubeflow/katib/pull/1333.
I am currently having problems with Argo support, because of that: https://github.com/kubeflow/katib/issues/1214#issuecomment-689663255.
In any case, I think Tekton should also work well in addition to Argo Workflows (https://github.com/kubeflow/katib/issues/1081).
/cc @czheng94 @nielsmeima @terrykong
> Add Tekton Pipeline example

- pkg/ui/v1beta1/frontend/src/actions/generalActions.js
- pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/MetricsCollector.jsx
- pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialParameters.jsx
- pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialTemplate.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
- pkg/ui/v1beta1/frontend/src/constants/constants.js
- pkg/ui/v1beta1/frontend/src/reducers/general.js
- pkg/ui/v1beta1/frontend/src/reducers/hpCreate.js
- pkg/ui/v1beta1/frontend/src/reducers/nasCreate.js
Fixes: https://github.com/kubeflow/katib/issues/1217.
I added all parameters from `TrialTemplate` to submit Experiment page.
As well, user can add template YAML directly from submit Experiment by parameters page.
> UI: Support new parameters in Trial template 

- pkg/ui/v1beta1/frontend/src/actions/hpCreateActions.js
- pkg/ui/v1beta1/frontend/src/actions/nasCreateActions.js
- pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Algorithm.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/CommonMeta.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/CommonSpec.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Objective.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/Parameters.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/Algorithm.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/CommonMeta.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/CommonSpec.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/NASConfig.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/Objective.jsx
- pkg/ui/v1beta1/frontend/src/reducers/hpCreate.js
- pkg/ui/v1beta1/frontend/src/reducers/nasCreate.js
Fixes: https://github.com/kubeflow/katib/issues/1220.
I added metric strategies to submit Experiment page.
> UI: Support metrics strategies to submit Experiment by parameters

- pkg/ui/v1beta1/frontend/src/components/HP/Create/Params/CommonSpec.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/Params/CommonSpec.jsx
- pkg/ui/v1beta1/frontend/src/reducers/hpCreate.js
- pkg/ui/v1beta1/frontend/src/reducers/nasCreate.js
Fixes: https://github.com/kubeflow/katib/issues/1221.
I added `ResumePolicy` select box in submit Experiment by parameters.
Also, I added missing HP and NAS supported algorithms.
> UI: Add resume policy to submit Experiment by parameters

- pkg/apis/controller/experiments/v1beta1/constants.go
- pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
I think it's better to remove default values for the `spec.trialTemplate.TrialSpec`.
It's make very unclear for the user that Experiment can be created without `trialTemplate` and which `spec.parameters` should be set.
WDYT @gaocegege @johnugeorge  ?
> Remove default values for Trial template

- pkg/ui/v1beta1/frontend/src/actions/generalActions.js
- pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/EarlyStopping.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Monitor/HPJobTable.jsx
- pkg/ui/v1beta1/frontend/src/reducers/general.js
I added early stopping in submit Experiment page in the UI.
> UI: Add early stopping to submit Experiment by parameters

- cmd/suggestion/nas/enas/v1alpha3/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- examples/v1alpha3/nas/enas-cnn-cifar10/requirements-cpu.txt
- examples/v1alpha3/nas/enas-cnn-cifar10/requirements-gpu.txt
- examples/v1beta1/nas/enas-cnn-cifar10/requirements-cpu.txt
- examples/v1beta1/nas/enas-cnn-cifar10/requirements-gpu.txt
I manually changed TF version to 1.15.4, I verified and it should work.
Related PRs: https://github.com/kubeflow/katib/pull/1353, https://github.com/kubeflow/katib/pull/1352, https://github.com/kubeflow/katib/pull/1351.
We should re-created PR, since our CI has been changed.
> Bump Tensorflow from 1.15.2 to 1.15.4

- examples/v1beta1/trial-configmap-source.yaml
I added example for the ConfigMap source of Trial template.
I think, it's useful to point user to this example in the new trial template documentation.
> Add example with ConfigMap source for the Trial template

- prow_config.yaml
- sdk/python/v1beta1/README.md
- sdk/python/v1beta1/setup.py
- setup.py
I updated SDK for the Katib 0.10 release.
Let's stick SDK version with Katib version to be consistent between the releases.
Fixes: https://github.com/kubeflow/katib/issues/1331.
If we change any API before the Katib 0.11 release, we can release new Patch SDK version. For example: 
`kubeflow-katib: 0.10.1`.
As well, I delete `setup.py`. It was added in this PR: https://github.com/kubeflow/katib/pull/406, we are not using it in [`python-test.sh`](https://github.com/kubeflow/katib/blob/master/test/scripts/v1beta1/python-tests.sh).
What do you think @gaocegege @johnugeorge ?
> Update Python SDK version to 0.10.0

- manifests/v1beta1/katib-controller/rbac.yaml
- pkg/webhook/v1beta1/pod/inject_webhook.go
We should add this role to run Tekton Pipeline.
The workflow is that:
Katib `Trial` -> Tekton `PipelineRun` -> Tekton `TaskRun` -> Kubernetes `Pod`.
Katib controller should have access to all of these resources.
> Fix: Add taskruns to Katib controller role to run Tekton Pipelines

- cmd/metricscollector/v1beta1/file-metricscollector/main.go
- examples/v1beta1/early-stopping/median-stop.yaml
Fixes: https://github.com/kubeflow/katib/issues/1385.
We should not wait one more step to compare values.
As well, I removed unnecessary params from the early stopping yaml.
> Fix compare step for the early stopping

- .github/stale.yml
I've added Stale config so we can better track inactive issues in Katib.
/cc @jlewi
> Add Stale config to close inactivity issues

- ADOPTERS.md
- README.md
I moved Adopters file to the root and more users can see it.
Also, let's keep the list in alphabetical order.
> Move Adopters file

- pkg/suggestion/v1beta1/goptuna/converter.go
- pkg/suggestion/v1beta1/goptuna/sample.go
In Goptuna Suggestion we should transfer the `EarlyStopped` Trials to `Pruned`.
Is that correct @c-bata ?
Also, I added additional info in errors.
/assign @c-bata @gaocegege @johnugeorge
> Fix Early Stopped Trials in Goptuna Suggestion

- cmd/suggestion/chocolate/v1beta1/requirements.txt
- cmd/suggestion/hyperband/v1beta1/requirements.txt
- cmd/suggestion/hyperopt/v1beta1/requirements.txt
- cmd/suggestion/skopt/v1beta1/requirements.txt
Fixes: https://github.com/kubeflow/katib/issues/1399.
I think we don't need `duecredit` package in our Suggestions.
> Remove duecredit pkg from the Suggestions

- .travis.yml
- pkg/ui/v1beta1/frontend/src/components/Common/Create/Params/Trial/TrialConfigMap.jsx
- pkg/ui/v1beta1/frontend/src/components/HP/Create/HPParameters.jsx
- pkg/ui/v1beta1/frontend/src/components/KubeflowDashboard.jsx
- pkg/ui/v1beta1/frontend/src/components/NAS/Create/NASParameters.jsx
- pkg/ui/v1beta1/frontend/src/components/Templates/Common/AddDialog.jsx
- pkg/ui/v1beta1/frontend/src/sagas/index.js
We should update the Prettier version for our Katib UI.
Even the [VSCode plugin](https://github.com/prettier/prettier-vscode) is using Prettier >= 2.0
> Bump Prettier to 2.2.0 for the Katib UI

- OWNERS
See comment: https://github.com/kubeflow/katib/pull/1403#issuecomment-737420797.
I remove redundant indentation in the OWNERS file and alphabetise names.
> Fix indentation in the OWNERS file

- operators/README.md
Looking at this README, it is hard to follow by users who are not familiar with `juju`. 
Adding initial steps to get started with Juju.
> Add Juju install commands to operators README

- .github/workflows/test-charmed-katib.yaml
- operators/bundle-edge.yaml
Adds Github Actions CI for charm operators, to ensure that there's no breakages / regressions
N/A
Adds new bundle for CI purposes that points at the `latest` tags instead of particular revisions.
```release-note
NONE
```
> Add Github Actions CI for charm operators

- pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
Invalid example url
Fixes #
```release-note
```
> Invalid example url

- prow_config.yaml
- test/workflows/components/workflows-v1beta1.libsonnet
Migrate katib to new test-infra
Fixes #1422 
```release-note
NONE
```
/cc @andreyvelich 
/hold
> Migrate katib to new test-infra

- operators/OWNERS
- operators/katib-controller/reactive/katib_controller.py
- operators/katib-ui/reactive/katib_ui.py
This will change the katib-controller and katib-uiroles to clusterroles.
Additionally Dominik Fleischmann is being added to the owners of the katib operators.
> Change roles to clusterroles for operators

- pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
Fixes: https://github.com/kubeflow/katib/issues/1435.
We should verify nil objective before set the default values for metrics strategies.
/cc @ScrapCodes
> Verify nil objective in Experiment defaults

- README.md
- docs/presentations.md
- scripts/update-readme-toc.sh
I updated README with community information and add doc with Katib presentations.
What do you think @jbottum @gaocegege @johnugeorge  ?
> Add Katib presentations and community information

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Added API to get list of trials that succeded with hyperparam and metrics to KatibClient
```
get_success_trial_details(self, name, namespace) -> List of trial name with hyperparams and metrics
```
> Enhance katib client by adding get_success_trial_details()

- docs/developer-guide.md
Signed-off-by: Anna Jung (VMware) <antheaj@vmware.com>
- Document Katib controller flags in the developer guide
- Flags were based on https://github.com/kubeflow/katib/blob/fe64c18172ba370fb3934552c50442f1da21ec1a/cmd/katib-controller/v1beta1/main.go#L50
Fixes https://github.com/kubeflow/katib/issues/1239
N/A
```release-note
NONE
```
/hold for feedback
> Add katib controller flags to developers guide

- .github/workflows/test-charmed-katib.yaml
Fixes Github Actions CI testing by bumping up installed version of MicroK8s from 1.19 to 1.20. I haven't delved into why exactly it's failing, but did raise a MicroK8s issue:
https://github.com/ubuntu/microk8s/issues/2083
> Re-enable Github Actions

- docs/new-algorithm-service.md
We should update our doc for the new Algorithm service since our CI has been changed.
/cc @gaocegege @johnugeorge @PatrickXYS
> Update new algorithm service doc

- pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
- pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-types.const.ts
- pkg/new-ui/v1beta1/frontend/src/app/enumerations/algorithms.enum.ts
- pkg/new-ui/v1beta1/frontend/src/app/models/experiment.k8s.model.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.scss
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.scss
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.scss
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.scss
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-thresholds/trial-thresholds.component.html
- pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
It adds support to the new UI's #1421 form for
* resumePolicy
* Early Stopping
* Trial Parameters
With this PR the form will be exposing all of the fields required to create a new Experiment. But, at the same time the only limitation I bumped into is the fact that the new UI doesn't currently allow us to edit the `source` of the Metric Collector. I'll comment this on our issue where we track the missing features. 
<details><summary>Videos of the changes</summary>
<p>
https://user-images.githubusercontent.com/11134742/110657178-4a4e7f00-81c9-11eb-9e2b-f90ccef6d649.mp4
https://user-images.githubusercontent.com/11134742/110657187-4cb0d900-81c9-11eb-98bb-61a0826dffae.mp4
https://user-images.githubusercontent.com/11134742/110657200-4e7a9c80-81c9-11eb-8395 …
> Add missing form fields to new UI

- hack/update-openapigen.sh
- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/controller.v1beta1/suggestion/suggestion_controller.go
- pkg/util/v1beta1/katibconfig/config.go
Blocked by: https://github.com/kubeflow/website/pull/2533.
I removed few TODOs that we completed.
> Remove completed TODOs for Katib config

- examples/v1beta1/bayesianoptimization-example.yaml
- examples/v1beta1/cmaes-example.yaml
- examples/v1beta1/custom-metricscollector-example.yaml
- examples/v1beta1/early-stopping/median-stop.yaml
- examples/v1beta1/file-metricscollector-example.yaml
- examples/v1beta1/grid-example.yaml
- examples/v1beta1/hyperband-example.yaml
- examples/v1beta1/metric-strategy-example.yaml
- examples/v1beta1/nas/darts-example-cpu.yaml
- examples/v1beta1/nas/darts-example-gpu.yaml
- examples/v1beta1/nas/enas-example-cpu.yaml
- examples/v1beta1/nas/enas-example-gpu.yaml
- examples/v1beta1/pytorchjob-example.yaml
- examples/v1beta1/random-example.yaml
- examples/v1beta1/resume-experiment/from-volume-resume.yaml
- examples/v1beta1/resume-experiment/never-resume.yaml
- examples/v1beta1/tekton/pipeline-run.yaml
- examples/v1beta1/tpe-example.yaml
- examples/v1beta1/trial-metadata-substitution.yaml
- manifests/v1beta1/components/controller/trial-templates.yaml
- operators/katib-controller/src/defaultTrialTemplate.yaml
- operators/katib-controller/src/enasCPUTemplate.yaml
- operators/katib-controller/src/pytorchJobTemplate.yaml
- test/e2e/v1beta1/invalid-experiment.yaml
- test/e2e/v1beta1/run-e2e-experiment.go
- test/e2e/v1beta1/valid-experiment.yaml
This PR: https://github.com/kubeflow/katib/pull/1464 fixes problems in the PyTorch and MXNet mnist examples.
We should update the examples images to the `v1beta1-45c5727` tag.
> Update Trial images to v1beta1-45c5727

- Makefile
- docs/developer-guide.md
- scripts/v1beta1/build.sh
- scripts/v1beta1/push.sh
- scripts/v1beta1/release.sh
Fixes: https://github.com/kubeflow/katib/issues/1466.
I added Katib release script.
In `Makefile` we currently have:
1. `push-latest` to publish images to the registry with the latest and commit tags from the master branch.
2. `push-tag` to publish image to the registry with the release and commit tags from the release branch.
3. `release` to make a new Katib release.
I changed `build.sh` and `push.sh` scripts to use them when publishing `latest` images and `release` images.
Release script follows this (e.g. Branch = `release-0.11`, Tag = `v0.11.0`):
1. Clone Katib repo to the temp dir.
2. Create a new branch (`release-0.11`), if it doesn't exist or use the existing branch.
3. Change image tags to the `v0.11.0` in the Katib installs.
4. Publish Katib SDK with version - `0.11.0`.
5. Commit …
> Add release process script

- docs/developer-guide.md
- examples/v1beta1/tekton/README.md
- pkg/ui/v1beta1/README.md
- pkg/ui/v1beta1/frontend/src/components/Menu/Main.jsx
Fix the broken instructions link in the UI, also other references to the old kubeflow website structure.
> fix broken links to kubeflow website

- docs/developer-guide.md
I removed flags from the developer guide that we currently disable: https://github.com/kubeflow/katib/blob/master/cmd/katib-controller/v1beta1/main.go#L57-L60.
If we decide to add them later, we should update the developer guide.
/cc @annajung @gaocegege @johnugeorge
> Remove legacy controller flags from the developer guide

- prow_config.yaml
We should update Prow to trigger CI once we make changes in the New UI or Early Stopping.
I keep folders in the alphabetical order.
/cc @kimwnasptd @gaocegege @johnugeorge
> Update Prow with the latest folder structure

- cmd/new-ui/v1beta1/Dockerfile
- pkg/new-ui/v1beta1/README.md
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
This PR updates the UI code, for the new UI #1421, to
1. detect if the dashboard is present
2. if it's not then show the namespace selector component
This is a first step for #1437. With this fix the new UI will be able to also be deployed as a standalone app and not always rely on the Central Dashboard to be present, to allow the users to navigate and inspect namespaces.
This brings the app at the same state and with the same behavior for the standalone mode with the current UI. Next steps would be to extend the current backend to use `SubjectAccessReviews` to perform authorization checks, if the app is deployed in kubeflow mode. But we can coordinate on this effort in our tracking issue #1437.
This is a first step …
> new-ui: Show the Namespace Selector when app is deployed as standalone

- docs/developer-guide.md
Fixes: https://github.com/kubeflow/katib/issues/1266.
I added Katib webhook documentation.
/cc @connorlwilkes @kylepad @gaocegege @johnugeorge @yanniszark
> Add Katib webhook documentation

- scripts/v1beta1/release.sh
- test/e2e/v1beta1/run-e2e-experiment.go
I fixed incorrect replace for the Katib image tags in the release script.
The current script replaces `mysql` image tag for the [`katib-ibm` install](https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/installs/katib-ibm/kustomization.yaml#L9) and doesn't replace tags in the `katib-config-patch.yaml`, which is not correct.
I make the explicit replace in the `katib-external-db/kustomization.yaml`, `katib-config-patch.yaml`, `katib-standalone/kustomization.yaml` and `katib-with-kubeflow/kustomization.yaml` files to make sure that we don't replace tags in the other places.
Please take a look.
/assign @yanniszark @gaocegege @johnugeorge
> Fix release script to replace Katib image tags

- hack/cert-generator.sh
- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/db-manager/db-manager.yaml
- manifests/v1beta1/components/mysql/mysql.yaml
- manifests/v1beta1/components/ui/ui.yaml
- manifests/v1beta1/components/webhook/cert-generator.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/certificate.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/kustomization.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/params.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/patches/katib-cert-injection.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/kustomization.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/patches/mysql-pvc.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/ui-virtual-service.yaml
Fixes https://github.com/kubeflow/katib/issues/1499
Fixes https://github.com/kubeflow/katib/issues/1500
Fixes https://github.com/kubeflow/katib/issues/1501
@andreyvelich I made the changes needed for Kubeflow 1.3, as the aforementioned issues show.
In addition, I made sure that the VirtualService is deployable by default, as other components' manifests do.
After merging, I will create a cherry-pick PR.
> Katib manifests fixes for 1.3

- hack/cert-generator.sh
- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/db-manager/db-manager.yaml
- manifests/v1beta1/components/mysql/mysql.yaml
- manifests/v1beta1/components/ui/ui.yaml
- manifests/v1beta1/components/webhook/cert-generator.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/certificate.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/kustomization.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/params.yaml
- manifests/v1beta1/installs/katib-with-kubeflow-cert-manager/patches/katib-cert-injection.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/kustomization.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/patches/mysql-pvc.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/ui-virtual-service.yaml
@andreyvelich this is the cherry-pick of #1502.
I added an extra commit to pin images for `katib-with-kubeflow-cert-manager`.
> Automated cherry pick of #1502 upstream release 0.11

- test/scripts/v1beta1/setup-katib.sh
Fixes: https://github.com/kubeflow/katib/issues/1504.
We should replace any tag in the `setup-katib.sh` script.
/cc @gaocegege @johnugeorge @yanniszark
> Fix setup Katib script to work on the release branch

- scripts/v1beta1/release.sh
- test/e2e/v1beta1/run-e2e-experiment.go
Fixes: https://github.com/kubeflow/katib/issues/1505.
We should add `katib-with-kubeflow-cert-manager` install to release script for updating the images.
/cc @yanniszark @gaocegege @johnugeorge
> Add cert manager install to the release script

- README.md
The link to the Kustomization's manifest to use the new Katib UI is broken like:
https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/installs/katib-standalone/kustomization.yaml#L43
This PR fixes the link by specifying the latest commit revision on master branch.
cc @kimwnasptd
None
None
```release-note
```
> Fix a link to Kustomize manifest for new Katib UI

- cmd/katib-controller/v1beta1/main.go
Fixes #1516 
```release-note
```
> Error messages corrected

- ROADMAP.md
Fixes: https://github.com/kubeflow/katib/issues/1484.
This is initial draft for our ROADMAP in 2021.
Please take a look and left your thoughts what we should add/priorities.
/cc @gaocegege @johnugeorge @PatrickXYS @terrytangyuan @kimwnasptd @yanniszark @jbottum @c-bata @RFMVasconcelos @knkski @frankmanbb
> Add Katib 2021 ROADMAP

- .github/workflows/test-go.yaml
- go.mod
- go.sum
I added `go mod tidy` check to GitHub actions.
That will help us to avoid invalid sync `go.mod` with `go.sum`.
> Add go mod tidy check to GitHub Actions

- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
When invalid-named experiment CREATE API was requested, such experiment status was shown as CREATED, but in fact it was not created.
Therefore, naming convention should be checked in validating webhook
Fixes #1538
```release-note
NONE
```
> feat: add naming regex check on validating webhook

- .github/workflows/test-go.yaml
- go.sum
- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/controller.v1beta1/suggestion/composer/composer_test.go
- pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
- pkg/controller.v1beta1/suggestion/suggestion_controller_util.go
- pkg/util/v1beta1/katibconfig/config.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- test/e2e/v1beta1/run-e2e-experiment.go
Related: https://github.com/kubeflow/katib/issues/1479.
I disabled default PV creation for Experiment with from volume `resumePolicy`.
As discussed here: https://github.com/kubeflow/katib/issues/1479#issuecomment-805319555, it is very uncommon to create custom PV for the Experiment.
/cc @gaocegege @johnugeorge @maanur @heilerich
> Disable default PV for Experiment with resume from volume

- operators/katib-controller/requirements.txt
- operators/katib-db-manager/requirements.txt
- operators/katib-ui/metadata.yaml
- operators/katib-ui/requirements.txt
- operators/katib-ui/src/charm.py
Switches the `katib-ui` operator to the `serialized-data-interface` library, which provides a way to declaratively define relationships.
```release-note
NONE
```
> Switch to sdi

- operators/README.md
simple fix for a typo
```release-note
NONE
```
> fix typo in operators/README

- pkg/util/v1beta1/katibconfig/config.go
Fixes: https://github.com/kubeflow/katib/issues/1559.
This will allow to specify empty resources for CPU and Memory in Katib config.
/cc @gaocegege @johnugeorge @sravi999
> Allow empty resources for CPU and Memory in Katib config

- Makefile
- pkg/apis/manager/health/build.sh
- pkg/apis/manager/v1beta1/build.sh
To avoid problems like this: https://github.com/kubeflow/katib/pull/1492, I added gRPC build script to the CI.
> Add gRPC build script to CI

- .github/workflows/test-charmed-katib.yaml
The snap store is now the preferred place for obtaining charmcraft, as opposed to pypi.org.
Fixes broken CI process
> Switch to charmcraft snap for CI

- pkg/controller.v1beta1/trial/trial_controller.go
Fixes: https://github.com/kubeflow/katib/issues/1320.
I think we can safely remove Job Level mutation from the controller.
The issue is created almost 1 year ago and our users don't complain about it.
> Remove Job Level Mutation from Katib Controller

- .github/workflows/test-charmed-katib.yaml
Install charmcraft 1.0.0 through pip for now until we move to pytest-operator tests.
> Install charmcraft 1.0.0

- manifests/v1beta1/components/mysql/mysql.yaml
- This PR fixes the mysql version to a constant tag.
The current image `mysql:8` is mutable tag. Every time an update is made this points to a new version. I.e it could point to 8.0.1 or 8.0.2 or 8.0.26. [SQL upgrades are one-way it is not possible to downgrade](https://www.percona.com/blog/2020/01/10/mysql-8-minor-version-upgrades-are-one-way-only/). 
This leads to errors if the image is already cached on kubernetes node. For example node already has 8.0.2 image cached, but 8.0.26 on was used on another node.
```
[InnoDB] Cannot boot server version 80017 on data directory built by version 80018. Downgrade is not supported
```
Another possible alternative would be to set image pull policy to Always.
```
imagePullPolicy: Always
```
> fix mysql version in docker image

- README.md
- examples/v1beta1/README.md
- examples/v1beta1/xgboost-lightgbm.yaml
- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/controller/rbac.yaml
Fixes: https://github.com/kubeflow/katib/issues/1558.
I added example for XGBoost with LightGBM sample.
Currently, I am using `docker.io/kubeflowkatib/xgboost-lightgbm:1.0` image for this example.
Please take a look @terrytangyuan @gaocegege @johnugeorge @Jeffwan 
cc @merlintang @0as1s
> Add support for XGBoost Operator with LightGBM example

- pkg/suggestion/v1beta1/skopt/service.py
- test/suggestion/v1beta1/test_skopt_service.py
- support validating for bayesianoptimization algorithm settings (skopt)
- validation criteria were referenced by https://scikit-optimize.github.io/stable/modules/generated/skopt.Optimizer.html
- we need it since for fast fail since user could mistake
fixes part of #1126
**Checklist:**
**How I Test**
- we could check with unit-test code
- Also, I've checked in my katib cluster with new skopt image with this yaml
```
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
name: random-example-3
namespace: kubeflow
spec:
algorithm:
algorithmName: bayesianoptimization
algorithmSettings:
- name: …
```
> [enh]: validate for bayesian optimization algorithm settings

- README.md
- docs/new-algorithm-service.md
- docs/presentations.md
- examples/v1beta1/argo/README.md
- examples/v1beta1/argo/argo-workflow.yaml
- examples/v1beta1/nas/darts-cnn-cifar10/architect.py
- examples/v1beta1/tekton/README.md
- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/controller/rbac.yaml
Fixes: https://github.com/kubeflow/katib/issues/1081.
I was able to integrate Argo Workflows in Katib's Experiment.
Thanks to @alexec and @terrytangyuan for helping with this issue: https://github.com/argoproj/argo-workflows/issues/4545.
Please take a look.
cc @jbottum @terrykong @nielsmeima
> Add Support for Argo Workflows

- .github/workflows/test-go.yaml
- Makefile
- manifests/v1beta1/components/crd/experiment.yaml
- manifests/v1beta1/components/crd/suggestion.yaml
- manifests/v1beta1/components/crd/trial.yaml
Fixes: https://github.com/kubeflow/katib/issues/1581, https://github.com/kubeflow/katib/issues/1354.
I upgraded `apiextensions.k8s.io/v1` since `v1beta1` was deprecated long time ago.
We still need to do some work to generate `openAPIV3Schema`, that can be done in the future PRs.
/cc @daftping
> Upgrade CRDs to apiextensions.k8s.io/v1

- pkg/suggestion/v1beta1/chocolate/service.py
- test/suggestion/v1beta1/test_chocolate_service.py
- test/suggestion/v1beta1/test_hyperopt_service.py
- test/suggestion/v1beta1/test_skopt_service.py
- test/suggestion/v1beta1/utils.py
Fixes: https://github.com/kubeflow/katib/issues/1122.
I added validation for Chocolate Grid suggestion to check if `max_trial_count` >= all possible search space combination.
Also, I moved `call_validate()` test function to utils to use it in Chocolate also.
/cc @sperlingxx
> Validate possible operations for Grid suggestion

- examples/v1beta1/trial-configmap-source.yaml
- manifests/v1beta1/components/cert-generator/cert-generator.yaml
- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/controller/service.yaml
- manifests/v1beta1/components/controller/trial-templates.yaml
- manifests/v1beta1/components/db-manager/db-manager.yaml
- manifests/v1beta1/components/db-manager/service.yaml
- manifests/v1beta1/components/mysql/mysql.yaml
- manifests/v1beta1/components/mysql/service.yaml
- manifests/v1beta1/components/ui/service.yaml
- manifests/v1beta1/components/ui/ui.yaml
- pkg/controller.v1beta1/consts/const.go
See discussion: https://github.com/kubeflow/common/issues/148#issuecomment-893826133.
I modified labels for Katib components to follow Kubernetes guidelines.
Probably, we should also think about renaming [`katib-metricscollector-injection: enabled`](https://github.com/kubeflow/katib/blob/master/manifests/v1beta1/components/namespace/namespace.yaml#L6) to `katib.kubeflow.org/metricscollector-injection: true`
/cc @gaocegege @johnugeorge @alculquicondor
> Modify Labels for Katib Components

- pkg/metricscollector/v1beta1/common/pns.go
- pkg/metricscollector/v1beta1/common/pns.py
Fixes: https://github.com/kubeflow/katib/issues/1576.
This fix should help with the non-existing process error.
I noticed that other steps (`proc.Ppid()` and `proc.Cmdline()`) can also be failed.
I skipped error for them as well.
/cc @gaocegege @chenwenjun-github @johnugeorge
> Fix Metrics Collector error in case of non-existing Process

- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/suggestion/composer/composer_test.go
- pkg/controller.v1beta1/util/annotations.go
To be consistent with this PR: https://github.com/kubeflow/katib/pull/1611, we should also change our labels for Trials and Suggestion Deployment's Pod.
Please take a look @alculquicondor @gaocegege @johnugeorge 
/hold for the review
> Modify labels for controller resources

- examples/v1beta1/xgboost-lightgbm.yaml
- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/controller/rbac.yaml
- pkg/apis/controller/experiments/v1beta1/experiment_defaults.go
- pkg/controller.v1beta1/consts/const.go
Since we will release Kubeflow Training operator within Kubeflow 1.4, let's make appropriate change for XGBoost example in Katib.
/cc @kubeflow/wg-training-leads
> Modify XGBoostJob example for the new Controller

- cmd/suggestion/optuna/v1beta1/Dockerfile
- cmd/suggestion/optuna/v1beta1/main.py
- cmd/suggestion/optuna/v1beta1/requirements.txt
- examples/v1beta1/multivariate-tpe-example.yaml
- pkg/suggestion/v1beta1/optuna/service.py
- scripts/v1beta1/build.sh
- test/scripts/v1beta1/python-tests.sh
- test/suggestion/v1beta1/test_optuna_service.py
This PR proposes to add the suggestion service based on [Optuna](https://github.com/optuna/optuna). Optuna provides several sampling algorithms that have not been implemented in other suggestion services in Katib, such as **[multi-variate TPE](https://tech.preferred.jp/en/blog/multivariate-tpe-makes-optuna-even-more-powerful/)** and **[constant liar](https://nni.readthedocs.io/en/stable/CommunitySharings/ParallelizingTpeSearch.html)**.
In addition, as discussed in #1549, Optuna can offer the extension of **multi-objective optimization** when Katib supports that interface.
I've written the example of invoking multi-variate TPE in a [separated repository](https://github.com/g-votte/katib-optuna-example), so that we can test and discuss the new …
> Add Optuna based suggestion service

- pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
- pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-types.const.ts
- pkg/new-ui/v1beta1/frontend/src/app/enumerations/algorithms.enum.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
I updated Katib UI with Multivariate TPE Algorithm.
Also, I modified some Experiment parameters in create page.
/assign @c-bata @g-votte @kimwnasptd
> Add Multivariate TPE to Katib UI

- pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
- pkg/suggestion/v1beta1/goptuna/converter.go
- pkg/suggestion/v1beta1/optuna/service.py
- test/suggestion/v1beta1/test_optuna_service.py
See comment: https://github.com/kubeflow/katib/pull/1625#discussion_r690002871.
We should add algorithm settings to Katib UI.
Also, I renamed some algorithm settings to be consistent across different Frameworks.
I will create an issue to track other frameworks and algorithm settings.
/assign @g-votte @c-bata @gaocegege @johnugeorge
> Update Katib UI with Optuna Algorithm Settings

- .github/workflows/test-node.yaml
- Makefile
- pkg/new-ui/v1beta1/frontend/package-lock.json
- pkg/new-ui/v1beta1/frontend/package.json
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/setting/setting.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/early-stopping/early-stopping.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metadata/metadata.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-parameter/trial-parameter.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/details/experiment-details-tab.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/overview/experiment-overview.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph/d3.parcoords.js
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph/trials-graph.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/optimal-trial/utils.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
- pkg/new-ui/v1beta1/frontend/src/app/shared/params-list/add-modal/add-modal.component.html
What : 
It adds 'Prettier' as devDependency to `package.json` of 'new-ui/frontend' app.
Why :
Currently the style formatter 'Prettier' is not included in the `package.json`. Which makes the style formatting of 'new-ui/frontend' app on local dev environment depend on whether `Prettier` is installed globally on each developer's computer. It may confuse them while setting the IDE integration for style formatting.
Even though it's being checked on Github Actions, checking and fixing the style errors on Actions take way much longer than formatting on local with features of IDE such as 'auto format on save'.
So I suggest adding `Prettier` to the project's `package.json` so every developer can easily set the style formatting process on their local.
**Which …
> new-ui: Add devDependency - prettier

- hack/gen-python-sdk/post_gen.py
- hack/gen-python-sdk/swagger_config.json
- sdk/python/v1beta1/docs/KatibClient.md
- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
- sdk/python/v1beta1/kubeflow/katib/api_client.py
- sdk/python/v1beta1/kubeflow/katib/models/__init__.py
- sdk/python/v1beta1/kubeflow/katib/utils/utils.py
- change list_trials, list_experiments to return list of objects as a default
Fixes #1447
**Checklist:**
**Questions To Members**
- Is there any recommended way to add unit test codes for python sdk, except this [example notebook](https://github.com/kubeflow/katib/tree/master/examples/v1beta1/sdk)?
> SDK: change list apis to return objects as default

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
closes https://github.com/kubeflow/katib/issues/1620
This is also part of the 0.12 release effort https://github.com/kubeflow/katib/issues/1597
The UI should gracefully handle the case of missing TrialParameters. 
I changed the UI to use `yaml` input by default and if no TrialTemplates were found then the `ConfigMap` option would be disabled. If the TrialTemplates were fetched correctly, and are not an empty list, then the UI will select the `ConfigMap` option.
**Checklist:**
/cc @andreyvelich 
/assign @kimwnasptd
> UI: Handle missing TrialTemplates

- pkg/controller.v1beta1/experiment/experiment_controller_test.go
- pkg/controller.v1beta1/trial/trial_controller_test.go
- It might fix unit test fail issue described in #1649
#1649
**Checklist:**
> [bugfix]: increase test timeout

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/trial-template/trial-template.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
Cherry-pick changes from  #1652
/cc @andreyvelich
> cherry-pick: UI fix for handling missing params

- go.mod
- go.sum
- hack/mockgen.sh
- hack/update-mockgen.sh
- pkg/mock/v1beta1/api/earlystopping.go
- pkg/mock/v1beta1/api/suggestion.go
- pkg/mock/v1beta1/db/db.go
- pkg/mock/v1beta1/experiment/manifest/generator.go
- pkg/mock/v1beta1/experiment/suggestion/suggestion.go
- pkg/mock/v1beta1/suggestion/suggestionclient/suggestionclient.go
- pkg/mock/v1beta1/trial/managerclient/katibmanager.go
- pkg/mock/v1beta1/util/katibclient/katibclient.go
Fixes: https://github.com/kubeflow/katib/issues/1635.
I added v1.6.0 version for mockgen.
Also, I moved mockgen to hack, similar to Kubernetes: https://github.com/kubernetes/kubernetes/tree/master/hack.
Let's keep only user-facing scripts under `./scripts/v1beta1`
cc @gaocegege @johnugeorge
> Add mockgen version to gen script

- prow_config.yaml
We should trigger prow for changes in `pkg/cert-generator/v1beta1`.
/cc @tenzen-y
> Add Cert Generator to prow include dirs

- sdk/python/v1beta1/setup.py
We should update our SDK version to the latest in the `master` branch.
> Bump Katib Python SDK to 0.12.0rc1 version

- docs/developer-guide.md
We will change the minimal kubectl version in #1667. So, we should change the minimal kustomize version in the developer guide.
Ref:  
- [kubernetes v1.21 release note](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.21.md#kustomize-updates-in-kubectl)
- https://github.com/kubeflow/website/pull/2962#issuecomment-922973501
Fixes #
> Change the minimal kustomize version in the developer guide

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/algorithm/algorithm.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/hyper-parameters/hyper-parameters.component.ts
Signed-off-by: Jaeyeon Kim <anencore94@gmail.com>
Co-authored-by: Seongjin Kim <seongjinkim1123@gmail.com>
1) There was a bug when handling odd number of parameters with negative step. For above example, the number of combination should be `64`, not `-62`.
2) minor typo
Fixes #
**Checklist:**
> [bugfix]: absolute value and typo

- .github/workflows/test-python.yaml
- test/unit/v1beta1/requirements.txt
Fixes comments from this PR: https://github.com/kubeflow/katib/pull/1677#pullrequestreview-764891011.
/assign @anencore94 @gaocegege @johnugeorge
> Add Python test requirements file

- examples/v1beta1/fpga/OWNERS
- examples/v1beta1/fpga/README.md
- examples/v1beta1/fpga/xgboost-example.yaml
* Update the FPGA XGBoost experiment:
* use [InAccel FPGA Operator](https://artifacthub.io/packages/helm/inaccel/fpga-operator) (>=2.5) features
* Update AWS F1 instructions:
* from **InAccel EKS-optimized FPGA AMI** to **InAccel FPGA Operator**
> Update FPGA examples

- examples/v1beta1/README.md
- FIx the hyperlink for PytorchJob because [pytorch-operator](https://github.com/kubeflow/pytorch-operator) was integrated [tf-operator](https://github.com/kubeflow/tf-operator).
- Remove the description of how to access Katib UI for users using Kubernetes <= 1.9 because Katib supports Kubernetes >= 1.17.
Fixes #
> Fix readme in examples directory

- README.md
Change hyperlink for build status from travis ci to github actions.
Fixes #
/assign
/assign @andreyvelich @gaocegege @johnugeorge
> Fix hyperlink for build status

- cmd/metricscollector/v1beta1/file-metricscollector/main.go
- pkg/controller.v1beta1/experiment/manifest/generator_test.go
- pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
- pkg/new-ui/v1beta1/util.go
- pkg/ui/v1beta1/util.go
- pkg/util/v1beta1/katibconfig/config.go
- pkg/util/v1beta1/katibconfig/config_test.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
Implement some unit tests for the following functions in the katibconfig package since it has not been sufficiently tested. 
In addition, fix some mistyped comments and envtest for suggestion-controller.
Fixes #
Ref https://github.com/kubeflow/katib/issues/1680#issuecomment-930407734
/assign
/cc @andreyvelich
> Implement some unit tests for the katibconfig package

- pkg/db/v1beta1/mysql/mysql.go
close mysql statement and rows resources when sql exec end, reslove mysql statement leak
Fixes #1719 
**Checklist:**
> fix: close mysql statement and rows resources when sql exec end

- pkg/suggestion/v1beta1/skopt/base_service.py
> Fix same set for HyperParameters in Bayesian Optimization algorithm

- pkg/util/v1beta1/katibconfig/config.go
This PR: https://github.com/kubeflow/katib/pull/1564 allows user to nuke resource for Suggestion and Metrics Collector, but user has to set `limits` and `requests` as `-1` to nuke it.
For some use-cases, users want to remove only `limits` or `requests` for `resources`.
After this PR they can do it.
/assign @gaocegege @johnugeorge @sravi999 @tenzen-y @anencore94
> Allow to remove each resource in Katib config

- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
Hi, we experienced that the users tend to make mistakes like below when creating experiments using new UI (Thanks for the nice UI update!)
When users set parameter references in trial templates like below,
they need to enter the parameter reference as same as the hyperparameter defined in the experiment spec. 
The experiment is created without errors even if the users mistakenly set the wrong parameter reference.
I think it would be better to check the wrong parameter reference in the validating webhook
so that experiments are not created with the wrong parameter reference.
Please take a look, thanks!
> fix: check if parameter references exist in experiment parameters

- pkg/suggestion/v1beta1/chocolate/base_service.py
- pkg/suggestion/v1beta1/internal/search_space.py
Fixes: https://github.com/kubeflow/katib/issues/1636.
In Chocolate Suggestion [`quantized_uniform`](https://chocolate.readthedocs.io/en/latest/api/space.html#chocolate.quantized_uniform) distribution uses half-open interval.
/assign @tenzen-y @gaocegege @johnugeorge
> Fix Range for Int and Double values in Grid

- docs/proposals/metrics-collector.md
- examples/v1beta1/argo/README.md
- manifests/v1beta1/components/namespace/namespace.yaml
- manifests/v1beta1/components/webhook/webhooks.yaml
- operators/katib-controller/src/webhooks.yaml
- pkg/metricscollector/v1beta1/common/const.go
- pkg/webhook/v1beta1/common/const.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/pod/const.go
- pkg/webhook/v1beta1/pod/utils.go
Related: https://github.com/kubeflow/katib/issues/1622.
This PR changes label for Katib Metrics Collector injection to `katib.kubeflow.org/metrics-collector-injection: enabled`.
I will create PRs to fix profile controller and manifests.
/assign @gaocegege @alculquicondor @johnugeorge @tenzen-y
> Change namespace label for metrics collector injection

- examples/v1beta1/argo/README.md
Minor change. It's better to refer to the Argo Workflows subproject of Argo.
> docs: Argo -> Argo Workflows

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
Users don't need to check Kubeflow version by using `kfctl`.
I think Katib version should be enough for us.
Also, I added links to our docs and Slack channel to the issue config.
/assign @tenzen-y @gaocegege @johnugeorge
> Update links for issue template

- .github/workflows/test-charmed-katib.yaml
- operators/katib-controller/src/charm.py
- operators/katib-db-manager/src/charm.py
- operators/katib-ui/src/charm.py
- Handle status of operators only in set_pod_spec function.
- Centralize all the logic in set_pod_spec and add helper checks.
> Fix Status Handling in Charmed Operators

- pkg/metricscollector/v1beta1/common/const.go
Fixes: https://github.com/kubeflow/katib/issues/1754.
I fixed the default regex format.
I will create separate PR to update the website doc.
/assign @kubeflow/wg-automl-leads 
/cc @RDarrylR @anencore94
> Fix the default Metrics Collector regex

- operators/katib-controller/metadata.yaml
- operators/katib-db-manager/metadata.yaml
- operators/katib-ui/metadata.yaml
Charmed Katib CI is [failing](https://github.com/kubeflow/katib/runs/4447581111?check_suite_focus=true) due to recent changes in `juju bundle` as it no longer recognizes certain keys in `metadata.yaml`. This PR should prevent the following:
```
Error: YAML Error: unknown field `display-name`, expected one of `name`, `summary`, `description`, `maintainers`, `terms`, `subordinate`, `containers`, `resources`, `provides`, `requires`, `peer`, `storage`, `devices`, `extra-bindings`, `series` at line 2 column 1
```
> katib/operators: removes unrecognized keys from metadata.yaml

- cmd/db-manager/v1beta1/Dockerfile
- cmd/katib-controller/v1beta1/Dockerfile
- cmd/metricscollector/v1beta1/file-metricscollector/Dockerfile
- cmd/new-ui/v1beta1/Dockerfile
- cmd/suggestion/goptuna/v1beta1/Dockerfile
- cmd/ui/v1beta1/Dockerfile
Bump `alpine` version to 3.15 since `musl` and `musl-utils` in `alpine:3.7` have a vulnerability with a CVSS score of 9.8.
ref: https://nvd.nist.gov/vuln/detail/cve-2019-14697
Fixes #1775 
**Checklist:**
> Bump `alpine` version to 3.15

- cmd/db-manager/v1beta1/Dockerfile
- cmd/suggestion/chocolate/v1beta1/Dockerfile
- cmd/suggestion/goptuna/v1beta1/Dockerfile
- cmd/suggestion/hyperband/v1beta1/Dockerfile
- cmd/suggestion/hyperopt/v1beta1/Dockerfile
- cmd/suggestion/nas/darts/v1beta1/Dockerfile
- cmd/suggestion/nas/enas/v1beta1/Dockerfile
- cmd/suggestion/optuna/v1beta1/Dockerfile
- cmd/suggestion/skopt/v1beta1/Dockerfile
Bump `grpc_health_probe` version to v0.4.6 since `golang.org/x/text` v0.3.2, on which `grpc_health_probe` v0.3.1 depends, has a vulnerability with a CVSS score of 7.5.
```shell
$ trivy image --severity HIGH,CRITICAL,MEDIUM,LOW kubeflowkatib/katib-db-manager:v1beta1-fa1babe
2022-01-16T21:29:40.788+0900    INFO    Detected OS: alpine
2022-01-16T21:29:40.788+0900    INFO    Detecting Alpine vulnerabilities...
2022-01-16T21:29:40.790+0900    INFO    Number of language-specific files: 2
2022-01-16T21:29:40.790+0900    INFO    Detecting gobinary vulnerabilities...
kubeflowkatib/katib-db-manager:v1beta1-fa1babe (alpine 3.15.0)
==============================================================
Total: 0 (LOW: 0, MEDIUM: 0, HIGH: 0, CRITICAL: 0) …
```
> Bump grpc_health_probe version to v0.4.6

- pkg/apis/manager/README.md
Fix a link for GRPC API documentation since we have removed outdated API Reference from the website in https://github.com/kubeflow/website/pull/3080
Fixes #
**Checklist:**
> Fix a link for GRPC API documentation

- Makefile
- scripts/v1beta1/build.sh
After this PR: https://github.com/kubeflow/katib/pull/1731, we should add `CPU_ARCH` to our push-tag and push-latest instructions to run our release script.
/assign @tenzen-y @gaocegege @johnugeorge
> Add CPU architecture to release scripts

- sdk/python/v1beta1/setup.py
We should update our SDK version to the latest in the `master` branch.
/assign @gaocegege @tenzen-y @johnugeorge
> Bump Katib Python SDK to 0.13.0rc0 version

- test/e2e/v1beta1/argo_workflow.py
I added Kubernetes version to our AWS CI.
We should be able to use this env: https://github.com/kubeflow/testing/blob/master/images/aws-scripts/create-eks-cluster.sh#L29
> Add Kubernetes version to AWS CI

- operators/katib-controller/metadata.yaml
- operators/katib-db-manager/metadata.yaml
- operators/katib-ui/metadata.yaml
This PR addresses https://github.com/canonical/bundle-kubeflow/issues/425 where a PVC is created per operator, adding the `min-juju-version: 2.9.0` element to prevent that PVC creation.
Fixes #425
https://github.com/canonical/bundle-kubeflow/issues/425 
**Checklist:**
No user facing changes required
> Add min-juju-version element to operators prevent excess PVC creation

- docs/proposals/metrics-collector.md
- docs/proposals/trial-custom-crd.md
- examples/v1beta1/kubeflow-training-operator/mxjob-byteps.yaml
- pkg/apis/controller/experiments/v1beta1/constants.go
- pkg/ui/v1beta1/frontend/src/reducers/general.js
- test/e2e/v1beta1/argo_workflow.py
- test/e2e/v1beta1/scripts/setup-katib.sh
This PR fixes the default label for Kubeflow Training Operators.
After this we should be able to run E2E Kubeflow example: https://github.com/kubeflow/katib/blob/master/examples/v1beta1/kubeflow-pipelines/kubeflow-e2e-mnist.ipynb.
We have to cherry pick this change on `release-0.13` branch and make the new RC.
/assign @kimwnasptd @tenzen-y @gaocegege @johnugeorge
> Fix default label for Training Operators

- docs/proposals/metrics-collector.md
- docs/proposals/trial-custom-crd.md
- examples/v1beta1/kubeflow-training-operator/mxjob-byteps.yaml
- pkg/apis/controller/experiments/v1beta1/constants.go
- pkg/ui/v1beta1/frontend/src/reducers/general.js
- test/e2e/v1beta1/argo_workflow.py
- test/e2e/v1beta1/scripts/setup-katib.sh
This is cherry pick for https://github.com/kubeflow/katib/pull/1808 on `release-0.13` branch.
/cc @johnugeorge @tenzen-y
> Automated cherry pick of #1808: Fix default label for Training Operators on release-0.13

- sdk/python/v1beta1/setup.py
We should update our SDK version to the latest in the master branch.
Related: https://github.com/kubeflow/katib/issues/1774
/assign @gaocegege @tenzen-y @johnugeorge
> Bump Katib Python SDK to 0.13.0rc1 version

- CHANGELOG.md
I updated Changelog for Katib 0.13.0-rc.1 release.
Related: https://github.com/kubeflow/katib/issues/1774.
/assign @johnugeorge @gaocegege @tenzen-y
> Update Changelog for Katib v0.13.0-rc.1 release

- OWNERS
I propose to add @anencore94 and @tenzen-y to Katib reviewers since they are very active with PRs and issues resolving.
That will automatically assign more reviewers to created PRs.
Thank you so much for your help with Katib project!
/assign @kubeflow/wg-automl-leads
> Add more reviewers to Katib OWNERS

- pkg/apis/manager/v1beta1/gen-doc/Dockerfile
- pkg/apis/manager/v1beta1/gen-doc/api.md
I fix the Dockerfile for API documentation generation since the base image of `pseudomuto/protoc-gen-doc` has been changed from `debian:jessie-slim` to `alpine:3.15.0` in v1.5.1.
Ref: https://github.com/pseudomuto/protoc-gen-doc/blob/v1.5.1/Dockerfile#L1
Fixes #
**Checklist:**
> Fix the Dockerfile for API documentation generation

- .github/workflows/test-charmed-katib.yaml
- operators/katib-controller/src/charm.py
- operators/katib-db-manager/src/charm.py
- operators/katib-ui/src/charm.py
Black is broken due to a change in the click dependency and is fixed in version 22.3.0.  Here is a link to the [related issue](https://github.com/psf/black/issues/2964)
**Checklist:**
> Upgrade Black to fix linting

- examples/v1beta1/fpga/README.md
**What this PR does**:
* Set `kube-system` as the suggested (InAccel FPGA Operator) namespace
* Replace broken link
The new link points to a MicroK8s + InAccel + Katib [tutorial](https://ubuntu.com/tutorials/accelerated-ml-experiments-on-microk8s-with-inaccel-fpga-operator-and-kubeflow-katib).
> Fix the FPGA examples documentation

- pkg/controller.v1beta1/experiment/experiment_controller.go
- pkg/controller.v1beta1/experiment/experiment_controller_test.go
Please see #1830
Fixes #1830 
**Checklist:**
> Reconcile trial assignments by comparing suggestion and trials being executed

- pkg/controller.v1beta1/consts/const.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
This PR fixes validation of Experiment when trial metadata used in template substitution.
Validator should not look for parameter in the spec.parameters if it is trial's metadata.
Fixes #1844
> Don't check if trial's metadata is in spec.parameters 

- cmd/suggestion/optuna/v1beta1/requirements.txt
This PR introduces an upper version constraint for Optuna.
Please refer to #1851 for the background.
Related #1851 
**Checklist:**
> Set upper constraint for Optuna

- operators/katib-controller/charmcraft.yaml
- operators/katib-db-manager/charmcraft.yaml
- operators/katib-ui/charmcraft.yaml
Due to pypa/setuptools_scm#713, we are experiencing errors when building charms both locally and in the CI. This change will prevent the error from happening until the issue is fixed.
This PR fixes the CI errors reported in #1866
> operators/katib-*: pins pip and setuptools versions to avoid installation issues

- examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
It seems that `mxnet/python:latest_cpu_native_py3` image has been deleted from [upstream dockerhub](https://hub.docker.com/r/mxnet/python/tags). 
As a result, our suite test can no longer be run as shown below, so I changed the base image from `mxnet/python:latest_cpu_native_py3` to `python:3.9`.
> error building image: GET https://index.docker.io/v2/mxnet/python/manifests/latest_cpu_native_py3: MANIFEST_UNKNOWN: manifest unknown; unknown tag=latest_cpu_native_py3
[Argo Workflow Logs](https://argo.kubeflow-testing.com/workflows/kubeflow-test-infra/kubeflow-katib-presubmit-e2e-v1beta1-1833-c56b348-2224-eb75?tab=workflow&nodeId=kubeflow-katib-presubmit-e2e-v1beta1-1833-c56b348-2224-eb75-1092086686&sidePanel=logs%3Akubeflow-katib-presubmit-e2e-v1beta1-1 …
> Fix kubeflowkatib/mxnet-mnist image

- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
Please see https://github.com/kubeflow/katib/issues/1873 for detailed explanation
Fixes #1873 
**Checklist:**
> additional metric names should not include objective metric name

- cmd/db-manager/v1beta1/Dockerfile
- cmd/katib-controller/v1beta1/Dockerfile
- cmd/suggestion/chocolate/v1beta1/Dockerfile
- cmd/suggestion/goptuna/v1beta1/Dockerfile
- cmd/suggestion/hyperband/v1beta1/Dockerfile
- cmd/suggestion/hyperopt/v1beta1/Dockerfile
- cmd/suggestion/nas/darts/v1beta1/Dockerfile
- cmd/suggestion/nas/enas/v1beta1/Dockerfile
- cmd/suggestion/optuna/v1beta1/Dockerfile
- cmd/suggestion/skopt/v1beta1/Dockerfile
- examples/v1beta1/kubeflow-training-operator/tfjob-mnist-with-summaries.yaml
I upgraded the grpc_health_probe version to v0.4.11 to resolve security vulnerability [CVE-2022-27191](https://nvd.nist.gov/vuln/detail/CVE-2022-27191).
Also, I added the primaryPodLabels to tfjob's example.
```shell
$ trivy image --severity CRITICAL,HIGH docker.io/kubeflowkatib/katib-db-manager:latest
2022-05-25T23:37:21.684+0900	INFO	Detected OS: alpine
2022-05-25T23:37:21.684+0900	INFO	Detecting Alpine vulnerabilities...
2022-05-25T23:37:21.685+0900	INFO	Number of language-specific files: 2
2022-05-25T23:37:21.685+0900	INFO	Detecting gobinary vulnerabilities...
docker.io/kubeflowkatib/katib-db-manager:latest (alpine 3.15.4)
Total: 0 (HIGH: 0, CRITICAL: 0)
app/katib-db-manager (gobinary)
Total: 0 (HIGH: 0, CRITICAL: 0)
bin/grpc_health_probe …
```
> Upgrade the grpc_health_probe version to v0.4.11 to resolve security vulnerability CVE-2022-27191

- cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/chocolate/v1beta1/Dockerfile
- cmd/suggestion/chocolate/v1beta1/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/Dockerfile
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
- examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
- examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
- examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
I upgraded the TensorFlow version to address some security issues.
Also, I modified the sample code for ENAS to work in Tensorflow 2.9.1 env.
Fixes #
**Checklist:**
> Upgrade the Tensorflow version to address some security issues

- Makefile
I fixed `HAS_SHELLCHECK` and `HAS_SETUP_ENVTEST` in Makefile to resolve `"make: command: Command not found"` errors reported in https://github.com/kubeflow/katib/pull/1882#discussion_r889232351.
/assign @johnugeorge 
Fixes #
**Checklist:**
> Fix `HAS_SHELLCHECK` and `HAS_SETUP_ENVTEST` in Makefile

- Makefile
- examples/v1beta1/kind-cluster/deploy.sh
- hack/verify-gofmt.sh
- hack/verify-golangci-lint.sh
- hack/verify-shellcheck.sh
To avoid the `make: command: Command not found` error, I have added `-v` option when using the `command` command in https://github.com/kubeflow/katib/pull/1884, although we received the same error message again.
> Run go mod download
make: command: Command not found
make: command: Command not found
make: command: Command not found
go generate ./pkg/... ./cmd/...
Generate deepcopy, clientset, listers, informers for the APIs
https://github.com/kubeflow/katib/runs/6736557128?check_suite_focus=true#step:5:10
According to this StackOverflow comment, we need to add a semicolon when using the `command` command on the Ubuntu machine.
> you must have a version of GNU make pre 4.3, that doesn't realize command is a shell built-in. You can force it by adding a …
> Add semicolon when using `command` command in Makefile

- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
I upgraded the tensorflow-aarch64 version to v2.9.1.
Ref: https://pypi.org/project/tensorflow-aarch64/2.9.1/
Fixes #
**Checklist:**
> Upgrade tensorflow-aarch64 version to v2.9.1

- ADOPTERS.md
I added CyberAgent to `ADOPTERS.md`.
Fixes #
**Checklist:**
> Add CyberAgent to adopters

- .github/workflows/lint.yaml
- .github/workflows/test-charmed-katib.yaml
- Makefile
- hack/verify-yamllint.sh
This PR verifies the format of YAML files in this repo using yamllint as discussed in https://github.com/kubeflow/katib/issues/1734#issuecomment-972703530 and #1859
Fixes #1859
**Checklist:**
> Linting for K8s YAML files

- cmd/new-ui/v1beta1/main.go
- pkg/new-ui/v1beta1/backend.go
- pkg/new-ui/v1beta1/frontend/src/app/app-routing.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/app.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/models/trial.k8s.model.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/metrics/metrics.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/metrics/metrics.component.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/metrics/metrics.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/metrics/metrics.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/trial-modal-overview.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/trial-modal-overview.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/trial-modal-overview.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/overview/trial-modal-overview.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.component.scss
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trials-table.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
This PR implements a distinct page for each Trial, as discussed in https://github.com/kubeflow/katib/issues/1763.
It adds an `OVERVIEW` tab to the Trial page to show Trial name, status, performance, and conditions.
The plan is to add additional tabs, such as `LOGS` (https://github.com/kubeflow/katib/issues/971, https://github.com/kubeflow/katib/issues/1764), `DETAILS` and `YAML` to show full information about a trial.
**Which issue(s) this PR fixes** 
Fixes https://github.com/kubeflow/katib/issues/1763
> Distinct page for each Trial in the UI

- pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-settings.const.ts
- pkg/new-ui/v1beta1/frontend/src/app/constants/algorithms-types.const.ts
- pkg/new-ui/v1beta1/frontend/src/app/enumerations/algorithms.enum.ts
This PR adds PBT as an option to the search algorithms drop-down for creating a new experiment from the Katib UI.
Related to: https://github.com/kubeflow/katib/issues/1382, https://github.com/kubeflow/katib/pull/1862
**Checklist:**
- [-] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing
> Add PBT to experiment creation form

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Signed-off-by: Jaeyeon Kim <anencore94@gmail.com>
- To fix sdk's bug which is unavailable to list trials filter by experiment's name.
- It was broken not from #1630. The condition was broken from the first time at #1177. It didn't cover the case when `name` was not given.
Fixes #1919
**Checklist:**
> [hotfix]: filter by name of experiment

- pkg/suggestion/v1beta1/optuna/base_service.py
- pkg/suggestion/v1beta1/optuna/service.py
- test/unit/v1beta1/suggestion/test_optuna_service.py
I implemented validation for optuna suggestion service. With that, I separated the processes to call optuna as `base_service.py` like other suggestion services.
Part-of: #1126 
**Checklist:**
> Implement validation for optuna suggestion service

- pkg/suggestion/v1beta1/nas/common/validation.py
- pkg/suggestion/v1beta1/nas/darts/README.md
- pkg/suggestion/v1beta1/nas/darts/service.py
- pkg/suggestion/v1beta1/nas/enas/service.py
- test/unit/v1beta1/suggestion/test_darts_service.py
- test/unit/v1beta1/suggestion/test_enas_service.py
- test/unit/v1beta1/suggestion/test_nas_common.py
I implemented validations for the darts suggestion service.
Also, I commonized a function to validate NAS operations as [`pkg/suggestion/v1beta1/nas/common/validate.py`](https://github.com/tenzen-y/katib/blob/5ab03be72cebe624d57fb6a4b9e5599258053a51/pkg/suggestion/v1beta1/nas/common/validation.py).
Part-of #1126 
**Checklist:**
> Implement validations for darts suggestion service

- CHANGELOG.md
Update changelog for Katib v0.14.0 release
> Update CHANGELOG for v0.14.0 release

- .github/workflows/template-setup-e2e-test/action.yaml
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
I added validation webhooks for maxFailedTrialCount and parallelTrialCount.
Also, I upgraded the Go version in e2e tests.
Fixes #
**Checklist:**
> Add validation webhooks for maxFailedTrialCount and parallelTrialCount

- cmd/db-manager/v1beta1/Dockerfile
- cmd/db-manager/v1beta1/main.go
- docs/developer-guide.md
- pkg/db/v1beta1/common/const.go
- pkg/db/v1beta1/db.go
- pkg/db/v1beta1/mysql/mysql.go
- pkg/db/v1beta1/postgres/postgres.go
I added a flag, `--connect-timeout`, to katib-db-manager that sets the time before calling an error on database connection and remove the non-configurable flag, `-w kubernetes`, set in katib-db-manager Dockerfile.
Also, I fixed a process to set PostgreSQL Database.
Fixes #1928 
**Checklist:**
> Add --connect-timeout flag to katib-db-manager

- examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
- examples/v1beta1/trial-images/mxnet-mnist/install-arm-performance-libraries.sh
- scripts/v1beta1/build.sh
I modified Dockerfile for mxnet-mnist to support arm64. Also, I upgraded mxnet version to v1.9.1.
I have tested using the following commands:
```shell
$ # For linux/amd64
$ docker run -it --pull always --platform=linux/amd64 ytenzen/multiplatform-mxnet:latest
$ # For linux/arm64
$ docker run -it --pull always --platform=linux/arm64 ytenzen/multiplatform-mxnet:latest
```
Part-of #1900
**Checklist:**
> Support for arm64 in mxnet-mnist image

- examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
- scripts/v1beta1/build.sh
I modified Dockerfile for pytorch-mnist to support arm64. 
Also, I have tested using the following commands:
```shell
$ # For linux/arm64 with cuda
$ docker run -it --pull always --platform linux/arm64 ytenzen/multiplatform-pytorch-gpu:latest --epochs=1 --batch-size=256
$ # For linux/amd64 with cuda
$ docker run -it --pull always --platform linux/amd64 ytenzen/multiplatform-pytorch-gpu:latest --epochs=1 --batch-size=256
$ # For linux/arm64
$ docker run -it --pull always --platform linux/arm64 ytenzen/multiplatform-pytorch-cpu:latest --epochs=1 --batch-size=256
$ # For linux/amd64
$ docker run -it --pull always --platform linux/amd64 ytenzen/multiplatform-pytorch-cpu:latest --epochs=1 --batch-size=256
```
/hold until #1940 is merged
**Which issue(s) …
> Support for arm64 in pytorch-mnist image

- examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
- examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
- examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
- scripts/v1beta1/build.sh
I modified Dockerfile for enas-cnn-cifar10 image to support arm64 and I tested operations  in the below commands:
```shell
$ # For arm64
$ docker run -it --platform linux/arm64 ytenzen/multiplatform-enas-cnn-cifar10-gpu:latest  --num_gpus=0 --num_epochs=1 --architecture="[[49]]" --nn_config="{'num_layers': 1, 'input_sizes': [32, 32, 3], 'output_sizes': [10], 'embedding': {'49': {'opt_id': 49, 'opt_type': 'separable_convolution', 'opt_params': {'filter_size': '3', 'num_filter': '128', 'stride': '2', 'depth_multiplier': '2'}}}}"
$ # For amd64
$ docker run -it --platform linux/amd64 ytenzen/multiplatform-enas-cnn-cifar10-gpu:latest  --num_gpus=0 --num_epochs=1 --architecture="[[49]]" …
```
> Support for arm64 in enas-cnn-cifar10 image

- examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
- scripts/v1beta1/build.sh
I modified Dockerfile for darts-cnn-cifar10 to support arm64 and I have tested in the below commands:
- linux/arm64 with GPU support
```shell
docker run -it --platform linux/arm64 ytenzen/multiplatform-darts-cnn-cifar10-gpu:latest --algorithm-settings="{'num_epochs': '1', 'w_lr': 0.025, 'w_lr_min': 0.001, 'w_momentum': 0.9, 'w_weight_decay': 0.0003, 'w_grad_clip': 5.0, 'alpha_lr': 0.0003, 'alpha_weight_decay': 0.001, 'batch_size': 128, 'num_workers': 0, 'init_channels': '1', 'print_step': 50, 'num_nodes': '1', 'stem_multiplier': '1'}" --search-space="['max_pooling_3x3']" --num-layers="1"
```
- linux/arm64 with CPU support
```shell
docker run -it --platform linux/arm64 …
```
> Support arm64 in darts-cnn-cifar10 image

- scripts/v1beta1/build.sh
I modified the Dockerfile for simple-pbt to support arm64 and I have tested on my local using the below commands:
- linux/arm64
```shell
docker run -it --platform linux/arm64 ytenzen/multiplatform-simple-pbt:latest --epochs=10
```
- linux/amd64
```shell
docker run -it --platform linux/amd64 ytenzen/multiplatform-simple-pbt:latest --epochs=10
```
Part-of #1900 
**Checklist:**
> Support for arm64 in simple-pbt image

- .github/workflows/build-and-publish-images.yaml
- .github/workflows/lint.yaml
- .github/workflows/publish-algorithm-images.yaml
- .github/workflows/publish-core-images.yaml
- .github/workflows/publish-trial-images.yaml
- .github/workflows/template-e2e-test/action.yaml
- .github/workflows/template-publish-image/action.yaml
- .github/workflows/template-setup-e2e-test/action.yaml
I added the CI to build multi-platform container images using composite action and reusable workflows.
Also, I cleaned up config files for actions according to the below documents.
- https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
- https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
Fixes #1900 
**Checklist:**
> Add the CI to build multi-platform container images

- examples/v1beta1/trial-images/simple-pbt/pbt_test.py
I added the license to PBT.
Fixes #
**Checklist:**
> Add the license to pbt

- pkg/new-ui/v1beta1/hp.go
Added some additional logging that was needed when troubleshooting a customer issue. It was possible to get into a state where the API was not responding and you couldn't tell if it was the underlying controller of the web API.
- Log start to command with experiment name and namespace (best practice - let's you know the call was make before possible errors)
- Log count of trials in case something goes wrong with processing.
> Improve UI API/controller logging to ease troubleshooting

- sdk/python/v1beta1/kubeflow/katib/constants/constants.py
I think, we should remove Final keyword from our constants in Python SDK.
Final is available only in >= Python 3.8 version: https://peps.python.org/pep-0591/
Currently, we say that [Katib SDK is supported in Python 3 and 3.7](https://github.pie.apple.com/kubeflow-oss/katib/blob/master/sdk/python/v1beta1/setup.py#L42-L47).
Also, it's better to be compatible with other Kubeflow components SDKs, [e.g. with Kubeflow Pipelines](https://github.com/kubeflow/pipelines/blob/master/sdk/python/setup.py#L85-L87).
We can think about Python upgrade in the future releases/versions across various Kubeflow components.
> [SDK] Remove Final Keyword from constants

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
We should send `namespace` parameter to `create_experiment` API, so user can set it using `tune` API.
cc @tenzen-y @johnugeorge @anencore94
> [SDK] Fix namespace parameter in tune API

- examples/v1beta1/trial-images/simple-pbt/README.md
- examples/v1beta1/trial-images/simple-pbt/pbt_test.py
As discussed in [this](https://github.com/kubeflow/katib/pull/1958#issuecomment-1261588102), I added the documentation for the simple-pbt example.
cc: @a9p @gaocegege 
Fixes #
**Checklist:**
> Add the documentation for simple-pbt

- cmd/new-ui/v1beta1/Dockerfile
- pkg/new-ui/v1beta1/README.md
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.module.ts
In this PR:
* Add a top row toolbar with the title of the app and the button to create a new Experiment.
* Replace the card with a responsive table that shows the items. The component also has a paginator.
* Update `Dockerfile` and `README` file to check out to the commit in master branch from the Kubeflow repository that includes the corresponding changes.
Here the new look of the app:
Related PR: https://github.com/kubeflow/kubeflow/pull/6316
> UI: Make KWA's main table responsive and add toolbar

- Makefile
- cmd/katib-controller/v1beta1/main.go
- cmd/metricscollector/v1beta1/file-metricscollector/main.go
- docs/developer-guide.md
- examples/v1beta1/trial-images/simple-pbt/README.md
- go.mod
- hack/verify-golangci-lint.sh
- pkg/client/controller/clientset/versioned/fake/register.go
- pkg/client/controller/clientset/versioned/scheme/register.go
- pkg/metricscollector/v1beta1/common/pns.go
- pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
- pkg/new-ui/v1beta1/backend.go
- pkg/ui/v1beta1/backend.go
- test/e2e/v1beta1/hack/aws/run-e2e-experiment.go
- test/e2e/v1beta1/hack/gh-actions/run-e2e-experiment.go
I upgraded Go version to v1.19.
Fixes #
**Checklist:**
> [chore] Upgrade Go version to v1.19

- pkg/new-ui/v1beta1/hp.go
In this PR, we move the status column to the first position of the trials table as it is in the other tables.
Here's a screenshot:
> [kwa-show-status-first] Show the trials table's status column first

- .github/workflows/build-and-publish-images.yaml
- .github/workflows/darts-cifar10-e2e-test.yaml
- .github/workflows/enas-cifar10-e2e-test.yaml
- .github/workflows/katib-ui-e2e-test.yaml
- .github/workflows/lint.yaml
- .github/workflows/mxnet-mnist-e2e-test.yaml
- .github/workflows/pytorch-mnist-e2e-test.yaml
- .github/workflows/simple-pbt-e2e-test.yaml
- .github/workflows/template-publish-image/action.yaml
- .github/workflows/test-charmed-katib.yaml
- .github/workflows/test-go.yaml
- .github/workflows/test-node.yaml
- .github/workflows/test-python.yaml
- .github/workflows/test-shell-script.yaml
- .github/workflows/tf-mnist-with-summaries-e2e-test.yaml
To resolve the following warning, I upgraded docker/metadata-action to v4, actions/checkout to v3, and actions/setup-python to v4.
```shell
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, docker/metadata-action, actions/checkout
```
```shell
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, …
```
> [chore] Upgrade docker/metadata-action, actions/checkout, and actions/setup-python version

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
In this PR, we rename the `Age` header of app's main table to `Created at` and right align it.
Related PR: https://github.com/kubeflow/kubeflow/pull/6694
> UI: Rename and right align the age column

- cmd/metricscollector/v1beta1/file-metricscollector/main.go
The GetMainProcesses function expects the directory for completed marker, e.g.  `/var/log/katib`:
https://github.com/kubeflow/katib/blob/master/pkg/metricscollector/v1beta1/common/pns.go#L94
The current code will pass the entire log file i.e `/var/log/katib/metrics.log`. When there is only single container, this code path will work since if will assign the first non-0 pid as main process. However, when multiple sidecar containers presented this method will break.
Fixes #
**Checklist:**
> Fix main process retrieve logic for early stopping

- docs/presentations.md
I've added more Katib Presentations from 2022.
Also, I've added "Event" column to the table, so we can identify the talk source easier.
Please take a look @terrytangyuan @johnugeorge @tenzen-y @kubeflow/wg-training-leads @kubeflow/wg-automl-leads
> Add More Katib Presentations 2022

- .github/workflows/darts-cifar10-e2e-test.yaml
- .github/workflows/enas-cifar10-e2e-test.yaml
- .github/workflows/mxnet-mnist-e2e-test.yaml
- .github/workflows/publish-algorithm-images.yaml
- .github/workflows/publish-core-images.yaml
- .github/workflows/publish-katib-ui-image.yaml
- .github/workflows/publish-trial-images.yaml
- .github/workflows/pytorch-mnist-e2e-test.yaml
- .github/workflows/simple-pbt-e2e-test.yaml
- .github/workflows/test-charmed-katib.yaml
- .github/workflows/test-go.yaml
- .github/workflows/test-node.yaml
- .github/workflows/test-python.yaml
- .github/workflows/test-shell-script.yaml
- .github/workflows/tf-mnist-with-summaries-e2e-test.yaml
- pkg/new-ui/v1beta1/frontend/package.json
This is a follow up PR to this https://github.com/kubeflow/katib/pull/1977. Here, we extend the GH action [Frontend Test](https://github.com/kubeflow/katib/blob/master/.github/workflows/test-node.yaml) to include a job that runs KWA frontend unit tests as well. This also is needed before this PR https://github.com/kubeflow/katib/pull/1991#issuecomment-1301793351 is merged to ensure that nothing breaks.
> gh-actions: Extend action to run Frontend Unit tests

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.scss
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/kfp-run/kfp-run.component.ts
In this PR:
- Introduce the `kfp-run` component as a distinct component.
- Make the pipeline button a link.
Here's a screenshot:
> [kwa-kfp-component] Introduce KWA's frontend component for kfp links

- pkg/new-ui/v1beta1/frontend/src/app/app-routing.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-modal/trial-modal.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
Fix 500 error when refreshing KWA's detail page by also adding the namespace variable as a query parameter to the route.
Related issue: https://github.com/kubeflow/katib/issues/1967
> frontend: Fix 500 error after detail page refresh (#1967)

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/experiment-creation.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/metrics-collector/metrics-collector.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/yaml-modal/yaml-modal.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/experiment-form.service.ts
While looking at the integration of our previous YAML editor (`ace-editor`), we found out that we do not take the appropriate actions in order to pass the `customYaml` input as part of the form it is in.
**Steps to reproduce the issue:**
* Write any kind of input in `Metrics Collector` > `Kind: Custom` > `Editor`
* Click `Create` or `Edit and Submit YAML`
An error will come up since we haven't set up properly a new experiment but if in our browser we use `Inspect` > `Network (tab)` > `create_experiment` > `postData` > `spec`. We can see `metricsCollectorSpec` > `source` hasn't any updated data in the section below:
(https://github.com/kubeflow/katib/blob/master/examples/v1beta1/metrics-collector/custom-metrics-collector.yaml#L18-L35)
```
collector:
kind: Custom
customCollector:
args:
- -m …
```
> [bugfix] Fix value passing bug in New Experiment form

- cmd/new-ui/v1beta1/main.go
- pkg/controller.v1beta1/consts/const.go
- pkg/new-ui/v1beta1/README.md
- pkg/new-ui/v1beta1/authzn.go
- pkg/new-ui/v1beta1/backend.go
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
- pkg/new-ui/v1beta1/hp.go
- pkg/new-ui/v1beta1/types.go
- pkg/new-ui/v1beta1/util.go
The current backend for the new UI does not perform any authorization checks. It should comply with the authz guidelines (https://github.com/kubeflow/kubeflow/issues/5566) and use `SubjectAccessReviews` (SAR) to check if a user has permissions to perform an action.
This PR:
- introduces authz checks for actions on:
- `Trials`
- `Experiments`
- `TrialTemplates`
- introduces three ENV variables:
- `APP_DISABLE_AUTH`: Skip authorization if an admin is explicitly requested it.
- `BACKEND_MODE`: dev or prod mode. Skip authorization when in dev mode.
- `USERID_HEADER`: to check and ensure that a username is provided into the header of every http request towards the api-server.
Before any request proceed to K8s api-server:
* check if authorization must be …
> Add authorization mechanisms in new Katib UI backend

- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/controller.v1beta1/suggestion/composer/composer_test.go
- pkg/util/v1beta1/katibconfig/config.go
- pkg/util/v1beta1/katibconfig/config_test.go
> add resources to earlystopping container

- pkg/controller.v1beta1/consts/const.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
- pkg/webhook/v1beta1/pod/utils.go
As we discussed on the recent AutoML WG meeting, we should add Trial labels to the pod during mutation.
We need it to get Trial logs from the Katib UI backend: https://github.com/kubeflow/katib/pull/2039.
cc @kimwnasptd @johnugeorge @tenzen-y @d-gol
> Add Trial Labels During Pod Mutation

- pkg/apis/controller/trials/v1beta1/util.go
- pkg/controller.v1beta1/experiment/experiment_controller.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
- pkg/controller.v1beta1/trial/trial_controller_util.go
- pkg/suggestion/v1beta1/internal/trial.py
- pkg/suggestion/v1beta1/skopt/base_service.py
Python suggestion services will convert the trials from request payload before passing in actual search algos. However, early stopped trials are filtered out in this process and thus no updates are provided to search algo and there are duplicated trials created.
Fixes #
https://github.com/kubeflow/katib/issues/2002
**Checklist:**
> [Fix] add early stopped trials in converter

- docs/developer-guide.md
- pkg/cert-generator/v1beta1/consts/const.go
- pkg/cert-generator/v1beta1/generate/generate.go
- pkg/cert-generator/v1beta1/generate/generate_test.go
I removed Certificate Chain from our Cert generator.
I think having chain is not necessary for Kubernetes Webhooks. I was able to create Katib Experiments in my environment with these changes.
Also, we can leave only Full Service Domain in our DNS names.
Do you have any objections @tenzen-y @johnugeorge @shaowei-su ?
> Remove Certificate Chain from Cert Generator

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
This PR enables sorting in KWA's main table based on the following columns:
- Status
- Name
- Created at
- Successful trials
- Running trials
- Failed trials
Here's a screenshot of the app:
I marked this PR as `WIP` since I couldn't build an image and tested in my cluster because of the bug reported here: https://github.com/kubeflow/katib/issues/2016 
Update: Managed to build an image and tested in my cluster. It worked as expected!
Related PRs: https://github.com/kubeflow/kubeflow/pull/6742
> frontend: Enable sorting in KWA's main table

- sdk/python/v1beta1/.gitignore
- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
- sdk/python/v1beta1/kubeflow/katib/constants/constants.py
- sdk/python/v1beta1/setup.py
Related: https://github.com/kubeflow/katib/issues/2022.
I've added API to get Trial metrics from the Katib DB using Katib DB Manager gRPC API.
Usage:
```python
cl = KatibClient()
trial_name = cl.get_experiment(name="test-experiment-1")["status"]["succeededTrialList"][0]
cl.get_trial_metrics(name=trial_name)[0]
"
time_stamp: "2022-12-05T14:42:08Z"
metric {
name: "Train-accuracy"
value: "0.112390"
}
"
```
Since we don't publish our gRPC as Python package, we can't modify [the requirements for our Katib SDK](https://github.com/andreyvelich/katib/blob/b6755bbdc4d73eee18f8025c0bc68b5d90c8747b/sdk/python/v1beta1/setup.py#L19-L26).
In the `setup.py` script [I copied the Katib gRPC APIs file to the appropriate location](https://github.com/kubeflow/katib/blob/b6755bbdc4d73eee18f8025c0bc68b5d90c8747 …
> [SDK] Get Trial Metrics from Katib DB

- .github/workflows/template-setup-e2e-test/action.yaml
I upgraded the [`actions-setup-minikube`](https://github.com/manusa/actions-setup-minikube) version to v2.7.2 to resolve the following error:
> stderr:
time="2022-12-14T13:37:48Z" level=fatal msg="validate service connection: CRI v1 runtime API is not implemented for endpoint \"unix:///var/run/cri-dockerd.sock\": rpc error: code = Unimplemented desc = unknown service runtime.v1.RuntimeService"
https://github.com/kubeflow/katib/actions/runs/3695006408/jobs/6257556328#step:3:131
ref: https://github.com/manusa/actions-setup-minikube/releases/tag/v2.7.2
**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets …
> Upgrade the actions-setup-minikube version to v2.7.2

- cmd/suggestion/skopt/v1beta1/requirements.txt
- examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
- examples/v1beta1/trial-images/mxnet-mnist/requirements.txt
I pinned the NumPy version with v1.23.5 in the mxnet-mnist image and the skopt suggestion image to avoid the following errors:
- mxnet-mnist
```sh
I1223 17:32:59.235460      19 main.go:396] Trial Name: grid-ssmbrpvl
I1223 17:33:07.242688      19 main.go:139] /usr/local/lib/python3.9/site-packages/mxnet/numpy/utils.py:37: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.  (This may have returned Python scalars in past versions.
I1223 17:33:07.242711      19 main.go:139]   bool = onp.bool
I1223 17:33:07.244035      19 main.go:139] Traceback (most recent call last):
I1223 17:33:07.244094      19 main.go:139]   File "/opt/mxnet-mnist/mnist.py", line 24, in <module> …
```
> Pin the NumPy version with v1.23.5 in some images

- manifests/v1beta1/components/controller/katib-config.yaml
- pkg/suggestion/v1beta1/internal/search_space.py
- pkg/suggestion/v1beta1/optuna/base_service.py
- pkg/suggestion/v1beta1/optuna/service.py
- test/unit/v1beta1/suggestion/test_optuna_service.py
I added a mechanism to support grid search in Optuna Suggestion Service since we will remove Chocolate Suggestion Service as mentioned in #2058.
Also, I switched the default Suggestion Service for grid search to Optuna Suggestion Service in katib-config.
Part of #2058
**Checklist:**
> Support for grid search algorithm in Optuna Suggestion Service

- cmd/new-ui/v1beta1/main.go
- manifests/v1beta1/components/ui/rbac.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/kubeflow-katib-roles.yaml
- pkg/new-ui/v1beta1/backend.go
Implementation of the backend for fetching logs, as a part of https://github.com/kubeflow/katib/issues/1764.  
Providing a route `/katib/fetch_trial_logs/` to obtain logs for a specific trial.  
Logs are obtained from a master pod.
> Backend for getting logs of a trial

- cmd/earlystopping/medianstop/v1beta1/Dockerfile
- cmd/metricscollector/v1beta1/tfevent-metricscollector/Dockerfile
- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/hyperband/v1beta1/Dockerfile
- cmd/suggestion/hyperopt/v1beta1/Dockerfile
- cmd/suggestion/nas/darts/v1beta1/Dockerfile
- cmd/suggestion/nas/enas/v1beta1/Dockerfile
- cmd/suggestion/optuna/v1beta1/Dockerfile
- cmd/suggestion/pbt/v1beta1/Dockerfile
- cmd/suggestion/skopt/v1beta1/Dockerfile
- docs/developer-guide.md
- examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
- examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.cpu
- examples/v1beta1/trial-images/mxnet-mnist/Dockerfile
- examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
- examples/v1beta1/trial-images/simple-pbt/Dockerfile
- examples/v1beta1/trial-images/tf-mnist-with-summaries/Dockerfile
- test/unit/v1beta1/requirements.txt
I upgraded Python version to 3.10 since Python 3.9 no longer fixes bugs, according to [this](https://devguide.python.org/versions/#supported-versions).
> 3.9 | PEP 596 | security | 2020-10-05 | 2025-10 | Łukasz Langa
Also, I upgraded pytest version to avoid the error, `E   TypeError: required field "lineno" missing from alias`.
ref: https://github.com/pytest-dev/pytest/pull/8540
Fixes #
**Checklist:**
> Upgrade Python version to 3.10

- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- examples/v1beta1/trial-images/enas-cnn-cifar10/Dockerfile.gpu
- examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
- examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
- examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
- sdk/python/v1beta1/kubeflow/katib/constants/constants.py
I upgraded the Tensorflow version.
Fixes #
**Checklist:**
> Upgrade Tensorflow version

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-graph-echarts/trials-graph-echarts.component.ts
This PR enables actions in the experiment graph and specifically:
- Restore action which resets the graph
- Save image action
> frontend: Enable actions in experiment graph

- examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
- examples/v1beta1/trial-images/darts-cnn-cifar10/requirements.txt
- examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
- examples/v1beta1/trial-images/pytorch-mnist/requirements.txt
- test/e2e/v1beta1/scripts/gh-actions/build-load.sh
I upgraded PyTorch version to v1.13.0.
Fixes #
**Checklist:**
> Upgrade PyTorch version to v1.13.0

- cmd/db-manager/v1beta1/Dockerfile
- cmd/suggestion/goptuna/v1beta1/Dockerfile
- cmd/suggestion/hyperband/v1beta1/Dockerfile
- cmd/suggestion/hyperopt/v1beta1/Dockerfile
- cmd/suggestion/nas/darts/v1beta1/Dockerfile
- cmd/suggestion/nas/enas/v1beta1/Dockerfile
- cmd/suggestion/optuna/v1beta1/Dockerfile
- cmd/suggestion/pbt/v1beta1/Dockerfile
- cmd/suggestion/skopt/v1beta1/Dockerfile
I upgraded the grpc-health-probe version to fix some security issues.
- CVE-2022-27664
- CVE-2022-32149
Fixes #
**Checklist:**
> Upgrade grpc-health-probe version to fix some security issues

- manifests/v1beta1/installs/katib-with-kubeflow/istio-authorizationpolicy.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/kustomization.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/patches/enable-ui-authz-checks.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/patches/istio-sidecar-injection.yaml
- manifests/v1beta1/installs/katib-with-kubeflow/patches/ui-rbac.yaml
- pkg/new-ui/v1beta1/backend.go
This is a follow-up PR from: https://github.com/kubeflow/katib/pull/1983
Currently, in kubeflow mode, any workload/pod can set the `kubeflow-userid` header and communicate with the backend of the Katib UI. Since the code for securing the backend is merged we need to provide a way to enable this feature.
Changes to `install-with-kubeflow` manifests:
- Enable Istio sidecar injection for katib-ui component
- Introduce AuthorizationPolicies: 
- `katib-ui`: Allow traffic only from the `istio-ingressgateway` towards the UI backend. We can trust `IGW` as we are sure it's setting the user header correctly.
- Enable authz checks for `katib-ui` backend (set `APP_DISABLE_AUTH` ENV var to false)
- Update `ClusterRole` to provide RBAC persmissions for the …
> Update manifests to enable authorization check mechanisms for katib-UI in kubeflow mode

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Use the same logic as for the SDK Training Client: https://github.com/kubeflow/training-operator/pull/1740.
/assign @gaocegege @johnugeorge @tenzen-y
> [SDK] Use Katib Client without Kube Config

- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/controller.v1beta1/suggestion/composer/composer_test.go
- pkg/controller.v1beta1/suggestion/suggestion_controller_test.go
- pkg/util/v1beta1/katibconfig/config.go
- pkg/util/v1beta1/katibconfig/config_test.go
This PR adds more fields to the `SuggestionConfig` that is used to populate the main container of the Suggestion deployment. It adds fields `command`, `args`, `envs` that can be used to pass arguments to the executable. This allows the user to easily parametrize the suggestion algorithm/executable itself by passing values using these new fields.   
Fixes #1737 (at least partly)
**Checklist:**
> More container fields for SuggestionConfig

- scripts/v1beta1/release.sh
After this PR: https://github.com/kubeflow/katib/pull/1951, we should modify release script to make correct version replace.
> Fix Release Script for Updating SDK Version

- docs/release/README.md
- sdk/python/v1beta1/setup.py
Also, I removed item from the release script doc.
> Bump Katib Python SDK to 0.15.0rc0 version

- operators/katib-ui/src/charm.py
I reformated katib-operators with `black operators/*/src`.
This PR will fix the following error:
```shell
would reformat /home/runner/work/katib/katib/operators/katib-ui/src/charm.py
Oh no! 💥 💔 💥
1 file would be reformatted, 2 files would be left unchanged.
Error: Process completed with exit code 1.
```
https://github.com/kubeflow/katib/actions/runs/4173685371/jobs/7226319287
After:
```shell
$ black --check operators/*/src
All done! ✨ 🍰 ✨
3 files would be left unchanged.
```
Blocking: #2101 
Fixes #
**Checklist:**
> Reformat katib-operators

- operators/katib-ui/src/charm.py
Cherry-pick of #2114  on release-0.15.
Fixes #
**Checklist:**
> Automated cherry pick of #2114: Reformat katib-operators

- pkg/new-ui/v1beta1/backend.go
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-details.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.html
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.scss
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/trials-table/trial-details/trial-logs/trial-logs.module.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
In this PR:
- Create a distinct `LOGS` tab, which displays the trial's logs in the Trial details page.
- Don't show the backend's error popup for logs, but show the message error in the admonition.
- Update the message the backend sends to not just expose that logs are not there because `retain` might not be set, but also because the cluster was scaled down.
Related issue: https://github.com/kubeflow/katib/issues/1764
Related PR: https://github.com/kubeflow/katib/pull/2039
> [kwa-trials-logs] Create the LOGS tab of Trial's details page in KWA

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-creation/nas-operations/operation/operation.component.ts
I removed an unused import, `EventsV1beta1Api`.
Blocking: #2111 
Fixes #
**Checklist:**
> UI: Remove an unsed import, EventV1beta1Api

- CHANGELOG.md
- docs/release/changelog.py
I added Katib Changelog for Katib v0.15.0-rc.0
I grouped PRs in the following categories:
- Core Features
- UI Improvements
- SDK Improvements
- Bug fixes 
- Documentation
- Misc
Please check the PR grouping and let me know what we should change.
I think, when we are going to make official Katib 0.15 release and [create a GitHub release](https://github.com/kubeflow/katib/releases/tag/v0.14.0), we should point all breaking changes and the most valuable features to the Top.
It is one of the biggest Katib releases (**over 130 commits**) with a lot of great new features.
Thanks everyone for your hard work!
/assign @johnugeorge @gaocegege @tenzen-y @anencore94 @kimwnasptd @elenzio9 @orfeas-k @apo-ger @d-gol @shaowei-su @zhixian82 @fischor @keisuke-umezawa
> Add Changelog for Katib v0.15.0-rc.0

- pkg/new-ui/v1beta1/frontend/src/app/pages/experiment-details/experiment-details.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/config.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/delete-modal-config.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.spec.ts
- pkg/new-ui/v1beta1/frontend/src/app/pages/experiments/experiments.component.ts
- pkg/new-ui/v1beta1/frontend/src/app/services/backend.service.ts
This PR adds support for all-namespaces in KWA.
Related PR: https://github.com/kubeflow/kubeflow/pull/6958
> kwa(front): Support all namespaces

- CHANGELOG.md
I added Changelog for Katib v0.15.0
@kimwnasptd @apo-ger I've added breaking change about Katib authz in this release.
Please let me know if that sounds good.
/assign @gaocegege @johnugeorge @tenzen-y @elenzio9 @kimwnasptd @apo-ger
> Add Changelog for Katib v0.15.0

- CHANGELOG.md
To avoid confusion around recent Katib SDK changes (e.g. https://github.com/kubeflow/katib/issues/2132), I've added the SDK breaking change to the Changelog for 0.15 release.
cc @johnugeorge @tenzen-y @anencore94
> Add SDK Breaking Change to Changelog

- cmd/earlystopping/medianstop/v1beta1/requirements.txt
- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/hyperband/v1beta1/requirements.txt
- cmd/suggestion/hyperopt/v1beta1/requirements.txt
- cmd/suggestion/nas/darts/v1beta1/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- cmd/suggestion/optuna/v1beta1/requirements.txt
- cmd/suggestion/pbt/v1beta1/requirements.txt
- cmd/suggestion/skopt/v1beta1/requirements.txt
- sdk/python/v1beta1/setup.py
I relaxed the version restrictions on dependencies in the Python SDK.
Fixes #2139
**Checklist:**
> Relax dependencies restriction for the gRPC libraries

- .github/workflows/publish-conformance-images.yaml
- Dockerfile.conformance
- conformance/run.sh
* This PR contains the changes required for [katib conformance test](https://docs.google.com/document/d/1TRUKUY1zCCMdgF-nJ7QtzRwifsoQop0V8UnRo-GWlpI/edit#heading=h.qkn0t2llzyaq).
* Added `Dockerfile.conformance` docker file to build container which contains test required for katib conformance.
* Added `publish-conformance-images.yaml` github action to publish conformance test docker image as part of CI.
> Containerize tests for katib-conformance

- Dockerfile.conformance
**What this PR does / why we need it**: 
* Currently, the conformance docker image raises an import error `ModuleNotFoundError: No module named 'kubeflow.katib.katib_api_pb2'`
* It seems in `setup.py` we're copying a file from `pkg/` directory to `kubeflow/katib` directory which we don't check in into github. https://github.com/kubeflow/katib/blob/master/sdk/python/v1beta1/setup.py#L29-L36
* Since `katib_api_pb2.py` was present in `.gitingore`, it was not highlighted in my ide/terminal and somehow I missed it in my local testing. https://github.com/kubeflow/katib/blob/master/sdk/python/v1beta1/.gitignore#L5
**Checklist:**
> Fix conformance docker image

- hack/gen-python-sdk/post_gen.py
- sdk/python/v1beta1/kubeflow/katib/models/__init__.py
Fixes: https://github.com/kubeflow/katib/issues/2110
Currently, we need to import all Kubernetes models to Katib SDK, so SDK can do proper deserialization.
We need to track better solution in: https://github.com/kubeflow/training-operator/issues/1723
/assign @johnugeorge @tenzen-y @votti
> SDK: Import all Kubernetes Models

- pkg/new-ui/v1beta1/backend.go
I fixed UI backend that should return proper value when Kubernetes Job Fails. When Job Fails, it spawns multiple Pods and our UI shows this: `More than one master replica found`.
To fix this, I follow this:
1.  If one Succeeded or Running Pod exists, we print the logs.
1. Otherwise, print logs from one of Failed Pods.
/assign @tenzen-y @kimwnasptd @johnugeorge @apo-ger @d-gol
> [UI] Fix Trial Logs when Kubernetes Job Fails

- .github/workflows/e2e-test-darts-cifar10.yaml
- .github/workflows/e2e-test-enas-cifar10.yaml
- .github/workflows/e2e-test-mxnet-mnist.yaml
- .github/workflows/e2e-test-pytorch-mnist.yaml
- .github/workflows/e2e-test-simple-pbt.yaml
- .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
- .github/workflows/e2e-test-ui-random-search-postgres.yaml
- .github/workflows/template-publish-image/action.yaml
- .github/workflows/template-setup-e2e-test/action.yaml
I replaced actions to set up minikube with [medyagh/setup-minikube](https://github.com/medyagh/setup-minikube) since using manusa/actions-setup-minikube seems to no longer be maintained, and the action doesn't support kubernetes v1.26.
related to: https://github.com/kubeflow/katib/pull/2177
Fixes #
**Checklist:**
> Replace action to setup minikube with medyagh/setup-minikube

- .github/workflows/test-go.yaml
- Makefile
We can stop explicitly setting a cpu architecture because the tool supports the arm64 platform since K8s v1.24.
https://github.com/kubernetes-sigs/kubebuilder/issues/2664#issuecomment-1149956592
Fixes #
**Checklist:**
> Allow install binaries for the arm64 in the envtest

- cmd/db-manager/v1beta1/Dockerfile
- cmd/suggestion/goptuna/v1beta1/Dockerfile
- cmd/suggestion/hyperband/v1beta1/Dockerfile
- cmd/suggestion/hyperopt/v1beta1/Dockerfile
- cmd/suggestion/nas/darts/v1beta1/Dockerfile
- cmd/suggestion/nas/enas/v1beta1/Dockerfile
- cmd/suggestion/optuna/v1beta1/Dockerfile
- cmd/suggestion/pbt/v1beta1/Dockerfile
- cmd/suggestion/skopt/v1beta1/Dockerfile
- manifests/v1beta1/components/db-manager/db-manager.yaml
- pkg/controller.v1beta1/consts/const.go
- pkg/controller.v1beta1/suggestion/composer/composer.go
- pkg/controller.v1beta1/suggestion/composer/composer_test.go
The built-in gRPC container probe has been enabled as a default since K8s v1.24.
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-a-grpc-liveness-probe
So we should replace grpc_health_probe with a built-in one.
Fixes #
**Checklist:**
> Replace grpc_health_probe with the built-in gRPC container probe feature

- Makefile
- docs/developer-guide.md
- go.mod
- hack/verify-golangci-lint.sh
- pkg/db/v1beta1/mysql/mysql.go
- pkg/db/v1beta1/mysql/mysql_test.go
- pkg/db/v1beta1/postgres/postgres.go
- pkg/db/v1beta1/postgres/postgres_test.go
I upgraded Go version to v1.20.
Fixes #
**Checklist:**
> Upgrade Go version to v1.20

- manifests/v1beta1/components/webhook/webhooks.yaml
Fixes: https://github.com/kubeflow/katib/issues/1946.
I removed  `failurePolicy: Ignore` from our Admission Webhooks, so the default policy [will be used (which is `Fail`)](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#failure-policy).
/assign @kubeflow/wg-automl-leads @tenzen-y @ca-scribner
> Change failurePolicy to Fail for Katib Webhooks

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
Currently, the only way to specify cpu and memory limits and requests for trial containers is by submitting a manifest directly. For example: [here](https://github.com/kubeflow/katib/blob/master/examples/v1beta1/hp-tuning/random.yaml#L65-L68).
This PR adds resource specification capabilities to the SDK's `tune` method to achieve parity with direct manifest submission. `resources` defaults to `None`, which aligns with what `kubernetes.client.V1ResourceRequirements` defaults to, so when `resources` is not specified, the behavior is unmodified.
**Which issue(s) this PR fixes**
Fixes https://github.com/kubeflow/katib/issues/2191
> [SDK] Enable resource specification for trial containers

- cmd/katib-controller/v1beta1/main.go
- docs/developer-guide.md
- pkg/certgenerator/v1beta1/generator.go
The current implementation potentially has an issue to occur a memory leak since the katib-controller doesn't verify if the channel is closed. 
Also, I added docs about cert-manager integration to developer guide.
Fixes #
**Checklist:**
> Sending an empty data to the certsReady channel

- docs/release/README.md
- sdk/python/v1beta1/setup.py
Also, I updated release doc to publish SDK to PyPi.
> Bump Katib Python SDK to 0.16.0rc0 version

- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/webhook/webhooks.yaml
I introduced the label to skip injecting the metrics-collector to the katib system components.
Fixes #2069
**Checklist:**
> Skip to inject the metrics-collector pods to the katib controller

- test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
To fix flaky E2E, I added additional checks to verify if the components are ready.
Fixes #
**Checklist:**
> E2E: Add additional checks to verify if the components are ready

- pkg/certgenerator/v1beta1/generator.go
- pkg/certgenerator/v1beta1/generator_test.go
To avoid the below error the cert-generator should wait for the certs to be mounted inside the container:
```shell
{"level":"error","ts":"2023-08-05T18:14:44Z","logger":"entrypoint","msg":"Unable to run the manager","error":"open /tmp/cert/tls.crt: no such file or directory","stacktrace":"main.main\n\t/go/src/github.com/kubeflow/katib/cmd/katib-controller/v1beta1/main.go:164\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```
Currently, the cert-generator immediately sends data to the `certsReady` channel once the certs are generated.
However, since completed to generate certs doesn't mean the mounted secret is updated with certs, the cert-generator should wait for the mounted secret to be updated by kubelet.
ref: …
> Bug: Wait for the certs to be mounted inside the container

- manifests/v1beta1/components/webhook/kustomization.yaml
- manifests/v1beta1/components/webhook/secret.yaml
- manifests/v1beta1/installs/katib-external-db/kustomization.yaml
- manifests/v1beta1/installs/katib-standalone-postgres/kustomization.yaml
- manifests/v1beta1/installs/katib-standalone/kustomization.yaml
I removed a katib-webhook-cert Secret from the components directory to avoid startup issues in the cert-manager installation.
Also, I confirmed built manifests like this:
```shell
$ kustomize build manifests/v1beta1/installs/katib-cert-manager/ | grep -C2 "name: katib-webhook-cert"
kind: Certificate
metadata:
name: katib-webhook-cert
namespace: kubeflow
spec:
$ kustomize build manifests/v1beta1/installs/katib-external-db/ | grep -C2 "name: katib-webhook-cert"
kind: Secret
metadata:
name: katib-webhook-cert
namespace: kubeflow
---
$ kustomize build manifests/v1beta1/installs/katib-leader-election/ | grep -C2 "name: katib-webhook-cert"
kind: Secret
metadata:
name: katib-webhook-cert
namespace: kubeflow
---
$ kustomize build …
```
> Remove a katib-webhook-cert Secret from components

- cmd/katib-controller/v1beta1/main.go
Currently, the controller checks if the cert-generator is enabled before starting `setupControllers`.
https://github.com/kubeflow/katib/blob/7f0d9229facf9047624d697e8f7ccd77a4690ed7/cmd/katib-controller/v1beta1/main.go#L136-L149
So, if the cert-generator is disabled, the controller sends data to `certsReady` channel before the controller starts waiting for certs to get ready. By this behavior, in the katib-with-kubeflow, the controller eternally keeps waiting for the certs to get ready.
https://github.com/kubeflow/katib/blob/7f0d9229facf9047624d697e8f7ccd77a4690ed7/cmd/katib-controller/v1beta1/main.go#L170-L171
**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when …
> Start waiting for certs to be ready before sending data to the channel

- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
- examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
- pkg/metricscollector/v1beta1/tfevent-metricscollector/tfevent_loader.py
- sdk/python/v1beta1/kubeflow/katib/constants/constants.py
I upgraded the Tensorflow version to v2.13.0.
Fixes #
**Checklist:**
> Upgrade Tensorflow version to v2.13.0

- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/webhook/webhooks.yaml
Cherry-pick of #2203 on release-0.16.
Fixes #
**Checklist:**
> Automated cherry pick of #2203: Skip to inject the metrics-collector pods to the katib controller

- test/e2e/v1beta1/scripts/gh-actions/setup-katib.sh
Cherry-pick of https://github.com/kubeflow/katib/pull/2202 on release-0.16.
Fixes #
**Checklist:**
> Automated cherry pick of #2202: E2E: Add additional checks to verify if the components are ready

- cmd/katib-controller/v1beta1/main.go
Cherry-pick of https://github.com/kubeflow/katib/pull/2209 on release-0.16.
Fixes #
**Checklist:**
> Automated cherry pick of #2209: Start waiting for certs to be ready before sending data to the channel

- CHANGELOG.md
I've added Changelog for Katib v0.16.0-rc.1
/assign @johnugeorge @tenzen-y 
/cc @kubeflow/release-team
> Add Changelog for Katib v0.16.0-rc.1

- pkg/certgenerator/v1beta1/generator.go
Currently, we use the klog in the cert-generator and the controller-runtime logger in other controllers, such as the experiment-controller. So the manager output logs using a different format from the other controllers for the cert-generator, as shown below:
```shell
...
{"level":"info","ts":"2023-08-18T04:36:53Z","msg":"Starting server","kind":"health probe","addr":"[::]:18080"}
{"level":"info","ts":"2023-08-18T04:36:53Z","msg":"starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
I0818 04:36:54.087010       1 generator.go:199] Generating self-signed public certificate and private key.
{"level":"info","ts":"2023-08-18T04:36:54Z","logger":"controller-runtime.healthz","msg":"healthz check failed","statuses":[{}]}
I0818 …
```
> Use the controller-runtime logger in the cert-generator

- .github/workflows/stale.yaml
Currently, Stale Actions process a few issues/PRs per run every day: https://github.com/kubeflow/katib/actions/runs/5941243672
I changed Stale action to run every 5 hour to process more stale issues/PRs.
That should help us to track more issues and don't hit GitHub REST API limits: https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limits-for-requests-from-github-actions
Also, I changed `operations-per-run` to 60.
WDYT @tenzen-y @johnugeorge ?
> Run Stale Action Every 5th Hour

- .github/workflows/build-and-publish-images.yaml
- .github/workflows/e2e-test-darts-cifar10.yaml
- .github/workflows/e2e-test-enas-cifar10.yaml
- .github/workflows/e2e-test-mxnet-mnist.yaml
- .github/workflows/e2e-test-pytorch-mnist.yaml
- .github/workflows/e2e-test-simple-pbt.yaml
- .github/workflows/e2e-test-tf-mnist-with-summaries.yaml
- .github/workflows/e2e-test-ui-random-search-postgres.yaml
- .github/workflows/stale.yaml
- .github/workflows/test-go.yaml
- .github/workflows/test-lint.yaml
- .github/workflows/test-node.yaml
- .github/workflows/test-python.yaml
- examples/v1beta1/trial-images/mxnet-mnist/install-arm-performance-libraries.sh
I updated Ubuntu version to `22.04` for our E2E tests to fix errors.
For more context follow this thread: https://github.com/kubeflow/katib/pull/2153#discussion_r1304485202
> Update Ubuntu to 22.04 for E2E Tests

- ROADMAP.md
I created initial draft for Katib ROADMAP 2022/2023.
I tried to consolidated features that we implemented in 2022, since we didn't update the ROADMAP in 2022 (if I missed some significant features that we've done, please let me know).
Please let me know if you have better ideas how to name headers.
Let's discuss the items during next month and finalise the ROADMAP.
/cc @johnugeorge @gaocegege @tenzen-y @anencore94 @kimwnasptd @elenzio9 @orfeas-k @apo-ger @d-gol @shaowei-su @zhixian82 @fischor @keisuke-umezawa @jbottum @DnPlas @juliusvonkohout 
cc @kubeflow/wg-training-leads
> Add Katib ROADMAP 2022/2023

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
If you call `KatibClient.tune` using an experiment name that already exists, you get a giant traceback with the relevant / helpful message not being at the bottom. We had a user struggle to debug this on their own.
This PR simply raises a more helpful exception in the event of a 409 (name conflict) response from the API.
**Checklist:**
> [SDK] Raise more human-readable name conflict exception

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
The `algorithm_settings` cannot be set in the `tune` method of the python SDK, therefore many details [here](https://www.kubeflow.org/docs/components/katib/experiment/#search-algorithms-in-detail) cannot be immediately used if not submitting the manifest directly. 
This PR adds the capability to do it. By default, `algorithm_settings` is set to `None` which aligns with the initiation of `V1beta1AlgorithmSpec`. So when not setting `algorithm_settings` the behavior is not changed.
Fixes #2225
> [SDK] Add 'algorithm_settings' in client tune

- cmd/suggestion/optuna/v1beta1/requirements.txt
- pkg/suggestion/v1beta1/optuna/service.py
- test/unit/v1beta1/suggestion/test_optuna_service.py
Since Optuna recently moved `cmaes` to optional dependencies, our CI is failing: https://github.com/optuna/optuna/pull/4901.
I bumped Optuna to 3.3.0 version to unblock it, we can keep specific version of Optuna for now to avoid such errors.
If we need to relax the version, we can discuss the long-term plan on how to identify such errors in advance.
Also, I noticed that we have incorrect validation for `cmaes` in Optuna service.
We need to check that Search Space has more than 2 dimensional continues parameters instead of checking Algorithm Settings, similar to Goptuna: https://github.com/kubeflow/katib/blob/master/pkg/suggestion/v1beta1/goptuna/service.go#L188-L196
/assign @tenzen-y @johnugeorge @c-bata @shipengcheng1230
> Fix Optuna Validation for CMA-ES

- sdk/python/v1beta1/setup.py
> Bump Katib Python SDK to 0.16.0 version

- CHANGELOG.md
I've added Changelog for Katib v0.16.0
Thanks everyone for making successful Katib release!
/cc @johnugeorge @tenzen-y @kubeflow/release-team
> Add Changelog for Katib v0.16.0

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
The `env` and `env_from` cannot be directly set in the client `tune` method. Recently I found myself need to set up proxy environment variables for cross-region data access. Doing so inside the existing python objective function seems less desirable than having them set through these two specifications. 
This PR enables this capability. By default, these two are set to None which aligns with [V1Container](https://github.com/kubernetes-client/python/blob/36cfbe68a509d9b9d33395b22b6fa94d7d46c30f/kubernetes/client/models/v1_container.py#L89). Therefore, behavior is not modified when not setting them.
~Also, there was a missing of `cmaes` package when testing optuna suggestion. Therefore I added it in the optuna requirements.txt.~ (Rebased the master …
> [SDK] Add `env` & `env_from` in client tune

- Makefile
We need to install typing-extensions v4.6.0 or newer to resolve the following CI error:
> E   ImportError: cannot import name 'TypeAliasType' from 'typing_extensions' (/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/typing_extensions.py)
https://github.com/kubeflow/katib/actions/runs/7400396607/job/20133921603?pr=2250#step:4:594
The root cause is that the sqlalchemy on which the optuna depends requires typing-extensions v4.6.0 or newer:
Optuna dependencies: https://github.com/optuna/optuna/blob/v3.3.0/pyproject.toml#L40
sqlalchemy dependencies: https://github.com/sqlalchemy/sqlalchemy/blob/4871a2f72f5f0e514fe81a8caa17a14f9fc51300/setup.cfg#L38-L39
**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes …
> Install typing-extensions v4.6.3 for Optuna

- docs/developer-guide.md
I added the coding guide to the contribution guide.
Part-of #2186
**Checklist:**
> Add Technical and style guide to the contribution guide

- pkg/db/v1beta1/common/const.go
- pkg/db/v1beta1/mysql/init.go
- pkg/db/v1beta1/postgres/init.go
- pkg/util/v1beta1/env/env.go
- pkg/util/v1beta1/env/env_test.go
Currently, DB Manager automatically tries to create `observation_logs` table on startup using `CREATE TABLE IF NOT EXISTS` clause. However, this part does not work when DB user does not have enough privilege to create table if DB schema creation is handled by manual admin process.
To address this, we have hard-forked the repository and built our own image after commenting out table creation part so far. Since I guess there might be similar need to skip table creation from other than us, I've added an environment variable option to skip table creation along with simple logic to validate `observation_logs` table structure with `SELECT` statement.
([ml-metadata allows](https://github.com/google/ml-metadata/blob/master/ml_metadata/proto/metadata_store.pr …
> DB: Add environment variable option to skip DB table creationˆ

- pkg/db/v1beta1/common/const.go
- pkg/db/v1beta1/postgres/postgres.go
- pkg/db/v1beta1/postgres/postgres_test.go
In postgres, `sslmode` may has [different value](https://www.postgresql.org/docs/current/libpq-ssl.html#LIBPQ-SSL-PROTECTION) such as `disable`, `prefer` and `require`. But for now in [postgres.go#L52](https://github.com/kubeflow/katib/blob/master/pkg/db/v1beta1/postgres/postgres.go#L52) it only allows `disable`. So we should add an environment variable option to allow users to specify the value of `sslmode`.
Fixes https://github.com/kubeflow/katib/issues/2244
**Checklist:**
(Need to update list of [Environment Variables for Katib Components](https://www.kubeflow.org/docs/components/katib/env-var …
> Add environment variable option to set postgres ssl mode

- examples/v1beta1/trial-images/darts-cnn-cifar10/architect.py
- examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py
If I use the original program, I will get this error when running darts-gpu, 
```
<architect.Architect object at 0x7fe597aad780>
Traceback (most recent call last):
File "/home/sifa/docker/katib/examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py", line 259, in <module>
main()
File "/home/sifa/docker/katib/examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py", line 155, in main
train(train_loader, valid_loader, model, architect, w_optim, alpha_optim,
File "/home/sifa/docker/katib/examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py", line 194, in train
architect.unrolled_backward(train_x, train_y, valid_x, valid_y, lr, w_optim)
File "/home/sifa/docker/katib/examples/v1beta1/trial-images/darts-cnn-cifar10/architect.py", line …
```
> Fix tensor devices for DARTS Trial

- examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.cpu
- examples/v1beta1/trial-images/darts-cnn-cifar10/Dockerfile.gpu
- examples/v1beta1/trial-images/darts-cnn-cifar10/requirements.txt
- examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.cpu
- examples/v1beta1/trial-images/pytorch-mnist/Dockerfile.gpu
- examples/v1beta1/trial-images/pytorch-mnist/requirements.txt
- sdk/python/v1beta1/kubeflow/katib/constants/constants.py
I upgraded PyTorch version to v2.2.1.
This is a blocker of #2278 
Fixes #
**Checklist:**
> Upgrade PyTorch version to v2.2.1

- pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
Add unit test cases for files in Text format in `file-metricscollector_test.go`, including:
1. "Positive case for logs in TEXT format" test case
2. "Invalid file name" test case
3. "Invalid file format" test case
4. "Invalid timestamp for logs in TEXT format" test case
5. "Missing objective metric in training logs" test case
Fixes #1756 
**Checklist:**
> chore: add unit testcases for files in Text format.

- .github/workflows/test-go.yaml
We sometimes face the following error when we retry CI. So, I enabled the parallel mode to avoid the error.
```shell
bad response status from coveralls: 422
{"message":"Can't add a job to a build that is already closed. Build 8475719809 is closed. See docs.coveralls.io/parallel-builds","error":true}
Error: Error: The process '/home/runner/work/_actions/shogo82148/actions-goveralls/v1/bin/goveralls_linux_amd64' failed with exit code 1
```
https://github.com/kubeflow/katib/actions/runs/8475719809/job/23237738755?pr=2285#step:5:29
Docs: https://github.com/shogo82148/actions-goveralls?tab=readme-ov-file#parallel-job-example
**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the …
> CI: Enable parallel mode for the coveralls

- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
- examples/v1beta1/trial-images/enas-cnn-cifar10/requirements.txt
- examples/v1beta1/trial-images/tf-mnist-with-summaries/requirements.txt
I upgraded the TensorFlow version to v2.16.1.
~~This is a blocker of #2278.~~
Fixes #
**Checklist:**
> Upgrade TensorFlow version to v2.16.1

- pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector.go
- pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
Current error comparison in file-metricscollector_test.go is based on a boolean rather than the error content  To make test cases more detailed and accurate, we should expose and compare errors. 
And also @tenzen-y suggested that `t.TempDir` should be used for generating test directory. So I replace static directories with `t.TempDir`.
Related discussion: https://github.com/kubeflow/katib/issues/1756#issuecomment-1983711306 https://github.com/kubeflow/katib/pull/2274#discussion_r1521725542
Fixes #1756 
**Checklist:**
> fix: clean up UTs for file metrics collector

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
I fixed the `env_per_trial` parameter assignment.
Currently, if user sets dict in `env_per_trial` we override it [to None in this condition.](https://github.com/kubeflow/katib/blob/7df05c23a55363ba7cbbd7b9859943562afd71f4/sdk/python/v1beta1/kubeflow/katib/api/katib_client.py#L347-L351)
/assign @kubeflow/wg-training-leads @shipengcheng1230 @droctothorpe
> [SDK] Fix env per Trial parameter in tune API

- Makefile
- docs/developer-guide.md
- docs/release/README.md
- scripts/v1beta1/build.sh
This PR should add support for `arm64` images to our release script.
> Support ARM64 arch for release images

- sdk/python/v1beta1/setup.py
/assign @kubeflow/wg-training-leads
> Bump Katib Python SDK to 0.17.0rc0 Version

- pkg/controller.v1beta1/experiment/manifest/generator_test.go
- pkg/controller.v1beta1/suggestion/suggestionclient/suggestionclient_test.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
Following the [suggestion](https://github.com/kubeflow/katib/pull/2289#discussion_r1566264061) to keep the test fields private within Go unit tests, this PR implements the necessary changes.
The unit tests for Go have been run and validated in [this CI Workflow](https://github.com/tariq-hasan/katib/actions/runs/8840443938).
Fixes #
**Checklist:**
> Make test fields private in Go unit tests

- cmd/suggestion/skopt/v1beta1/requirements.txt
This should fix our CI for skopt suggestion. We are getting this error in the most recent `sckit-learn` version:
```
E   ImportError: cannot import name 'check_pandas_support' from 'sklearn.utils' 
(/Users/avelichk/miniconda3/envs/katib-ci/lib/python3.9/site-packages/sklearn/utils/__init__.py)
```
Eventually, we should deprecate skopt in favour of `GPSampler` from Optuna: https://github.com/kubeflow/katib/issues/2280#issuecomment-1993658378 for bayesian optimization in Katib.
cc @contramundum53 
/assign @kubeflow/wg-training-leads
> Fix Scikit-Learn Version for Skopt Tests

- examples/v1beta1/tekton/README.md
> fix katib use crds token pipeline trail template guide

- docs/developer-guide.md
When building images from the source code on an Apple Silicon machine, following the `docs/developer-guide.md`, I encountered the "rosetta error: bss_size overflow". This PR adds instructions to resolve this error by disabling Rosetta emulation in Docker Desktop settings.
Fixes #
**Checklist:**
> Fix apple silicon rosetta error when building images from the source code

- pkg/controller.v1beta1/trial/trial_controller_test.go
Fix unstable tests
#1649
**Checklist:**
> Fix TestReconcileBatchJob

- cmd/earlystopping/medianstop/v1beta1/requirements.txt
- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/hyperband/v1beta1/requirements.txt
- cmd/suggestion/hyperopt/v1beta1/requirements.txt
- cmd/suggestion/nas/darts/v1beta1/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- cmd/suggestion/optuna/v1beta1/requirements.txt
- cmd/suggestion/pbt/v1beta1/requirements.txt
- cmd/suggestion/skopt/v1beta1/requirements.txt
- sdk/python/v1beta1/setup.py
I upgraded the protobuf versions with >=4.21.12,<5.
I aligned those versions with KFP (https://github.com/kubeflow/pipelines/blob/sdk-2.7.0/sdk/python/requirements.in#L21).
Fixes #2346
**Checklist:**
> Upgrade the protobuf version to >=4.21.12,<5

- Makefile
- scripts/v1beta1/release.sh
I removed the code generation from our release script.
Currently, we have to clone Katib repo to the `$GOPATH/src/github.com/kubeflow/katib` to correctly run Go code generation. However, in the release script we clone the Katib repo to the [temp directory](https://github.com/kubeflow/katib/blob/0947169ab114dfe71f5492b0d094d4c2054052a9/scripts/v1beta1/release.sh#L43-L47) to avoid un-sync Git history.
We don't need to run `make generate` in our release script, since we have [the code generation check](https://github.com/andreyvelich/katib/blob/0947169ab114dfe71f5492b0d094d4c2054052a9/hack/verify-generated-codes.sh#L24) for each PR.
Also, we don't need to publish images with COMMIT tag during the release.
> Remove code generation from release script

- Makefile
- scripts/v1beta1/release.sh
Cherry pick this PR to release 0.17 branch: https://github.com/kubeflow/katib/pull/2363
> Cherry pick: Remove code generation from release script (#2363)

- sdk/python/v1beta1/setup.py
Updating Katib Python SDK to the 0.17.0rc1 version.
> Bump Katib Python SDK to 0.17.0rc1 version

- manifests/v1beta1/components/webhook/webhooks.yaml
caBundle hasn't been a required key since k8s v1.13
Removing it makes it simpler to deploy katib with terraform.
Fixes #2367
**Checklist:**
> Remove default caBundle value

- CHANGELOG.md
I updated Changelog for Katib 0.17.0-rc.1.
Thanks everyone for your contribution to Katib 🎉
/assign @kubeflow/wg-training-leads @forsaken628 @Mersho
> Add Changelog for Katib v0.17.0-rc.1

- pkg/webhook/v1beta1/experiment/validation_webhook.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
For experiment validator, return errors after all fields are verified.
Fixes https://github.com/kubeflow/katib/issues/2302
**Checklist:**
> Use ErrorList for experiment validator

- cmd/metricscollector/v1beta1/file-metricscollector/main.go
- go.mod
- go.sum
**What this PR does / why we need it**: This issue helps to migrate the dependency of the `tail` package in `katib` from https://github.com/hpcloud/tail to https://github.com/nxadm/tail. This change is required because `hpcloud` has not been maintaining their implementation of the `tail` package. 
Fixes https://github.com/kubeflow/katib/issues/2299
**Checklist:**
> Replaced hpcloud with nxadm for tail package in Go

- CHANGELOG.md
I updated Changelog for Katib v0.17.0
Thanks everyone for your contribution to Katib 🎉
/hold for review
/assign @kubeflow/wg-training-leads @kubeflow/release-team @lkaybob @ckcd @bharathk005 @shipengcheng1230 @droctothorpe @Electronic-Waste @sifa1024 @tarilabs  @forsaken628 @Mersho
> Add Changelog for Katib v0.17.0

- sdk/python/v1beta1/setup.py
Updating Katib Python SDK to the 0.17.0 version.
> Bump Katib Python SDK to 0.17.0 version

- .github/workflows/trigger-rerun-test.yaml
Followup on this KFP PR: https://github.com/kubeflow/pipelines/pull/10930
I added ability to re-run failed GitHub Actions without manually re-trigger them.
That allows contributors without GitHub write access to trigger the failed actions.
The following commands are supported by this action:
`/rerun-all` - rerun all failed workflows.
`/rerun-workflow <workflow name>` - rerun a specific failed workflow. Only one workflow name can be specified.
Reference: https://github.com/estroz/rerun-actions
/assign @kubeflow/wg-training-leads @rimolive
> Add command to re-run GitHub Actions tests

- docs/proposals/suggestion.md
implmentation -> implementation
**Checklist:**
> docs: update suggestion.md

- examples/v1beta1/argo/README.md
add  Workflow trialResources for argo
fix the doc error
when run `kubectl patch Deployment katib-controller -n kubeflow --type=json \
-p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--trial-resources=Workflow.v1alpha1.argoproj.io"}]'` ,will get pod CrashLoopBackOff
**Checklist:**
> Update Instructions for Argo Workflows

- hack/gen-python-sdk/post_gen.py
- pkg/apis/controller/common/v1beta1/common_types.go
- pkg/controller.v1beta1/consts/const.go
- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
- pkg/webhook/v1beta1/pod/utils.go
- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
I add a new parameter `metrics_collector_config` to `tune` function. Design details: https://github.com/kubeflow/katib/blob/cc95ef03cb25df3d86a1a1c20c9c69bad17fce92/docs/proposals/push-based-metrics-collection.md#add-new-parameter-in-tune
Fixes #
**Checklist:**
> [GSoC] Add New Parameter in `tune`

- pkg/metricscollector/v1beta1/file-metricscollector/file-metricscollector_test.go
We removed the dependency of `protocmp` in `google.golang.org/protobuf/testing/protocmp` by ignoring the unexported fields in `v1beta1.ObservationLog`(generated by grpc).
Fixes #2389 
**Checklist:**
> fix: remove the dependency of `protocmp` in `google.golang.org/protobuf/testing/protocmp`.

- pkg/apis/controller/experiments/v1beta1/experiment_types.go
- pkg/apis/v1beta1/openapi_generated.go
- pkg/apis/v1beta1/swagger.json
- pkg/client/controller/applyconfiguration/experiments/v1beta1/feasiblespace.go
- sdk/python/v1beta1/docs/V1beta1FeasibleSpace.md
- sdk/python/v1beta1/kubeflow/katib/models/v1beta1_feasible_space.py
- Added `DistributionType` to `ParameterSpec` in `pkg/apis/controller/experiments/v1beta1/experiment_types.go`.
- Defined `DistributionType`.
Fixes #2374 
**Checklist:**
> [GSoC] Added `DistributionType` to Experiment API

- docs/proposals/parameter-distribution.md
> [GSOC] Support for various Parameter distributions in Katib

- .flake8
- .pre-commit-config.yaml
- examples/v1beta1/kubeflow-pipelines/mpi-job-horovod.py
- examples/v1beta1/trial-images/darts-cnn-cifar10/architect.py
- examples/v1beta1/trial-images/darts-cnn-cifar10/model.py
- examples/v1beta1/trial-images/darts-cnn-cifar10/operations.py
- examples/v1beta1/trial-images/darts-cnn-cifar10/run_trial.py
- examples/v1beta1/trial-images/darts-cnn-cifar10/search_space.py
- examples/v1beta1/trial-images/darts-cnn-cifar10/utils.py
- examples/v1beta1/trial-images/enas-cnn-cifar10/ModelConstructor.py
- examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
- examples/v1beta1/trial-images/enas-cnn-cifar10/op_library.py
- examples/v1beta1/trial-images/pytorch-mnist/mnist.py
- examples/v1beta1/trial-images/tf-mnist-with-summaries/mnist.py
- hack/gen-python-sdk/post_gen.py
- sdk/python/v1beta1/kubeflow/__init__.py
- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
- sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
- sdk/python/v1beta1/kubeflow/katib/api/report_metrics.py
- sdk/python/v1beta1/kubeflow/katib/api/search.py
- sdk/python/v1beta1/kubeflow/katib/utils/utils.py
This PR implements the flake8 linter and black formatting as a pre-commit hook to ensure code quality and adherence to style guidelines. 
Fixes #
**Checklist:**
**`Not sure if I there is a need to exclude something else in the pre-commit config??.
If it should be please let me know`**
> Enhance pre-commit hooks with flake8 and black

- pkg/webhook/v1beta1/pod/inject_webhook_test.go
I refactored `/pkg/webhook/v1beta1/pod/inject_webhook_test.go` with rule described in [Developer Guide](https://github.com/kubeflow/katib/blob/master/docs/developer-guide.md):
1. Use [cmp.Diff](https://pkg.go.dev/github.com/google/go-cmp/cmp#Diff) instead of reflect.Equal, to provide useful comparisons.
2. Define test cases as maps instead of slices to avoid dependencies on the running order. Map key should be equal to the test case name.
Fixes #2388
**Checklist:**
> [Test] Refactor `inject_webhook_test.go` according to the Developer Guide

- pkg/controller.v1beta1/experiment/manifest/generator.go
- pkg/controller.v1beta1/experiment/manifest/generator_test.go
- pkg/controller.v1beta1/trial/util/job_util_test.go
- pkg/suggestion/v1beta1/goptuna/converter_test.go
- pkg/webhook/v1beta1/pod/inject_webhook.go
- pkg/webhook/v1beta1/pod/inject_webhook_test.go
- pkg/webhook/v1beta1/pod/utils.go
Following the suggestion https://github.com/kubeflow/katib/pull/2281#pullrequestreview-1926741952 from @tenzen-y this code change provides a more thorough comparison of errors through the introduction of error constants and the replacement of `replace.DeepEqual` with `cmp.Diff`.
In addition some of the test cases in `generator_test.go` have been revised to allow for a more thorough comparison of error messages.
Finally cosmetic changes have been applied to some of the tests in order to match the style of the code in [config_test.go](https://github.com/kubeflow/katib/pull/2281#discussion_r1519020624) that compares error constants.
**Which issue(s) this PR fixes** _(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close …
> Introduced error constants and replaced reflect with cmp

- pkg/common/v1beta1/katib_manager_util.go
- pkg/controller.v1beta1/trial/managerclient/managerclient.go
- pkg/controller.v1beta1/trial/trial_controller.go
- pkg/controller.v1beta1/trial/trial_controller_test.go
- pkg/controller.v1beta1/trial/trial_controller_util.go
- pkg/mock/v1beta1/trial/managerclient/katibmanager.go
I made some compatibility changes to the Trial Controller. Design details: https://github.com/kubeflow/katib/blob/master/docs/proposals/push-based-metrics-collection.md#compatibility-changes-in-trial-controller
Fixes #
**Checklist:**
> [GSoC] Compatibility Changes in Trial Controller

- examples/v1beta1/trial-images/enas-cnn-cifar10/ModelConstructor.py
- examples/v1beta1/trial-images/enas-cnn-cifar10/RunTrial.py
This should fix E2E tests for ENAS example and unblock other PRs.
I removed the Dropout layer from the model constructor given that it fails for TensorFlow distributed training:
```
ValueError: creating distributed tf.Variable with aggregation=MEAN and 
a non-floating dtype is not supported, please use a different aggregation or dtype
```
/assign @kubeflow/wg-training-leads @Electronic-Waste @tariq-hasan
> Remove Dropout layer from ENAS Trial container to fix E2E tests

- examples/v1beta1/kubeflow-pipelines/README.md
As @yehudit1987 discussed with me in the Slack, there is a missing guide link in the environment setting section : https://github.com/kubeflow/katib/blob/master/examples/v1beta1/kubeflow-pipelines/README.md#multi-user-pipelines-setup 
We decided to fix it to make the guide accessible to new-comers.
cc👀 @yehudit1987 @kubeflow/wg-automl-leads 
Fixes #
**Checklist:**
> doc(example): fix the broken link.

- pkg/controller.v1beta1/trial/trial_controller_test.go
As I described in #2431, a propagated `gomega.Gomega` will improve the debuggability of the UTs.
Fixes #2431 
**Checklist:**
> fix(trial): use propagated gomega to improve debuggability.

- cmd/earlystopping/medianstop/v1beta1/requirements.txt
- cmd/metricscollector/v1beta1/tfevent-metricscollector/requirements.txt
- cmd/suggestion/hyperband/v1beta1/requirements.txt
- cmd/suggestion/hyperopt/v1beta1/requirements.txt
- cmd/suggestion/nas/darts/v1beta1/requirements.txt
- cmd/suggestion/nas/enas/v1beta1/requirements.txt
- cmd/suggestion/optuna/v1beta1/requirements.txt
- cmd/suggestion/pbt/v1beta1/requirements.txt
- cmd/suggestion/skopt/v1beta1/requirements.txt
- sdk/python/v1beta1/setup.py
- test/unit/v1beta1/requirements.txt
After #2344 got merged, our python grpc client is generated by `buf.build/grpc/python:v1.64.1`. However, our Python SDK still uses `grpcio>=1.41.1`, resulting in some errors like #2427.
This is due to the update of [grpcio packge](https://github.com/grpc/grpc/releases/tag/v1.64.0) (the corresponding PR is https://github.com/grpc/grpc/pull/36371). In v1.64.0, grpcio introduced a parameter `__register_method` to `unary_unary`, which would be called by grpc client  in:
https://github.com/kubeflow/katib/blob/eb8af4d50266b51c77ea895585ff535c8e9137f9/pkg/apis/manager/v1beta1/python/api_pb2_grpc.py#L19-L23
And in `tensorflow/tensorflow:2.13.0`, the `grpcio` version is `v1.56.0` while in `tensorflow/tensorflow:2.17.0` the version is `v1.64.1`. So the error …
> Upgrade grpcio version to v1.64.1

- .github/workflows/template-publish-image/action.yaml
We need to manually rerun CI jobs due to cache exporting errors:
```
#33 exporting to GitHub Actions Cache
#33 preparing build cache for export
#33 writing layer sha256:043014c17c0e213c5220cb1c47f39ba308ecad3e3d912504a1f69cc0689bdcdd
#33 preparing build cache for export 865.0s done
#33 writing layer sha256:043014c17c0e213c5220cb1c47f39ba308ecad3e3d912504a1f69cc0689bdcdd 600.1s done
#33 ERROR: error writing layer blob: maximum timeout reached
```
We can ignore this with `ignore-error=true`, following [this guide](https://docs.docker.com/build/cache/backends/gha/#synopsis). Same work is done in https://github.com/kubeflow/training-operator/pull/2336
**Which issue(s) this PR fixes** :
Fixes #
**Checklist:**
> Ignore cache exporting errors in the image building workflows

- CONTRIBUTING.md
- cmd/db-manager/v1beta1/main.go
**What this PR does / why we need it**: I would like to be able to pass a different listen-address to handle other ports or even ipv6.
Fixes #
**Checklist:**
> chore: supporting the listen-address parameter on db-manager

- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/webhook/webhooks.yaml
The [AdmissionWebhookMatchConditions](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#matching-requests-matchconditions) became beta feature in k8s 1.28, which means the feature-gate is enabled by default.
This PR switches the webhook configuration from objectSelector to AdmissionWebhookMatchConditions to exclude the katib-controller pod creation deadlock.
Fixes #2206 
**Checklist:**
> Update MutatingWebhookConfiguration: Switch from objectSelector to AdmissionWebhookMatchConditions

- pkg/ui/v1beta1/frontend/cypress/e2e/index-page.cy.ts
- pkg/ui/v1beta1/frontend/src/app/pages/experiments/config.ts
Showing experiments from newest to oldest by default instead of sorting them by name. 
Now the experiments are initially shown as follows:
**Which issue(s) this PR fixes** :
Fixes #2475 
**Checklist:**
> Sort experiments by descending creation date by default in katib-ui

- sdk/python/v1beta1/kubeflow/katib/api/katib_client.py
- sdk/python/v1beta1/kubeflow/katib/api/katib_client_test.py
- sdk/python/v1beta1/kubeflow/katib/utils/utils.py
This PR handles potential name errors for PVCs gracefully.
Fixes #2491 
**Checklist:**
> [SDK] improve PVC creation name error

- Makefile
We need to install typing-extensions v4.10.0 or newer to resolve the following CI error:
```
from typing_extensions import TypeIs as _TypeIs
E   ImportError: cannot import name 'TypeIs' from 'typing_extensions'
```
The root cause is that `TypeIs` was introduced in version 4.10.0 according to the typing-extensions documentation, and torch 2.6.0 requires typing-extensions>=4.10.0, 
Fixes #2503
**Checklist:**
> Install typing-extensions v4.10.0 to fix Python test error

- cmd/ui/v1beta1/Dockerfile
CI job for Katib UI docker image currently takes 1 h 55 min and its flaky, by using smaller images and correcting npm commands, after using github action caches it builds in 11 mins. hopefully its not flaky anymore. 
ref: https://github.com/mahdikhashan/katib/actions/runs/13089634195/job/36524775489
Fixes #2501 
**Checklist:**
> [CI] optimize katib ui dockerfile 

- pkg/webhook/v1beta1/experiment/validator/validator.go
- pkg/webhook/v1beta1/experiment/validator/validator_test.go
As of now, the suggestion service does not start if the concatenation of algorithm and experiment name are more than 63 characters. The experiment gets created successfully on the dashboard, but never runs. This PR directly rejects all experiments with names longer than 40 characters. 
Fixes #2454 
**Checklist:**
- [ X ] [Docs](https://www.kubeflow.org/docs/components/katib/) included if any changes are user facing
**Previous Behavior:**
Would successfully allow the experiment to be submitted, and would also create the experiment. However, the suggestion service would crash silently with no error output.
**New Behavior:**
Throws the following error message:
```
Error from server: error when creating …
```
> Set experiment names at a max of 40 characters. 

- .github/workflows/e2e-test-pytorch-mnist.yaml
- examples/v1beta1/hp-tuning/optuna-distribution.yaml
- pkg/suggestion/v1beta1/hyperopt/base_service.py
- pkg/suggestion/v1beta1/optuna/base_service.py
- test/unit/v1beta1/suggestion/test_optuna_service.py
> [GSOC] `optuna` suggestion service logic update

- sdk/python/v1beta1/setup.py
Part of: https://github.com/kubeflow/katib/issues/2386.
Updating SDK version to the latest release.
/assign @kubeflow/wg-training-leads @Electronic-Waste @helenxie-bit
> Bump Katib Python SDK to 0.18.0rc0 version

- CHANGELOG.md
This is Changelog for Katib v0.18.0
Thanks everyone for your contributions 🎉
/assign @kubeflow/wg-training-leads @Electronic-Waste @helenxie-bit @kubeflow/release-team @shashank-iitbhu @saileshd1402 @mahdikhashan @forsaken628 @Jerry-yz @AydanPirani @mahdikhashan @Doris-xm @lianghao208 @caiofralmeida @gonmmarques @Ygnas @droctothorpe @jaffe-fly @eltociear @tariq-hasan @ckcd @vihangm @garymm
> chore(docs): Add Changelog Katib v0.18.0

- manifests/v1beta1/components/controller/controller.yaml
- manifests/v1beta1/components/db-manager/db-manager.yaml
- manifests/v1beta1/components/mysql/mysql.yaml
- manifests/v1beta1/components/ui/ui.yaml
related to https://github.com/kubeflow/manifests/pull/3050
**Checklist:**
> Fix PSS restricted warnings

- README.md
Part of: https://github.com/kubeflow/community/issues/834
I added OpenSSF badge for Kubeflow Katib project.
/cc @kubeflow/kubeflow-steering-committee @kubeflow/wg-training-leads @varodrig @castrojo
> chore(docs): Add OpenSSF Badge

- SECURITY.md
Part of: https://github.com/kubeflow/community/issues/851, https://github.com/kubeflow/community/issues/858.
This doc explains how to report security vulnerability for Kubeflow Katib project. This is required for CNCF graduation.
/cc @kubeflow/kubeflow-steering-committee @varodrig @castrojo @kubeflow/wg-training-leads @Electronic-Waste @helenxie-bit
> feat(docs): Guide to report security vulnerabilities
